#!/bin/bash

#echo "This is the commit-msg hook."
#echo "Arguments: |$@|"
filename=$1
#cat $1


#change_type=$(update_type)
#echo "change_type = $change_type"


ret=0
#for rev in $(new_revisions); do
printed_header=0
#subject=$(git log -1 $rev --format=%s)
subject=$(head -n 1 $filename)
#echo "subject = $subject"

.git/hooks/check_message "$subject"
ret=$?

if [ "$ret" != 0 ] ; then
    echo "Aborting commit, due to keyword errors."
    echo
    exit 1;
fi

exit 0
