[build-system]
requires = ["scikit-build-core", "pybind11"]
build-backend = "scikit_build_core.build"

[project]
name = "pcms"
version = "0.4.0"

[tool.scikit-build.cmake.define]
PCMS_ENABLE_Python = true

[tool.pytest.ini_options]
testpaths = ["test/python"]
python_files = "test_*.py"
python_classes = "Test*"
python_functions = "test_*"
addopts = "--strict-markers"
