#!/bin/bash
# Generate checksums for GENE runs and check if a given list of checksums agrees with the files

# Default behaviour: Control checksums for .dat files
fileext=".dat"
mode="help"
chkfilename="checksums.sha"


while getopts wrf:uc: opt
do
   case $opt in
      #Generate and write checksums
      w) mode="writechk";;
      #Update existing checksums
      u) mode="updchk";;
      #Read checksum file and test them
      r) mode="readchk";;
      # Optional file ending, otherwise default to .dat
      f) fileext=$OPTARG;;
      # Optional name of the checksum file
      c) chkfilename=$OPTARG;;
   esac
done

if [ "$mode" = "readchk" ]
then
   sha1sum -c $chkfilename
elif [ "$mode" = "writechk" ]
then
   if [ -e $chkfilename ]
   then
      echo "$chkfilename exists. Extending file. Use -u to update the checksums."
   fi
   sha1sum *$fileext >> $chkfilename
elif [ "$mode" = "updchk" ]
then
   if [ ! -e $chkfilename ]
   then
      echo "$chkfilename does not exist. Use -w to create it."
   else
      sha1sum *$fileext > $chkfilename
   fi
else
   echo "Usage: runchecksum [-w| -u | -r] [-f filextension for -w and -u] [-c file with checksums]"
fi
