#ifndef WDMCPL_SRC_WDMCPL_PROFILE_H
#define WDMCPL_SRC_WDMCPL_PROFILE_H
#include <perfstubs_api/timer.h>

#define WDMCPL_FUNCTION_TIMER PERFSTUBS_SCOPED_TIMER_FUNC()

#endif // WDMCPL_SRC_WDMCPL_PROFILE_H
