/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.1.1+fortran
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */
/* -----------------------------------------------------------------------------
 *  This section contains generic SWIG labels for method/variable
 *  declarations/attributes, and other compiler dependent labels.
 * ----------------------------------------------------------------------------- */

/* template workaround for compilers that cannot correctly implement the C++ standard */
#ifndef SWIGTEMPLATEDISAMBIGUATOR
# if defined(__SUNPRO_CC) && (__SUNPRO_CC <= 0x560)
#  define SWIGTEMPLATEDISAMBIGUATOR template
# elif defined(__HP_aCC)
/* Needed even with `aCC -AA' when `aCC -V' reports HP ANSI C++ B3910B A.03.55 */
/* If we find a maximum version that requires this, the test would be __HP_aCC <= 35500 for A.03.55 */
#  define SWIGTEMPLATEDISAMBIGUATOR template
# else
#  define SWIGTEMPLATEDISAMBIGUATOR
# endif
#endif

/* inline attribute */
#ifndef SWIGINLINE
# if defined(__cplusplus) || (defined(__GNUC__) && !defined(__STRICT_ANSI__))
#   define SWIGINLINE inline
# else
#   define SWIGINLINE
# endif
#endif

/* attribute recognised by some compilers to avoid 'unused' warnings */
#ifndef SWIGUNUSED
# if defined(__GNUC__)
#   if !(defined(__cplusplus)) || (__GNUC__ > 3 || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4))
#     define SWIGUNUSED __attribute__ ((__unused__))
#   else
#     define SWIGUNUSED
#   endif
# elif defined(__ICC)
#   define SWIGUNUSED __attribute__ ((__unused__))
# else
#   define SWIGUNUSED
# endif
#endif

#ifndef SWIG_MSC_UNSUPPRESS_4505
# if defined(_MSC_VER)
#   pragma warning(disable : 4505) /* unreferenced local function has been removed */
# endif
#endif

#ifndef SWIGUNUSEDPARM
# ifdef __cplusplus
#   define SWIGUNUSEDPARM(p)
# else
#   define SWIGUNUSEDPARM(p) p SWIGUNUSED
# endif
#endif

/* internal SWIG method */
#ifndef SWIGINTERN
# define SWIGINTERN static SWIGUNUSED
#endif

/* internal inline SWIG method */
#ifndef SWIGINTERNINLINE
# define SWIGINTERNINLINE SWIGINTERN SWIGINLINE
#endif

/* exporting methods */
#if defined(__GNUC__)
#  if (__GNUC__ >= 4) || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4)
#    ifndef GCC_HASCLASSVISIBILITY
#      define GCC_HASCLASSVISIBILITY
#    endif
#  endif
#endif

#ifndef SWIGEXPORT
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   if defined(STATIC_LINKED)
#     define SWIGEXPORT
#   else
#     define SWIGEXPORT __declspec(dllexport)
#   endif
# else
#   if defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
#     define SWIGEXPORT __attribute__ ((visibility("default")))
#   else
#     define SWIGEXPORT
#   endif
# endif
#endif

/* calling conventions for Windows */
#ifndef SWIGSTDCALL
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   define SWIGSTDCALL __stdcall
# else
#   define SWIGSTDCALL
# endif
#endif

/* Deal with Microsoft's attempt at deprecating C standard runtime functions */
#if !defined(SWIG_NO_CRT_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_CRT_SECURE_NO_DEPRECATE)
# define _CRT_SECURE_NO_DEPRECATE
#endif

/* Deal with Microsoft's attempt at deprecating methods in the standard C++ library */
#if !defined(SWIG_NO_SCL_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_SCL_SECURE_NO_DEPRECATE)
# define _SCL_SECURE_NO_DEPRECATE
#endif

/* Deal with Apple's deprecated 'AssertMacros.h' from Carbon-framework */
#if defined(__APPLE__) && !defined(__ASSERT_MACROS_DEFINE_VERSIONS_WITHOUT_UNDERSCORES)
# define __ASSERT_MACROS_DEFINE_VERSIONS_WITHOUT_UNDERSCORES 0
#endif

/* Intel's compiler complains if a variable which was never initialised is
 * cast to void, which is a common idiom which we use to indicate that we
 * are aware a variable isn't used.  So we just silence that warning.
 * See: https://github.com/swig/swig/issues/192 for more discussion.
 */
#ifdef __INTEL_COMPILER
# pragma warning disable 592
#endif


#ifndef SWIGEXTERN
# ifdef __cplusplus
#   define SWIGEXTERN extern
# else
#   define SWIGEXTERN
# endif
#endif


#define SWIG_exception_impl(DECL, CODE, MSG, RETURNNULL) \
 { throw std::logic_error("In " DECL ": " MSG); }


enum SwigMemFlags {
    SWIG_MEM_OWN = 0x01,
    SWIG_MEM_RVALUE = 0x02,
};


#define SWIG_check_nonnull(PTR, TYPENAME, FNAME, FUNCNAME, RETURNNULL) \
  if (!(PTR)) { \
    SWIG_exception_impl(FUNCNAME, SWIG_NullReferenceError, \
                        "Cannot pass null " TYPENAME " (class " FNAME ") " \
                        "as a reference", RETURNNULL); \
  }


namespace swig {
enum AssignmentType {
  ASSIGNMENT_DEFAULT,
  ASSIGNMENT_NODESTRUCT,
  ASSIGNMENT_SMARTPTR
};
}



#define SWIG_VERSION 0x040101
#define SWIGFORTRAN
#define SWIGPOLICY_WdmCplFieldAdapter swig::ASSIGNMENT_DEFAULT

#ifdef __cplusplus
#include <utility>
/* SwigValueWrapper is described in swig.swg */
template<typename T> class SwigValueWrapper {
  struct SwigSmartPointer {
    T *ptr;
    SwigSmartPointer(T *p) : ptr(p) { }
    ~SwigSmartPointer() { delete ptr; }
    SwigSmartPointer& operator=(SwigSmartPointer& rhs) { T* oldptr = ptr; ptr = 0; delete oldptr; ptr = rhs.ptr; rhs.ptr = 0; return *this; }
    void reset(T *p) { T* oldptr = ptr; ptr = 0; delete oldptr; ptr = p; }
  } pointer;
  SwigValueWrapper& operator=(const SwigValueWrapper<T>& rhs);
  SwigValueWrapper(const SwigValueWrapper<T>& rhs);
public:
  SwigValueWrapper() : pointer(0) { }
  SwigValueWrapper& operator=(const T& t) { SwigSmartPointer tmp(new T(t)); pointer = tmp; return *this; }
#if __cplusplus >=201103L
  SwigValueWrapper& operator=(T&& t) { SwigSmartPointer tmp(new T(std::move(t))); pointer = tmp; return *this; }
  operator T&&() const { return std::move(*pointer.ptr); }
#else
  operator T&() const { return *pointer.ptr; }
#endif
  T *operator&() const { return pointer.ptr; }
  static void reset(SwigValueWrapper& t, T *p) { t.pointer.reset(p); }
};

/*
 * SwigValueInit() is a generic initialisation solution as the following approach:
 * 
 *       T c_result = T();
 * 
 * doesn't compile for all types for example:
 * 
 *       unsigned int c_result = unsigned int();
 */
template <typename T> T SwigValueInit() {
  return T();
}

#if __cplusplus >=201103L
# define SWIG_STD_MOVE(OBJ) std::move(OBJ)
#else
# define SWIG_STD_MOVE(OBJ) OBJ
#endif

#endif


#include <stdexcept>


/* Support for the `contract` feature.
 *
 * Note that RETURNNULL is first because it's inserted via a 'Replaceall' in
 * the fortran.cxx file.
 */
#define SWIG_contract_assert(RETURNNULL, EXPR, MSG) \
 if (!(EXPR)) { SWIG_exception_impl("$decl", SWIG_ValueError, MSG, RETURNNULL); } 


#define SWIG_as_voidptr(a) const_cast< void * >(static_cast< const void * >(a)) 
#define SWIG_as_voidptrptr(a) ((void)SWIG_as_voidptr(*a),reinterpret_cast< void** >(a)) 


#include "wdmcpl/capi/client.h"


#ifdef HAVE_MPI
#include <mpi.h>
#endif


#include <stdint.h>


struct SwigClassWrapper {
    void* cptr;
    int cmemflags;
};


SWIGINTERN SwigClassWrapper SwigClassWrapper_uninitialized() {
    SwigClassWrapper result;
    result.cptr = NULL;
    result.cmemflags = 0;
    return result;
}


namespace swig {

template<class T, AssignmentType A>
struct DestructorPolicy {
  static SwigClassWrapper destroy(SwigClassWrapper self) {
    delete static_cast<T*>(self.cptr);
    return SwigClassWrapper_uninitialized();
  }
};
template<class T>
struct DestructorPolicy<T, ASSIGNMENT_NODESTRUCT> {
  static SwigClassWrapper destroy(SwigClassWrapper) {
    SWIG_exception_impl("assignment", SWIG_TypeError, "Invalid assignment: class type has private destructor", return SwigClassWrapper_uninitialized());
  }
};
}


namespace swig {

SWIGINTERN SwigClassWrapper capture(SwigClassWrapper other) {
  other.cmemflags &= ~SWIG_MEM_RVALUE;
  return other;
}

template<class T, AssignmentType A>
struct AssignmentPolicy {
  static SwigClassWrapper destroy(SwigClassWrapper self) {
    return DestructorPolicy<T, A>::destroy(self);
  }
  static SwigClassWrapper alias(SwigClassWrapper other) {
    SwigClassWrapper self = other;
    self.cmemflags &= ~SWIG_MEM_OWN;
    return self;
  }
  static SwigClassWrapper move_alias(SwigClassWrapper self, SwigClassWrapper other) {
    if (self.cmemflags & SWIG_MEM_OWN) {
      destroy(self);
    }
    return capture(other);
  }
  static SwigClassWrapper copy_alias(SwigClassWrapper self, SwigClassWrapper other) {
    if (self.cmemflags & SWIG_MEM_OWN) {
      destroy(self);
    }
    return capture(other);
  }
};

template<class T>
struct AssignmentPolicy<T, ASSIGNMENT_SMARTPTR> {
  static SwigClassWrapper destroy(SwigClassWrapper self) {
    return DestructorPolicy<T, ASSIGNMENT_SMARTPTR>::destroy(self);
  }
  static SwigClassWrapper alias(SwigClassWrapper other) {
    SwigClassWrapper self;
    self.cptr = new T(*static_cast<T*>(other.cptr));
    self.cmemflags = other.cmemflags | SWIG_MEM_OWN;
    return self;
  }
  static SwigClassWrapper move_alias(SwigClassWrapper self, SwigClassWrapper other) {
    self = copy_alias(self, other);
    self.cmemflags = other.cmemflags & ~SWIG_MEM_RVALUE;
    destroy(other);
    return self;
  }
  static SwigClassWrapper copy_alias(SwigClassWrapper self, SwigClassWrapper other) {
    // LHS and RHS should both 'own' their shared pointers
    T *pself = static_cast<T*>(self.cptr);
    T *pother = static_cast<T*>(other.cptr);
    *pself = *pother;
    return self;
  }
};

} // end namespace swig

template<class T, swig::AssignmentType A>
SWIGINTERN void SWIG_assign(SwigClassWrapper* self, SwigClassWrapper other) {
  typedef swig::AssignmentPolicy<T, A> Policy_t;

  if (self->cptr == NULL) {
    /* LHS is unassigned */
    if (other.cmemflags & SWIG_MEM_RVALUE) {
      /* Capture pointer from RHS, clear 'moving' flag */
      *self = swig::capture(other);
    } else {
      /* Aliasing another class; clear ownership or copy smart pointer */
      *self = Policy_t::alias(other);
    }
  } else if (other.cptr == NULL) {
    /* Replace LHS with a null pointer */
    *self = Policy_t::destroy(*self);
  } else if (self->cptr == other.cptr) {
    /* Self-assignment: ignore */
  } else if (other.cmemflags & SWIG_MEM_RVALUE) {
    /* Transferred ownership from a variable that's about to be lost.
     * Move-assign and delete the transient data */
    *self = Policy_t::move_alias(*self, other);
  } else {
    /* RHS shouldn't be deleted, alias to LHS */
    *self = Policy_t::copy_alias(*self, other);
  }
}

template<class T, swig::AssignmentType A>
SWIGINTERN void SWIG_free_rvalue(SwigClassWrapper other) {
  typedef swig::AssignmentPolicy<T, A> Policy_t;
  if (other.cmemflags & SWIG_MEM_RVALUE 
      && other.cmemflags & SWIG_MEM_OWN) {
    /* We own *and* are being passed an expiring value */
    Policy_t::destroy(other);
  }
}



#include <stdlib.h>
#ifdef _MSC_VER
# ifndef strtoull
#  define strtoull _strtoui64
# endif
# ifndef strtoll
#  define strtoll _strtoi64
# endif
#endif


struct SwigArrayWrapper {
    void* data;
    size_t size;
};


SWIGINTERN SwigArrayWrapper SwigArrayWrapper_uninitialized() {
  SwigArrayWrapper result;
  result.data = NULL;
  result.size = 0;
  return result;
}

extern "C" {
SWIGEXPORT void _wrap_WdmCplFieldAdapter_type_set(SwigClassWrapper *farg1, int const *farg2) {
  WdmCplFieldAdapter *arg1 = (WdmCplFieldAdapter *) 0 ;
  WdmCplAdapterType arg2 ;
  
  SWIG_check_nonnull(farg1->cptr, "WdmCplFieldAdapter *", "WdmCplFieldAdapter", "WdmCplFieldAdapter::type", return );
  arg1 = (WdmCplFieldAdapter *)farg1->cptr;
  arg2 = (WdmCplAdapterType)(*farg2);
  if (arg1) (arg1)->type = arg2;
}


SWIGEXPORT int _wrap_WdmCplFieldAdapter_type_get(SwigClassWrapper *farg1) {
  int fresult ;
  WdmCplFieldAdapter *arg1 = (WdmCplFieldAdapter *) 0 ;
  WdmCplAdapterType result;
  
  SWIG_check_nonnull(farg1->cptr, "WdmCplFieldAdapter *", "WdmCplFieldAdapter", "WdmCplFieldAdapter::type", return 0);
  arg1 = (WdmCplFieldAdapter *)farg1->cptr;
  result = (WdmCplAdapterType) ((arg1)->type);
  fresult = (int)(result);
  return fresult;
}


SWIGEXPORT void _wrap_WdmCplFieldAdapter_data_type_set(SwigClassWrapper *farg1, int const *farg2) {
  WdmCplFieldAdapter *arg1 = (WdmCplFieldAdapter *) 0 ;
  WdmCplType arg2 ;
  
  SWIG_check_nonnull(farg1->cptr, "WdmCplFieldAdapter *", "WdmCplFieldAdapter", "WdmCplFieldAdapter::data_type", return );
  arg1 = (WdmCplFieldAdapter *)farg1->cptr;
  arg2 = (WdmCplType)(*farg2);
  if (arg1) (arg1)->data_type = arg2;
}


SWIGEXPORT int _wrap_WdmCplFieldAdapter_data_type_get(SwigClassWrapper *farg1) {
  int fresult ;
  WdmCplFieldAdapter *arg1 = (WdmCplFieldAdapter *) 0 ;
  WdmCplType result;
  
  SWIG_check_nonnull(farg1->cptr, "WdmCplFieldAdapter *", "WdmCplFieldAdapter", "WdmCplFieldAdapter::data_type", return 0);
  arg1 = (WdmCplFieldAdapter *)farg1->cptr;
  result = (WdmCplType) ((arg1)->data_type);
  fresult = (int)(result);
  return fresult;
}


SWIGEXPORT SwigClassWrapper _wrap_new_WdmCplFieldAdapter() {
  SwigClassWrapper fresult ;
  WdmCplFieldAdapter *result = 0 ;
  
  result = (WdmCplFieldAdapter *)new WdmCplFieldAdapter();
  fresult.cptr = (void*)result;
  fresult.cmemflags = SWIG_MEM_RVALUE | (1 ? SWIG_MEM_OWN : 0);
  return fresult;
}


SWIGEXPORT void _wrap_delete_WdmCplFieldAdapter(SwigClassWrapper *farg1) {
  WdmCplFieldAdapter *arg1 = (WdmCplFieldAdapter *) 0 ;
  
  arg1 = (WdmCplFieldAdapter *)farg1->cptr;
  delete arg1;
}


SWIGEXPORT void _wrap_WdmCplFieldAdapter_op_assign__(SwigClassWrapper *farg1, SwigClassWrapper *farg2) {
  WdmCplFieldAdapter *arg1 = (WdmCplFieldAdapter *) 0 ;
  WdmCplFieldAdapter *arg2 = 0 ;
  
  (void)sizeof(arg1);
  (void)sizeof(arg2);
  SWIG_assign<WdmCplFieldAdapter, SWIGPOLICY_WdmCplFieldAdapter>(farg1, *farg2);
  
}


SWIGEXPORT SwigClassWrapper _wrap_wdmcpl_create_client(SwigArrayWrapper *farg1, int const *farg2) {
  SwigClassWrapper fresult ;
  char *arg1 = (char *) 0 ;
  MPI_Comm arg2 ;
  WdmCplClient *result = 0 ;
  
  arg1 = (char *)(farg1->data);
#ifdef HAVE_MPI
  arg2 = MPI_Comm_f2c((MPI_Fint)*farg2);
#else
  arg2 = *farg2;
#endif
  result = (WdmCplClient *)wdmcpl_create_client((char const *)arg1,SWIG_STD_MOVE(arg2));
  fresult.cptr = (void*)result;
  fresult.cmemflags = SWIG_MEM_RVALUE | (0 ? SWIG_MEM_OWN : 0);
  return fresult;
}


SWIGEXPORT void _wrap_wdmcpl_destroy_client(SwigClassWrapper *farg1) {
  WdmCplClient *arg1 = (WdmCplClient *) 0 ;
  
  arg1 = (WdmCplClient *)farg1->cptr;
  wdmcpl_destroy_client(arg1);
}


SWIGEXPORT SwigClassWrapper _wrap_wdmcpl_load_reverse_classification(SwigArrayWrapper *farg1, int const *farg2) {
  SwigClassWrapper fresult ;
  char *arg1 = (char *) 0 ;
  MPI_Comm arg2 ;
  WdmCplReverseClassificationHandle *result = 0 ;
  
  arg1 = (char *)(farg1->data);
#ifdef HAVE_MPI
  arg2 = MPI_Comm_f2c((MPI_Fint)*farg2);
#else
  arg2 = *farg2;
#endif
  result = (WdmCplReverseClassificationHandle *)wdmcpl_load_reverse_classification((char const *)arg1,SWIG_STD_MOVE(arg2));
  fresult.cptr = (void*)result;
  fresult.cmemflags = SWIG_MEM_RVALUE | (0 ? SWIG_MEM_OWN : 0);
  return fresult;
}


SWIGEXPORT void _wrap_wdmcpl_destroy_reverse_classification(SwigClassWrapper *farg1) {
  WdmCplReverseClassificationHandle *arg1 = (WdmCplReverseClassificationHandle *) 0 ;
  
  arg1 = (WdmCplReverseClassificationHandle *)farg1->cptr;
  wdmcpl_destroy_reverse_classification(arg1);
}


SWIGEXPORT int _wrap_wdmcpl_reverse_classification_count_verts(SwigClassWrapper *farg1) {
  int fresult ;
  WdmCplReverseClassificationHandle *arg1 = (WdmCplReverseClassificationHandle *) 0 ;
  int result;
  
  arg1 = (WdmCplReverseClassificationHandle *)farg1->cptr;
  result = (int)wdmcpl_reverse_classification_count_verts(arg1);
  fresult = (int)(result);
  return fresult;
}


SWIGEXPORT SwigClassWrapper _wrap_wdmcpl_create_xgc_field_adapter(SwigArrayWrapper *farg1, void const **farg2, int const *farg3, int const *farg4, SwigClassWrapper *farg5, in_overlap_function farg6) {
  SwigClassWrapper fresult ;
  char *arg1 = (char *) 0 ;
  void *arg2 = (void *) 0 ;
  int arg3 ;
  WdmCplType arg4 ;
  WdmCplReverseClassificationHandle *arg5 = (WdmCplReverseClassificationHandle *) 0 ;
  in_overlap_function arg6 = (in_overlap_function) 0 ;
  WdmCplFieldAdapter *result = 0 ;
  
  arg1 = (char *)(farg1->data);
  arg2 = (void *)(*farg2);
  arg3 = (int)(*farg3);
  arg4 = (WdmCplType)(*farg4);
  arg5 = (WdmCplReverseClassificationHandle *)farg5->cptr;
  arg6 = (in_overlap_function)(*farg6);
  result = (WdmCplFieldAdapter *)wdmcpl_create_xgc_field_adapter((char const *)arg1,arg2,arg3,arg4,(WdmCplReverseClassificationHandle const *)arg5,arg6);
  fresult.cptr = (void*)result;
  fresult.cmemflags = SWIG_MEM_RVALUE | (0 ? SWIG_MEM_OWN : 0);
  return fresult;
}


SWIGEXPORT void _wrap_wdmcpl_destroy_field_adapter(SwigClassWrapper *farg1) {
  WdmCplFieldAdapter *arg1 = (WdmCplFieldAdapter *) 0 ;
  
  arg1 = (WdmCplFieldAdapter *)farg1->cptr;
  wdmcpl_destroy_field_adapter(arg1);
}


SWIGEXPORT SwigClassWrapper _wrap_wdmcpl_add_field(SwigClassWrapper *farg1, SwigArrayWrapper *farg2, SwigClassWrapper *farg3) {
  SwigClassWrapper fresult ;
  WdmCplClient *arg1 = (WdmCplClient *) 0 ;
  char *arg2 = (char *) 0 ;
  WdmCplFieldAdapter *arg3 = (WdmCplFieldAdapter *) 0 ;
  WdmCplFieldHandle *result = 0 ;
  
  arg1 = (WdmCplClient *)farg1->cptr;
  arg2 = (char *)(farg2->data);
  arg3 = (WdmCplFieldAdapter *)farg3->cptr;
  result = (WdmCplFieldHandle *)wdmcpl_add_field(arg1,(char const *)arg2,arg3);
  fresult.cptr = (void*)result;
  fresult.cmemflags = SWIG_MEM_RVALUE | (0 ? SWIG_MEM_OWN : 0);
  return fresult;
}


SWIGEXPORT void _wrap_wdmcpl_send_field_name(SwigClassWrapper *farg1, SwigArrayWrapper *farg2) {
  WdmCplClient *arg1 = (WdmCplClient *) 0 ;
  char *arg2 = (char *) 0 ;
  
  arg1 = (WdmCplClient *)farg1->cptr;
  arg2 = (char *)(farg2->data);
  wdmcpl_send_field_name(arg1,(char const *)arg2);
}


SWIGEXPORT void _wrap_wdmcpl_receive_field_name(SwigClassWrapper *farg1, SwigArrayWrapper *farg2) {
  WdmCplClient *arg1 = (WdmCplClient *) 0 ;
  char *arg2 = (char *) 0 ;
  
  arg1 = (WdmCplClient *)farg1->cptr;
  arg2 = (char *)(farg2->data);
  wdmcpl_receive_field_name(arg1,(char const *)arg2);
}


SWIGEXPORT void _wrap_wdmcpl_send_field(SwigClassWrapper *farg1) {
  WdmCplFieldHandle *arg1 = (WdmCplFieldHandle *) 0 ;
  
  arg1 = (WdmCplFieldHandle *)farg1->cptr;
  wdmcpl_send_field(arg1);
}


SWIGEXPORT void _wrap_wdmcpl_receive_field(SwigClassWrapper *farg1) {
  WdmCplFieldHandle *arg1 = (WdmCplFieldHandle *) 0 ;
  
  arg1 = (WdmCplFieldHandle *)farg1->cptr;
  wdmcpl_receive_field(arg1);
}


} // extern

