/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.1.1+fortran
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */
/* -----------------------------------------------------------------------------
 *  This section contains generic SWIG labels for method/variable
 *  declarations/attributes, and other compiler dependent labels.
 * ----------------------------------------------------------------------------- */

/* template workaround for compilers that cannot correctly implement the C++ standard */
#ifndef SWIGTEMPLATEDISAMBIGUATOR
# if defined(__SUNPRO_CC) && (__SUNPRO_CC <= 0x560)
#  define SWIGTEMPLATEDISAMBIGUATOR template
# elif defined(__HP_aCC)
/* Needed even with `aCC -AA' when `aCC -V' reports HP ANSI C++ B3910B A.03.55 */
/* If we find a maximum version that requires this, the test would be __HP_aCC <= 35500 for A.03.55 */
#  define SWIGTEMPLATEDISAMBIGUATOR template
# else
#  define SWIGTEMPLATEDISAMBIGUATOR
# endif
#endif

/* inline attribute */
#ifndef SWIGINLINE
# if defined(__cplusplus) || (defined(__GNUC__) && !defined(__STRICT_ANSI__))
#   define SWIGINLINE inline
# else
#   define SWIGINLINE
# endif
#endif

/* attribute recognised by some compilers to avoid 'unused' warnings */
#ifndef SWIGUNUSED
# if defined(__GNUC__)
#   if !(defined(__cplusplus)) || (__GNUC__ > 3 || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4))
#     define SWIGUNUSED __attribute__ ((__unused__))
#   else
#     define SWIGUNUSED
#   endif
# elif defined(__ICC)
#   define SWIGUNUSED __attribute__ ((__unused__))
# else
#   define SWIGUNUSED
# endif
#endif

#ifndef SWIG_MSC_UNSUPPRESS_4505
# if defined(_MSC_VER)
#   pragma warning(disable : 4505) /* unreferenced local function has been removed */
# endif
#endif

#ifndef SWIGUNUSEDPARM
# ifdef __cplusplus
#   define SWIGUNUSEDPARM(p)
# else
#   define SWIGUNUSEDPARM(p) p SWIGUNUSED
# endif
#endif

/* internal SWIG method */
#ifndef SWIGINTERN
# define SWIGINTERN static SWIGUNUSED
#endif

/* internal inline SWIG method */
#ifndef SWIGINTERNINLINE
# define SWIGINTERNINLINE SWIGINTERN SWIGINLINE
#endif

/* exporting methods */
#if defined(__GNUC__)
#  if (__GNUC__ >= 4) || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4)
#    ifndef GCC_HASCLASSVISIBILITY
#      define GCC_HASCLASSVISIBILITY
#    endif
#  endif
#endif

#ifndef SWIGEXPORT
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   if defined(STATIC_LINKED)
#     define SWIGEXPORT
#   else
#     define SWIGEXPORT __declspec(dllexport)
#   endif
# else
#   if defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
#     define SWIGEXPORT __attribute__ ((visibility("default")))
#   else
#     define SWIGEXPORT
#   endif
# endif
#endif

/* calling conventions for Windows */
#ifndef SWIGSTDCALL
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   define SWIGSTDCALL __stdcall
# else
#   define SWIGSTDCALL
# endif
#endif

/* Deal with Microsoft's attempt at deprecating C standard runtime functions */
#if !defined(SWIG_NO_CRT_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_CRT_SECURE_NO_DEPRECATE)
# define _CRT_SECURE_NO_DEPRECATE
#endif

/* Deal with Microsoft's attempt at deprecating methods in the standard C++ library */
#if !defined(SWIG_NO_SCL_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_SCL_SECURE_NO_DEPRECATE)
# define _SCL_SECURE_NO_DEPRECATE
#endif

/* Deal with Apple's deprecated 'AssertMacros.h' from Carbon-framework */
#if defined(__APPLE__) && !defined(__ASSERT_MACROS_DEFINE_VERSIONS_WITHOUT_UNDERSCORES)
# define __ASSERT_MACROS_DEFINE_VERSIONS_WITHOUT_UNDERSCORES 0
#endif

/* Intel's compiler complains if a variable which was never initialised is
 * cast to void, which is a common idiom which we use to indicate that we
 * are aware a variable isn't used.  So we just silence that warning.
 * See: https://github.com/swig/swig/issues/192 for more discussion.
 */
#ifdef __INTEL_COMPILER
# pragma warning disable 592
#endif


#ifndef SWIGEXTERN
# ifdef __cplusplus
#   define SWIGEXTERN extern
# else
#   define SWIGEXTERN
# endif
#endif


#include <assert.h>
#define SWIG_exception_impl(DECL, CODE, MSG, RETURNNULL) \
 { printf("In " DECL ": " MSG); assert(0); RETURNNULL; }


enum {
    SWIG_MEM_OWN = 0x01,
    SWIG_MEM_RVALUE = 0x02,
};


#define SWIG_check_nonnull(PTR, TYPENAME, FNAME, FUNCNAME, RETURNNULL) \
  if (!(PTR)) { \
    SWIG_exception_impl(FUNCNAME, SWIG_NullReferenceError, \
                        "Cannot pass null " TYPENAME " (class " FNAME ") " \
                        "as a reference", RETURNNULL); \
  }



#define SWIG_VERSION 0x040101
#define SWIGFORTRAN

#include <stdio.h>
#if (defined(_MSC_VER) && (_MSC_VER < 1900)) || defined(__BORLANDC__) || defined(_WATCOM)
# ifndef snprintf
#  define snprintf _snprintf
# endif
#endif


/* Support for the `contract` feature.
 *
 * Note that RETURNNULL is first because it's inserted via a 'Replaceall' in
 * the fortran.cxx file.
 */
#define SWIG_contract_assert(RETURNNULL, EXPR, MSG) \
 if (!(EXPR)) { SWIG_exception_impl("$decl", SWIG_ValueError, MSG, RETURNNULL); } 


#define SWIG_as_voidptr(a) (void *)((const void *)(a)) 
#define SWIG_as_voidptrptr(a) ((void)SWIG_as_voidptr(*a),(void**)(a)) 


#include "wdmcpl/capi/client.h"


#ifdef HAVE_MPI
#include <mpi.h>
#endif


#include <stdint.h>


typedef struct {
    void* cptr;
    int cmemflags;
} SwigClassWrapper;


SWIGINTERN SwigClassWrapper SwigClassWrapper_uninitialized() {
    SwigClassWrapper result;
    result.cptr = NULL;
    result.cmemflags = 0;
    return result;
}


#include <stdlib.h>
#ifdef _MSC_VER
# ifndef strtoull
#  define strtoull _strtoui64
# endif
# ifndef strtoll
#  define strtoll _strtoi64
# endif
#endif


#include <string.h>


SWIGINTERN void SWIG_assign(SwigClassWrapper* self, SwigClassWrapper other) {
  if (self->cptr == NULL) {
    /* LHS is unassigned */
    if (other.cmemflags & SWIG_MEM_RVALUE) {
      /* Capture pointer from RHS, clear 'moving' flag */
      self->cptr = other.cptr;
      self->cmemflags = other.cmemflags & (~SWIG_MEM_RVALUE);
    } else {
      /* Become a reference to the other object */
      self->cptr = other.cptr;
      self->cmemflags = other.cmemflags & (~SWIG_MEM_OWN);
    }
  } else if (other.cptr == NULL) {
    /* Replace LHS with a null pointer */
    free(self->cptr);
    *self = SwigClassWrapper_uninitialized();
  } else if (self->cptr == other.cptr) {
    /* Self-assignment: ignore */
  } else {
    if (self->cmemflags & SWIG_MEM_OWN) {
      free(self->cptr);
    }
    self->cptr = other.cptr;
    if (other.cmemflags & SWIG_MEM_RVALUE) {
      /* Capture RHS */
      self->cmemflags = other.cmemflags & ~SWIG_MEM_RVALUE;
    } else {
      /* Point to RHS */
      self->cmemflags = other.cmemflags & ~SWIG_MEM_OWN;
    }
  }
}


typedef struct {
    void* data;
    size_t size;
} SwigArrayWrapper;


SWIGINTERN SwigArrayWrapper SwigArrayWrapper_uninitialized() {
  SwigArrayWrapper result;
  result.data = NULL;
  result.size = 0;
  return result;
}

SWIGEXPORT void _wrap_WdmCplFieldAdapter_type_set(SwigClassWrapper *farg1, int const *farg2) {
  struct WdmCplFieldAdapter *arg1 = (struct WdmCplFieldAdapter *) 0 ;
  WdmCplAdapterType arg2 ;
  
  SWIG_check_nonnull(farg1->cptr, "struct WdmCplFieldAdapter *", "WdmCplFieldAdapter", "WdmCplFieldAdapter::type", return );
  arg1 = (struct WdmCplFieldAdapter *)farg1->cptr;
  arg2 = (WdmCplAdapterType)(*farg2);
  if (arg1) (arg1)->type = arg2;
}


SWIGEXPORT int _wrap_WdmCplFieldAdapter_type_get(SwigClassWrapper *farg1) {
  int fresult ;
  struct WdmCplFieldAdapter *arg1 = (struct WdmCplFieldAdapter *) 0 ;
  WdmCplAdapterType result;
  
  SWIG_check_nonnull(farg1->cptr, "struct WdmCplFieldAdapter *", "WdmCplFieldAdapter", "WdmCplFieldAdapter::type", return 0);
  arg1 = (struct WdmCplFieldAdapter *)farg1->cptr;
  result = (WdmCplAdapterType) ((arg1)->type);
  fresult = (int)(result);
  return fresult;
}


SWIGEXPORT void _wrap_WdmCplFieldAdapter_data_type_set(SwigClassWrapper *farg1, int const *farg2) {
  struct WdmCplFieldAdapter *arg1 = (struct WdmCplFieldAdapter *) 0 ;
  WdmCplType arg2 ;
  
  SWIG_check_nonnull(farg1->cptr, "struct WdmCplFieldAdapter *", "WdmCplFieldAdapter", "WdmCplFieldAdapter::data_type", return );
  arg1 = (struct WdmCplFieldAdapter *)farg1->cptr;
  arg2 = (WdmCplType)(*farg2);
  if (arg1) (arg1)->data_type = arg2;
}


SWIGEXPORT int _wrap_WdmCplFieldAdapter_data_type_get(SwigClassWrapper *farg1) {
  int fresult ;
  struct WdmCplFieldAdapter *arg1 = (struct WdmCplFieldAdapter *) 0 ;
  WdmCplType result;
  
  SWIG_check_nonnull(farg1->cptr, "struct WdmCplFieldAdapter *", "WdmCplFieldAdapter", "WdmCplFieldAdapter::data_type", return 0);
  arg1 = (struct WdmCplFieldAdapter *)farg1->cptr;
  result = (WdmCplType) ((arg1)->data_type);
  fresult = (int)(result);
  return fresult;
}


SWIGEXPORT void _wrap_WdmCplFieldAdapter_xgc__set(SwigClassWrapper *farg1, SwigClassWrapper *farg2) {
  struct WdmCplFieldAdapter *arg1 = (struct WdmCplFieldAdapter *) 0 ;
  WdmCplXgcAdapter *arg2 = (WdmCplXgcAdapter *) 0 ;
  
  SWIG_check_nonnull(farg1->cptr, "struct WdmCplFieldAdapter *", "WdmCplFieldAdapter", "WdmCplFieldAdapter::xgc_", return );
  arg1 = (struct WdmCplFieldAdapter *)farg1->cptr;
  arg2 = (WdmCplXgcAdapter *)farg2->cptr;
  if (arg1) (arg1)->xgc_ = arg2;
}


SWIGEXPORT SwigClassWrapper _wrap_WdmCplFieldAdapter_xgc__get(SwigClassWrapper *farg1) {
  SwigClassWrapper fresult ;
  struct WdmCplFieldAdapter *arg1 = (struct WdmCplFieldAdapter *) 0 ;
  WdmCplXgcAdapter *result = 0 ;
  
  SWIG_check_nonnull(farg1->cptr, "struct WdmCplFieldAdapter *", "WdmCplFieldAdapter", "WdmCplFieldAdapter::xgc_", return SwigClassWrapper_uninitialized());
  arg1 = (struct WdmCplFieldAdapter *)farg1->cptr;
  result = (WdmCplXgcAdapter *) ((arg1)->xgc_);
  fresult.cptr = (void*)result;
  fresult.cmemflags = SWIG_MEM_RVALUE | (0 ? SWIG_MEM_OWN : 0);
  return fresult;
}


SWIGEXPORT SwigClassWrapper _wrap_new_WdmCplFieldAdapter() {
  SwigClassWrapper fresult ;
  struct WdmCplFieldAdapter *result = 0 ;
  
  result = (struct WdmCplFieldAdapter *)calloc(1, sizeof(struct WdmCplFieldAdapter));
  fresult.cptr = (void*)result;
  fresult.cmemflags = SWIG_MEM_RVALUE | (1 ? SWIG_MEM_OWN : 0);
  return fresult;
}


SWIGEXPORT void _wrap_delete_WdmCplFieldAdapter(SwigClassWrapper *farg1) {
  struct WdmCplFieldAdapter *arg1 = (struct WdmCplFieldAdapter *) 0 ;
  
  arg1 = (struct WdmCplFieldAdapter *)farg1->cptr;
  free((char *) arg1);
}


SWIGEXPORT void _wrap_WdmCplFieldAdapter_op_assign__(SwigClassWrapper *farg1, SwigClassWrapper *farg2) {
  struct WdmCplFieldAdapter *arg1 = (struct WdmCplFieldAdapter *) 0 ;
  struct WdmCplFieldAdapter *arg2 = 0 ;
  
  (void)sizeof(arg1);
  (void)sizeof(arg2);
  SWIG_assign(farg1, *farg2);
  
}


SWIGEXPORT SwigClassWrapper _wrap_wdmcpl_create_client(SwigArrayWrapper *farg1, int const *farg2) {
  SwigClassWrapper fresult ;
  char *arg1 = (char *) 0 ;
  MPI_Comm arg2 ;
  WdmCplClient *result = 0 ;
  
  arg1 = (char *)(farg1->data);
#ifdef HAVE_MPI
  arg2 = MPI_Comm_f2c((MPI_Fint)*farg2);
#else
  arg2 = *farg2;
#endif
  result = (WdmCplClient *)wdmcpl_create_client((char const *)arg1,arg2);
  fresult.cptr = (void*)result;
  fresult.cmemflags = SWIG_MEM_RVALUE | (0 ? SWIG_MEM_OWN : 0);
  return fresult;
}


SWIGEXPORT void _wrap_wdmcpl_destroy_client(SwigClassWrapper *farg1) {
  WdmCplClient *arg1 = (WdmCplClient *) 0 ;
  
  arg1 = (WdmCplClient *)farg1->cptr;
  wdmcpl_destroy_client(arg1);
}


SWIGEXPORT SwigClassWrapper _wrap_wdmcpl_load_reverse_classification(SwigArrayWrapper *farg1, int const *farg2) {
  SwigClassWrapper fresult ;
  char *arg1 = (char *) 0 ;
  MPI_Comm arg2 ;
  WdmCplReverseClassificationHandle *result = 0 ;
  
  arg1 = (char *)(farg1->data);
#ifdef HAVE_MPI
  arg2 = MPI_Comm_f2c((MPI_Fint)*farg2);
#else
  arg2 = *farg2;
#endif
  result = (WdmCplReverseClassificationHandle *)wdmcpl_load_reverse_classification((char const *)arg1,arg2);
  fresult.cptr = (void*)result;
  fresult.cmemflags = SWIG_MEM_RVALUE | (0 ? SWIG_MEM_OWN : 0);
  return fresult;
}


SWIGEXPORT void _wrap_wdmcpl_destroy_reverse_classification(SwigClassWrapper *farg1) {
  WdmCplReverseClassificationHandle *arg1 = (WdmCplReverseClassificationHandle *) 0 ;
  
  arg1 = (WdmCplReverseClassificationHandle *)farg1->cptr;
  wdmcpl_destroy_reverse_classification(arg1);
}


SWIGEXPORT int _wrap_wdmcpl_reverse_classification_count_verts(SwigClassWrapper *farg1) {
  int fresult ;
  WdmCplReverseClassificationHandle *arg1 = (WdmCplReverseClassificationHandle *) 0 ;
  int result;
  
  arg1 = (WdmCplReverseClassificationHandle *)farg1->cptr;
  result = (int)wdmcpl_reverse_classification_count_verts(arg1);
  fresult = (int)(result);
  return fresult;
}


SWIGEXPORT SwigClassWrapper _wrap_wdmcpl_create_xgc_field_adapter(SwigArrayWrapper *farg1, void const **farg2, int const *farg3, int const *farg4, SwigClassWrapper *farg5, in_overlap_function farg6) {
  SwigClassWrapper fresult ;
  char *arg1 = (char *) 0 ;
  void *arg2 = (void *) 0 ;
  int arg3 ;
  WdmCplType arg4 ;
  WdmCplReverseClassificationHandle *arg5 = (WdmCplReverseClassificationHandle *) 0 ;
  in_overlap_function arg6 = (in_overlap_function) 0 ;
  WdmCplFieldAdapter *result = 0 ;
  
  arg1 = (char *)(farg1->data);
  arg2 = (void *)(*farg2);
  arg3 = (int)(*farg3);
  arg4 = (WdmCplType)(*farg4);
  arg5 = (WdmCplReverseClassificationHandle *)farg5->cptr;
  arg6 = (in_overlap_function)(*farg6);
  result = (WdmCplFieldAdapter *)wdmcpl_create_xgc_field_adapter((char const *)arg1,arg2,arg3,arg4,(WdmCplReverseClassificationHandle const *)arg5,arg6);
  fresult.cptr = (void*)result;
  fresult.cmemflags = SWIG_MEM_RVALUE | (0 ? SWIG_MEM_OWN : 0);
  return fresult;
}


SWIGEXPORT void _wrap_wdmcpl_destroy_field_adapter(SwigClassWrapper *farg1) {
  WdmCplFieldAdapter *arg1 = (WdmCplFieldAdapter *) 0 ;
  
  arg1 = (WdmCplFieldAdapter *)farg1->cptr;
  wdmcpl_destroy_field_adapter(arg1);
}


SWIGEXPORT SwigClassWrapper _wrap_wdmcpl_add_field(SwigClassWrapper *farg1, SwigArrayWrapper *farg2, SwigClassWrapper *farg3) {
  SwigClassWrapper fresult ;
  WdmCplClient *arg1 = (WdmCplClient *) 0 ;
  char *arg2 = (char *) 0 ;
  WdmCplFieldAdapter *arg3 = (WdmCplFieldAdapter *) 0 ;
  WdmCplFieldHandle *result = 0 ;
  
  arg1 = (WdmCplClient *)farg1->cptr;
  arg2 = (char *)(farg2->data);
  arg3 = (WdmCplFieldAdapter *)farg3->cptr;
  result = (WdmCplFieldHandle *)wdmcpl_add_field(arg1,(char const *)arg2,arg3);
  fresult.cptr = (void*)result;
  fresult.cmemflags = SWIG_MEM_RVALUE | (0 ? SWIG_MEM_OWN : 0);
  return fresult;
}


SWIGEXPORT void _wrap_wdmcpl_send_field_name(SwigClassWrapper *farg1, SwigArrayWrapper *farg2) {
  WdmCplClient *arg1 = (WdmCplClient *) 0 ;
  char *arg2 = (char *) 0 ;
  
  arg1 = (WdmCplClient *)farg1->cptr;
  arg2 = (char *)(farg2->data);
  wdmcpl_send_field_name(arg1,(char const *)arg2);
}


SWIGEXPORT void _wrap_wdmcpl_receive_field_name(SwigClassWrapper *farg1, SwigArrayWrapper *farg2) {
  WdmCplClient *arg1 = (WdmCplClient *) 0 ;
  char *arg2 = (char *) 0 ;
  
  arg1 = (WdmCplClient *)farg1->cptr;
  arg2 = (char *)(farg2->data);
  wdmcpl_receive_field_name(arg1,(char const *)arg2);
}


SWIGEXPORT void _wrap_wdmcpl_send_field(SwigClassWrapper *farg1) {
  WdmCplFieldHandle *arg1 = (WdmCplFieldHandle *) 0 ;
  
  arg1 = (WdmCplFieldHandle *)farg1->cptr;
  wdmcpl_send_field(arg1);
}


SWIGEXPORT void _wrap_wdmcpl_receive_field(SwigClassWrapper *farg1) {
  WdmCplFieldHandle *arg1 = (WdmCplFieldHandle *) 0 ;
  
  arg1 = (WdmCplFieldHandle *)farg1->cptr;
  wdmcpl_receive_field(arg1);
}



