name: install-repo

inputs:
  repo-name:
    required: true
  repo-path:
    required: true
  repo-ref:
    required: true
  options:
    required: true

runs:
  using: "composite"
  steps:

  - name: Check Cache
    uses: actions/cache@v3
    id: build-kokkos
    with:
      key: build-${{inputs.repo-name}}
      path: ${{ runner.temp }}/build-${{inputs.repo-name}}
      
  - name: Checkout Repo
    if: ${{ !steps[format('build-{0}', inputs.repo-name)].outputs.cache-hit }}
    uses: actions/checkout@v3
    with:
      repository: ${{inputs.repo-path}}
      ref: ${{inputs.repo-ref}}
      path: ${{inputs.repo-name}}

  - name: Configure CMake
    shell: bash
    if: ${{ !steps[format('build-{0}', inputs.repo-name)].outputs.cache-hit }}
    run: cmake -S $GITHUB_WORKSPACE/${{inputs.repo-name}} -B ${{ runner.temp }}/build-${{inputs.repo-name}}
      -DCMAKE_INSTALL_PREFIX=${{ runner.temp }}/build-${{inputs.repo-name}}/install
      ${{inputs.options}}
  
  - name: Build Cmake
    shell: bash
    if: ${{ !steps[format('build-{0}', inputs.repo-name)].outputs.cache-hit }}
    run: cmake --build ${{ runner.temp }}/build-${{inputs.repo-name}} -j8 --target install