/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.1.1+fortran
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */
/* -----------------------------------------------------------------------------
 *  This section contains generic SWIG labels for method/variable
 *  declarations/attributes, and other compiler dependent labels.
 * ----------------------------------------------------------------------------- */

/* template workaround for compilers that cannot correctly implement the C++ standard */
#ifndef SWIGTEMPLATEDISAMBIGUATOR
# if defined(__SUNPRO_CC) && (__SUNPRO_CC <= 0x560)
#  define SWIGTEMPLATEDISAMBIGUATOR template
# elif defined(__HP_aCC)
/* Needed even with `aCC -AA' when `aCC -V' reports HP ANSI C++ B3910B A.03.55 */
/* If we find a maximum version that requires this, the test would be __HP_aCC <= 35500 for A.03.55 */
#  define SWIGTEMPLATEDISAMBIGUATOR template
# else
#  define SWIGTEMPLATEDISAMBIGUATOR
# endif
#endif

/* inline attribute */
#ifndef SWIGINLINE
# if defined(__cplusplus) || (defined(__GNUC__) && !defined(__STRICT_ANSI__))
#   define SWIGINLINE inline
# else
#   define SWIGINLINE
# endif
#endif

/* attribute recognised by some compilers to avoid 'unused' warnings */
#ifndef SWIGUNUSED
# if defined(__GNUC__)
#   if !(defined(__cplusplus)) || (__GNUC__ > 3 || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4))
#     define SWIGUNUSED __attribute__ ((__unused__))
#   else
#     define SWIGUNUSED
#   endif
# elif defined(__ICC)
#   define SWIGUNUSED __attribute__ ((__unused__))
# else
#   define SWIGUNUSED
# endif
#endif

#ifndef SWIG_MSC_UNSUPPRESS_4505
# if defined(_MSC_VER)
#   pragma warning(disable : 4505) /* unreferenced local function has been removed */
# endif
#endif

#ifndef SWIGUNUSEDPARM
# ifdef __cplusplus
#   define SWIGUNUSEDPARM(p)
# else
#   define SWIGUNUSEDPARM(p) p SWIGUNUSED
# endif
#endif

/* internal SWIG method */
#ifndef SWIGINTERN
# define SWIGINTERN static SWIGUNUSED
#endif

/* internal inline SWIG method */
#ifndef SWIGINTERNINLINE
# define SWIGINTERNINLINE SWIGINTERN SWIGINLINE
#endif

/* exporting methods */
#if defined(__GNUC__)
#  if (__GNUC__ >= 4) || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4)
#    ifndef GCC_HASCLASSVISIBILITY
#      define GCC_HASCLASSVISIBILITY
#    endif
#  endif
#endif

#ifndef SWIGEXPORT
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   if defined(STATIC_LINKED)
#     define SWIGEXPORT
#   else
#     define SWIGEXPORT __declspec(dllexport)
#   endif
# else
#   if defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
#     define SWIGEXPORT __attribute__ ((visibility("default")))
#   else
#     define SWIGEXPORT
#   endif
# endif
#endif

/* calling conventions for Windows */
#ifndef SWIGSTDCALL
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   define SWIGSTDCALL __stdcall
# else
#   define SWIGSTDCALL
# endif
#endif

/* Deal with Microsoft's attempt at deprecating C standard runtime functions */
#if !defined(SWIG_NO_CRT_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_CRT_SECURE_NO_DEPRECATE)
# define _CRT_SECURE_NO_DEPRECATE
#endif

/* Deal with Microsoft's attempt at deprecating methods in the standard C++ library */
#if !defined(SWIG_NO_SCL_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_SCL_SECURE_NO_DEPRECATE)
# define _SCL_SECURE_NO_DEPRECATE
#endif

/* Deal with Apple's deprecated 'AssertMacros.h' from Carbon-framework */
#if defined(__APPLE__) && !defined(__ASSERT_MACROS_DEFINE_VERSIONS_WITHOUT_UNDERSCORES)
# define __ASSERT_MACROS_DEFINE_VERSIONS_WITHOUT_UNDERSCORES 0
#endif

/* Intel's compiler complains if a variable which was never initialised is
 * cast to void, which is a common idiom which we use to indicate that we
 * are aware a variable isn't used.  So we just silence that warning.
 * See: https://github.com/swig/swig/issues/192 for more discussion.
 */
#ifdef __INTEL_COMPILER
# pragma warning disable 592
#endif


#ifndef SWIGEXTERN
# ifdef __cplusplus
#   define SWIGEXTERN extern
# else
#   define SWIGEXTERN
# endif
#endif


#include <assert.h>
#define SWIG_exception_impl(DECL, CODE, MSG, RETURNNULL) \
 { printf("In " DECL ": " MSG); assert(0); RETURNNULL; }


enum {
    SWIG_MEM_OWN = 0x01,
    SWIG_MEM_RVALUE = 0x02,
};



#define SWIG_VERSION 0x040101
#define SWIGFORTRAN

#include <stdio.h>
#if (defined(_MSC_VER) && (_MSC_VER < 1900)) || defined(__BORLANDC__) || defined(_WATCOM)
# ifndef snprintf
#  define snprintf _snprintf
# endif
#endif


/* Support for the `contract` feature.
 *
 * Note that RETURNNULL is first because it's inserted via a 'Replaceall' in
 * the fortran.cxx file.
 */
#define SWIG_contract_assert(RETURNNULL, EXPR, MSG) \
 if (!(EXPR)) { SWIG_exception_impl("$decl", SWIG_ValueError, MSG, RETURNNULL); } 


#define SWIG_as_voidptr(a) (void *)((const void *)(a)) 
#define SWIG_as_voidptrptr(a) ((void)SWIG_as_voidptr(*a),(void**)(a)) 


#include "pcms/capi/client.h"
#include "pcms/capi/kokkos.h"


#ifdef HAVE_MPI
#include <mpi.h>
#endif


#include <stdint.h>


typedef struct {
    void* cptr;
    int cmemflags;
} SwigClassWrapper;


SWIGINTERN SwigClassWrapper SwigClassWrapper_uninitialized() {
    SwigClassWrapper result;
    result.cptr = NULL;
    result.cmemflags = 0;
    return result;
}


#include <stdlib.h>
#ifdef _MSC_VER
# ifndef strtoull
#  define strtoull _strtoui64
# endif
# ifndef strtoll
#  define strtoll _strtoi64
# endif
#endif


typedef struct {
    void* data;
    size_t size;
} SwigArrayWrapper;


SWIGINTERN SwigArrayWrapper SwigArrayWrapper_uninitialized() {
  SwigArrayWrapper result;
  result.data = NULL;
  result.size = 0;
  return result;
}

SWIGEXPORT SwigClassWrapper _wrap_pcms_create_client(SwigArrayWrapper *farg1, int const *farg2) {
  SwigClassWrapper fresult ;
  char *arg1 = (char *) 0 ;
  MPI_Comm arg2 ;
  WdmCplClientHandle *result = 0 ;
  
  arg1 = (char *)(farg1->data);
#ifdef HAVE_MPI
  arg2 = MPI_Comm_f2c((MPI_Fint)*farg2);
#else
  arg2 = *farg2;
#endif
  result = (WdmCplClientHandle *)pcms_create_client((char const *)arg1,arg2);
  fresult.cptr = (void*)result;
  fresult.cmemflags = SWIG_MEM_RVALUE | (0 ? SWIG_MEM_OWN : 0);
  return fresult;
}


SWIGEXPORT void _wrap_pcms_destroy_client(SwigClassWrapper *farg1) {
  WdmCplClientHandle *arg1 = (WdmCplClientHandle *) 0 ;
  
  arg1 = (WdmCplClientHandle *)farg1->cptr;
  pcms_destroy_client(arg1);
}


SWIGEXPORT SwigClassWrapper _wrap_pcms_load_reverse_classification(SwigArrayWrapper *farg1, int const *farg2) {
  SwigClassWrapper fresult ;
  char *arg1 = (char *) 0 ;
  MPI_Comm arg2 ;
  WdmCplReverseClassificationHandle *result = 0 ;
  
  arg1 = (char *)(farg1->data);
#ifdef HAVE_MPI
  arg2 = MPI_Comm_f2c((MPI_Fint)*farg2);
#else
  arg2 = *farg2;
#endif
  result = (WdmCplReverseClassificationHandle *)pcms_load_reverse_classification((char const *)arg1,arg2);
  fresult.cptr = (void*)result;
  fresult.cmemflags = SWIG_MEM_RVALUE | (0 ? SWIG_MEM_OWN : 0);
  return fresult;
}


SWIGEXPORT void _wrap_pcms_destroy_reverse_classification(SwigClassWrapper *farg1) {
  WdmCplReverseClassificationHandle *arg1 = (WdmCplReverseClassificationHandle *) 0 ;
  
  arg1 = (WdmCplReverseClassificationHandle *)farg1->cptr;
  pcms_destroy_reverse_classification(arg1);
}


SWIGEXPORT int _wrap_pcms_reverse_classification_count_verts(SwigClassWrapper *farg1) {
  int fresult ;
  WdmCplReverseClassificationHandle *arg1 = (WdmCplReverseClassificationHandle *) 0 ;
  int result;
  
  arg1 = (WdmCplReverseClassificationHandle *)farg1->cptr;
  result = (int)pcms_reverse_classification_count_verts(arg1);
  fresult = (int)(result);
  return fresult;
}


SWIGEXPORT SwigClassWrapper _wrap_pcms_create_xgc_field_adapter(SwigArrayWrapper *farg1, int const *farg2, void const **farg3, int const *farg4, int const *farg5, SwigClassWrapper *farg6, in_overlap_function farg7) {
  SwigClassWrapper fresult ;
  char *arg1 = (char *) 0 ;
  MPI_Comm arg2 ;
  void *arg3 = (void *) 0 ;
  int arg4 ;
  WdmCplType arg5 ;
  WdmCplReverseClassificationHandle *arg6 = (WdmCplReverseClassificationHandle *) 0 ;
  in_overlap_function arg7 = (in_overlap_function) 0 ;
  WdmCplFieldAdapterHandle *result = 0 ;
  
  arg1 = (char *)(farg1->data);
#ifdef HAVE_MPI
  arg2 = MPI_Comm_f2c((MPI_Fint)*farg2);
#else
  arg2 = *farg2;
#endif
  arg3 = (void *)(*farg3);
  arg4 = (int)(*farg4);
  arg5 = (WdmCplType)(*farg5);
  arg6 = (WdmCplReverseClassificationHandle *)farg6->cptr;
  arg7 = (in_overlap_function)(*farg7);
  result = (WdmCplFieldAdapterHandle *)pcms_create_xgc_field_adapter((char const *)arg1,arg2,arg3,arg4,arg5,(WdmCplReverseClassificationHandle const *)arg6,arg7);
  fresult.cptr = (void*)result;
  fresult.cmemflags = SWIG_MEM_RVALUE | (0 ? SWIG_MEM_OWN : 0);
  return fresult;
}


SWIGEXPORT SwigClassWrapper _wrap_pcms_create_dummy_field_adapter() {
  SwigClassWrapper fresult ;
  WdmCplFieldAdapterHandle *result = 0 ;
  
  result = (WdmCplFieldAdapterHandle *)pcms_create_dummy_field_adapter();
  fresult.cptr = (void*)result;
  fresult.cmemflags = SWIG_MEM_RVALUE | (0 ? SWIG_MEM_OWN : 0);
  return fresult;
}


SWIGEXPORT void _wrap_pcms_destroy_field_adapter(SwigClassWrapper *farg1) {
  WdmCplFieldAdapterHandle *arg1 = (WdmCplFieldAdapterHandle *) 0 ;
  
  arg1 = (WdmCplFieldAdapterHandle *)farg1->cptr;
  pcms_destroy_field_adapter(arg1);
}


SWIGEXPORT SwigClassWrapper _wrap_pcms_add_field(SwigClassWrapper *farg1, SwigArrayWrapper *farg2, SwigClassWrapper *farg3, int const *farg4) {
  SwigClassWrapper fresult ;
  WdmCplClientHandle *arg1 = (WdmCplClientHandle *) 0 ;
  char *arg2 = (char *) 0 ;
  WdmCplFieldAdapterHandle *arg3 = (WdmCplFieldAdapterHandle *) 0 ;
  int arg4 ;
  WdmCplFieldHandle *result = 0 ;
  
  arg1 = (WdmCplClientHandle *)farg1->cptr;
  arg2 = (char *)(farg2->data);
  arg3 = (WdmCplFieldAdapterHandle *)farg3->cptr;
  arg4 = (int)(*farg4);
  result = (WdmCplFieldHandle *)pcms_add_field(arg1,(char const *)arg2,arg3,arg4);
  fresult.cptr = (void*)result;
  fresult.cmemflags = SWIG_MEM_RVALUE | (0 ? SWIG_MEM_OWN : 0);
  return fresult;
}


SWIGEXPORT void _wrap_pcms_send_field_name(SwigClassWrapper *farg1, SwigArrayWrapper *farg2) {
  WdmCplClientHandle *arg1 = (WdmCplClientHandle *) 0 ;
  char *arg2 = (char *) 0 ;
  
  arg1 = (WdmCplClientHandle *)farg1->cptr;
  arg2 = (char *)(farg2->data);
  pcms_send_field_name(arg1,(char const *)arg2);
}


SWIGEXPORT void _wrap_pcms_receive_field_name(SwigClassWrapper *farg1, SwigArrayWrapper *farg2) {
  WdmCplClientHandle *arg1 = (WdmCplClientHandle *) 0 ;
  char *arg2 = (char *) 0 ;
  
  arg1 = (WdmCplClientHandle *)farg1->cptr;
  arg2 = (char *)(farg2->data);
  pcms_receive_field_name(arg1,(char const *)arg2);
}


SWIGEXPORT void _wrap_pcms_send_field(SwigClassWrapper *farg1) {
  WdmCplFieldHandle *arg1 = (WdmCplFieldHandle *) 0 ;
  
  arg1 = (WdmCplFieldHandle *)farg1->cptr;
  pcms_send_field(arg1);
}


SWIGEXPORT void _wrap_pcms_receive_field(SwigClassWrapper *farg1) {
  WdmCplFieldHandle *arg1 = (WdmCplFieldHandle *) 0 ;
  
  arg1 = (WdmCplFieldHandle *)farg1->cptr;
  pcms_receive_field(arg1);
}


SWIGEXPORT void _wrap_pcms_begin_send_phase(SwigClassWrapper *farg1) {
  WdmCplClientHandle *arg1 = (WdmCplClientHandle *) 0 ;
  
  arg1 = (WdmCplClientHandle *)farg1->cptr;
  pcms_begin_send_phase(arg1);
}


SWIGEXPORT void _wrap_pcms_end_send_phase(SwigClassWrapper *farg1) {
  WdmCplClientHandle *arg1 = (WdmCplClientHandle *) 0 ;
  
  arg1 = (WdmCplClientHandle *)farg1->cptr;
  pcms_end_send_phase(arg1);
}


SWIGEXPORT void _wrap_pcms_begin_receive_phase(SwigClassWrapper *farg1) {
  WdmCplClientHandle *arg1 = (WdmCplClientHandle *) 0 ;
  
  arg1 = (WdmCplClientHandle *)farg1->cptr;
  pcms_begin_receive_phase(arg1);
}


SWIGEXPORT void _wrap_pcms_end_receive_phase(SwigClassWrapper *farg1) {
  WdmCplClientHandle *arg1 = (WdmCplClientHandle *) 0 ;
  
  arg1 = (WdmCplClientHandle *)farg1->cptr;
  pcms_end_receive_phase(arg1);
}


SWIGEXPORT void _wrap_pcms_kokkos_initialize_without_args() {
  pcms_kokkos_initialize_without_args();
}


SWIGEXPORT void _wrap_pcms_kokkos_finalize() {
  pcms_kokkos_finalize();
}



