/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.1.1+fortran
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */
/* -----------------------------------------------------------------------------
 *  This section contains generic SWIG labels for method/variable
 *  declarations/attributes, and other compiler dependent labels.
 * ----------------------------------------------------------------------------- */

/* template workaround for compilers that cannot correctly implement the C++ standard */
#ifndef SWIGTEMPLATEDISAMBIGUATOR
# if defined(__SUNPRO_CC) && (__SUNPRO_CC <= 0x560)
#  define SWIGTEMPLATEDISAMBIGUATOR template
# elif defined(__HP_aCC)
/* Needed even with `aCC -AA' when `aCC -V' reports HP ANSI C++ B3910B A.03.55 */
/* If we find a maximum version that requires this, the test would be __HP_aCC <= 35500 for A.03.55 */
#  define SWIGTEMPLATEDISAMBIGUATOR template
# else
#  define SWIGTEMPLATEDISAMBIGUATOR
# endif
#endif

/* inline attribute */
#ifndef SWIGINLINE
# if defined(__cplusplus) || (defined(__GNUC__) && !defined(__STRICT_ANSI__))
#   define SWIGINLINE inline
# else
#   define SWIGINLINE
# endif
#endif

/* attribute recognised by some compilers to avoid 'unused' warnings */
#ifndef SWIGUNUSED
# if defined(__GNUC__)
#   if !(defined(__cplusplus)) || (__GNUC__ > 3 || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4))
#     define SWIGUNUSED __attribute__ ((__unused__))
#   else
#     define SWIGUNUSED
#   endif
# elif defined(__ICC)
#   define SWIGUNUSED __attribute__ ((__unused__))
# else
#   define SWIGUNUSED
# endif
#endif

#ifndef SWIG_MSC_UNSUPPRESS_4505
# if defined(_MSC_VER)
#   pragma warning(disable : 4505) /* unreferenced local function has been removed */
# endif
#endif

#ifndef SWIGUNUSEDPARM
# ifdef __cplusplus
#   define SWIGUNUSEDPARM(p)
# else
#   define SWIGUNUSEDPARM(p) p SWIGUNUSED
# endif
#endif

/* internal SWIG method */
#ifndef SWIGINTERN
# define SWIGINTERN static SWIGUNUSED
#endif

/* internal inline SWIG method */
#ifndef SWIGINTERNINLINE
# define SWIGINTERNINLINE SWIGINTERN SWIGINLINE
#endif

/* exporting methods */
#if defined(__GNUC__)
#  if (__GNUC__ >= 4) || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4)
#    ifndef GCC_HASCLASSVISIBILITY
#      define GCC_HASCLASSVISIBILITY
#    endif
#  endif
#endif

#ifndef SWIGEXPORT
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   if defined(STATIC_LINKED)
#     define SWIGEXPORT
#   else
#     define SWIGEXPORT __declspec(dllexport)
#   endif
# else
#   if defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
#     define SWIGEXPORT __attribute__ ((visibility("default")))
#   else
#     define SWIGEXPORT
#   endif
# endif
#endif

/* calling conventions for Windows */
#ifndef SWIGSTDCALL
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   define SWIGSTDCALL __stdcall
# else
#   define SWIGSTDCALL
# endif
#endif

/* Deal with Microsoft's attempt at deprecating C standard runtime functions */
#if !defined(SWIG_NO_CRT_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_CRT_SECURE_NO_DEPRECATE)
# define _CRT_SECURE_NO_DEPRECATE
#endif

/* Deal with Microsoft's attempt at deprecating methods in the standard C++ library */
#if !defined(SWIG_NO_SCL_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_SCL_SECURE_NO_DEPRECATE)
# define _SCL_SECURE_NO_DEPRECATE
#endif

/* Deal with Apple's deprecated 'AssertMacros.h' from Carbon-framework */
#if defined(__APPLE__) && !defined(__ASSERT_MACROS_DEFINE_VERSIONS_WITHOUT_UNDERSCORES)
# define __ASSERT_MACROS_DEFINE_VERSIONS_WITHOUT_UNDERSCORES 0
#endif

/* Intel's compiler complains if a variable which was never initialised is
 * cast to void, which is a common idiom which we use to indicate that we
 * are aware a variable isn't used.  So we just silence that warning.
 * See: https://github.com/swig/swig/issues/192 for more discussion.
 */
#ifdef __INTEL_COMPILER
# pragma warning disable 592
#endif


#ifndef SWIGEXTERN
# ifdef __cplusplus
#   define SWIGEXTERN extern
# else
#   define SWIGEXTERN
# endif
#endif


#include <assert.h>
#define SWIG_exception_impl(DECL, CODE, MSG, RETURNNULL) \
 { printf("In " DECL ": " MSG); assert(0); RETURNNULL; }


enum {
    SWIG_MEM_OWN = 0x01,
    SWIG_MEM_RVALUE = 0x02,
};

#define SWIG_check_nonnull(PTR, TYPENAME, FNAME, FUNCNAME, RETURNNULL)         \
  if (!(PTR)) {                                                                \
    SWIG_exception_impl(FUNCNAME, SWIG_NullReferenceError,                     \
                        "Cannot pass null " TYPENAME " (class " FNAME ") "     \
                        "as a reference",                                      \
                        RETURNNULL);                                           \
  }

#define SWIG_VERSION 0x040101
#define SWIGFORTRAN

#include <stdio.h>
#if (defined(_MSC_VER) && (_MSC_VER < 1900)) || defined(__BORLANDC__) || defined(_WATCOM)
# ifndef snprintf
#  define snprintf _snprintf
# endif
#endif


/* Support for the `contract` feature.
 *
 * Note that RETURNNULL is first because it's inserted via a 'Replaceall' in
 * the fortran.cxx file.
 */
#define SWIG_contract_assert(RETURNNULL, EXPR, MSG) \
 if (!(EXPR)) { SWIG_exception_impl("$decl", SWIG_ValueError, MSG, RETURNNULL); } 


#define SWIG_as_voidptr(a) (void *)((const void *)(a)) 
#define SWIG_as_voidptrptr(a) ((void)SWIG_as_voidptr(*a),(void**)(a)) 


#include "pcms/capi/client.h"
#include "pcms/capi/kokkos.h"


#ifdef HAVE_MPI
#include <mpi.h>
#endif


#include <stdint.h>


typedef struct {
    void* cptr;
    int cmemflags;
} SwigClassWrapper;


SWIGINTERN SwigClassWrapper SwigClassWrapper_uninitialized() {
    SwigClassWrapper result;
    result.cptr = NULL;
    result.cmemflags = 0;
    return result;
}


#include <stdlib.h>
#ifdef _MSC_VER
# ifndef strtoull
#  define strtoull _strtoui64
# endif
# ifndef strtoll
#  define strtoll _strtoi64
# endif
#endif

#include <string.h>

SWIGINTERN void SWIG_assign(SwigClassWrapper* self, SwigClassWrapper other)
{
    if (self->cptr == NULL) {
      /* LHS is unassigned */
      if (other.cmemflags & SWIG_MEM_RVALUE) {
        /* Capture pointer from RHS, clear 'moving' flag */
        self->cptr = other.cptr;
        self->cmemflags = other.cmemflags & (~SWIG_MEM_RVALUE);
      } else {
        /* Become a reference to the other object */
        self->cptr = other.cptr;
        self->cmemflags = other.cmemflags & (~SWIG_MEM_OWN);
      }
    } else if (other.cptr == NULL) {
      /* Replace LHS with a null pointer */
      free(self->cptr);
      *self = SwigClassWrapper_uninitialized();
    } else if (self->cptr == other.cptr) {
      /* Self-assignment: ignore */
    } else {
      if (self->cmemflags & SWIG_MEM_OWN) {
        free(self->cptr);
      }
      self->cptr = other.cptr;
      if (other.cmemflags & SWIG_MEM_RVALUE) {
        /* Capture RHS */
        self->cmemflags = other.cmemflags & ~SWIG_MEM_RVALUE;
      } else {
        /* Point to RHS */
        self->cmemflags = other.cmemflags & ~SWIG_MEM_OWN;
      }
    }
}

typedef struct {
    void* data;
    size_t size;
} SwigArrayWrapper;


SWIGINTERN SwigArrayWrapper SwigArrayWrapper_uninitialized() {
  SwigArrayWrapper result;
  result.data = NULL;
  result.size = 0;
  return result;
}

SWIGEXPORT void _wrap_PcmsClientHandle_pointer_set(SwigClassWrapper* farg1,
                                                   void const** farg2)
{
  struct PcmsClientHandle* arg1 = (struct PcmsClientHandle*)0;
  void* arg2 = (void*)0;

  SWIG_check_nonnull(farg1->cptr, "struct PcmsClientHandle *",
                     "PcmsClientHandle", "PcmsClientHandle::pointer", return);
  arg1 = (struct PcmsClientHandle*)farg1->cptr;
  arg2 = (void*)(*farg2);
  if (arg1)
      (arg1)->appPointer = arg2;
}

SWIGEXPORT void* _wrap_PcmsClientHandle_pointer_get(SwigClassWrapper* farg1)
{
  void* fresult;
  struct PcmsClientHandle* arg1 = (struct PcmsClientHandle*)0;
  void* result = 0;

  SWIG_check_nonnull(farg1->cptr, "struct PcmsClientHandle *",
                     "PcmsClientHandle", "PcmsClientHandle::pointer", return 0);
  arg1 = (struct PcmsClientHandle*)farg1->cptr;
  result = (void*)((arg1)->appPointer);
  fresult = (void*)(result);
  return fresult;
}

SWIGEXPORT SwigClassWrapper _wrap_new_PcmsClientHandle()
{
  SwigClassWrapper fresult;
  struct PcmsClientHandle* result = 0;

  result = (struct PcmsClientHandle*)calloc(1, sizeof(struct PcmsClientHandle));
  fresult.cptr = (void*)result;
  fresult.cmemflags = SWIG_MEM_RVALUE | (1 ? SWIG_MEM_OWN : 0);
  return fresult;
}

SWIGEXPORT void _wrap_delete_PcmsClientHandle(SwigClassWrapper* farg1)
{
  struct PcmsClientHandle* arg1 = (struct PcmsClientHandle*)0;

  arg1 = (struct PcmsClientHandle*)farg1->cptr;
  free((char*)arg1);
}

SWIGEXPORT void _wrap_PcmsClientHandle_op_assign__(SwigClassWrapper* farg1,
                                                   SwigClassWrapper* farg2)
{
  struct PcmsClientHandle* arg1 = (struct PcmsClientHandle*)0;
  struct PcmsClientHandle* arg2 = 0;

  (void)sizeof(arg1);
  (void)sizeof(arg2);
  SWIG_assign(farg1, *farg2);
}

SWIGEXPORT void _wrap_PcmsOmegaHMeshHandle_pointer_set(SwigClassWrapper* farg1,
                                                       void const** farg2)
{
  struct PcmsOmegaHMeshHandle* arg1 = (struct PcmsOmegaHMeshHandle*)0;
  void* arg2 = (void*)0;

  SWIG_check_nonnull(farg1->cptr, "struct PcmsOmegaHMeshHandle *",
                     "PcmsOmegaHMeshHandle", "PcmsOmegaHMeshHandle::pointer",
                     return);
  arg1 = (struct PcmsOmegaHMeshHandle*)farg1->cptr;
  arg2 = (void*)(*farg2);
  if (arg1)
      (arg1)->pointer = arg2;
}

SWIGEXPORT void* _wrap_PcmsOmegaHMeshHandle_pointer_get(SwigClassWrapper* farg1)
{
  void* fresult;
  struct PcmsOmegaHMeshHandle* arg1 = (struct PcmsOmegaHMeshHandle*)0;
  void* result = 0;

  SWIG_check_nonnull(farg1->cptr, "struct PcmsOmegaHMeshHandle *",
                     "PcmsOmegaHMeshHandle", "PcmsOmegaHMeshHandle::pointer",
                     return 0);
  arg1 = (struct PcmsOmegaHMeshHandle*)farg1->cptr;
  result = (void*)((arg1)->pointer);
  fresult = (void*)(result);
  return fresult;
}

SWIGEXPORT SwigClassWrapper _wrap_new_PcmsOmegaHMeshHandle()
{
  SwigClassWrapper fresult;
  struct PcmsOmegaHMeshHandle* result = 0;

  result = (struct PcmsOmegaHMeshHandle*)calloc(
    1, sizeof(struct PcmsOmegaHMeshHandle));
  fresult.cptr = (void*)result;
  fresult.cmemflags = SWIG_MEM_RVALUE | (1 ? SWIG_MEM_OWN : 0);
  return fresult;
}

SWIGEXPORT void _wrap_delete_PcmsOmegaHMeshHandle(SwigClassWrapper* farg1)
{
  struct PcmsOmegaHMeshHandle* arg1 = (struct PcmsOmegaHMeshHandle*)0;

  arg1 = (struct PcmsOmegaHMeshHandle*)farg1->cptr;
  free((char*)arg1);
}

SWIGEXPORT void _wrap_PcmsOmegaHMeshHandle_op_assign__(SwigClassWrapper* farg1,
                                                       SwigClassWrapper* farg2)
{
  struct PcmsOmegaHMeshHandle* arg1 = (struct PcmsOmegaHMeshHandle*)0;
  struct PcmsOmegaHMeshHandle* arg2 = 0;

  (void)sizeof(arg1);
  (void)sizeof(arg2);
  SWIG_assign(farg1, *farg2);
}

SWIGEXPORT void _wrap_PcmsReverseClassificationHandle_pointer_set(
  SwigClassWrapper* farg1, void const** farg2)
{
  struct PcmsReverseClassificationHandle* arg1 =
    (struct PcmsReverseClassificationHandle*)0;
  void* arg2 = (void*)0;

  SWIG_check_nonnull(farg1->cptr, "struct PcmsReverseClassificationHandle *",
                     "PcmsReverseClassificationHandle",
                     "PcmsReverseClassificationHandle::pointer", return);
  arg1 = (struct PcmsReverseClassificationHandle*)farg1->cptr;
  arg2 = (void*)(*farg2);
  if (arg1)
      (arg1)->pointer = arg2;
}

SWIGEXPORT void* _wrap_PcmsReverseClassificationHandle_pointer_get(
  SwigClassWrapper* farg1)
{
  void* fresult;
  struct PcmsReverseClassificationHandle* arg1 =
    (struct PcmsReverseClassificationHandle*)0;
  void* result = 0;

  SWIG_check_nonnull(farg1->cptr, "struct PcmsReverseClassificationHandle *",
                     "PcmsReverseClassificationHandle",
                     "PcmsReverseClassificationHandle::pointer", return 0);
  arg1 = (struct PcmsReverseClassificationHandle*)farg1->cptr;
  result = (void*)((arg1)->pointer);
  fresult = (void*)(result);
  return fresult;
}

SWIGEXPORT SwigClassWrapper _wrap_new_PcmsReverseClassificationHandle()
{
  SwigClassWrapper fresult;
  struct PcmsReverseClassificationHandle* result = 0;

  result = (struct PcmsReverseClassificationHandle*)calloc(
    1, sizeof(struct PcmsReverseClassificationHandle));
  fresult.cptr = (void*)result;
  fresult.cmemflags = SWIG_MEM_RVALUE | (1 ? SWIG_MEM_OWN : 0);
  return fresult;
}

SWIGEXPORT void _wrap_delete_PcmsReverseClassificationHandle(
  SwigClassWrapper* farg1)
{
  struct PcmsReverseClassificationHandle* arg1 =
    (struct PcmsReverseClassificationHandle*)0;

  arg1 = (struct PcmsReverseClassificationHandle*)farg1->cptr;
  free((char*)arg1);
}

SWIGEXPORT void _wrap_PcmsReverseClassificationHandle_op_assign__(
  SwigClassWrapper* farg1, SwigClassWrapper* farg2)
{
  struct PcmsReverseClassificationHandle* arg1 =
    (struct PcmsReverseClassificationHandle*)0;
  struct PcmsReverseClassificationHandle* arg2 = 0;

  (void)sizeof(arg1);
  (void)sizeof(arg2);
  SWIG_assign(farg1, *farg2);
}

SWIGEXPORT void _wrap_PcmsFieldAdapterHandle_pointer_set(
  SwigClassWrapper* farg1, void const** farg2)
{
  struct PcmsFieldAdapterHandle* arg1 = (struct PcmsFieldAdapterHandle*)0;
  void* arg2 = (void*)0;

  SWIG_check_nonnull(farg1->cptr, "struct PcmsFieldAdapterHandle *",
                     "PcmsFieldAdapterHandle",
                     "PcmsFieldAdapterHandle::pointer", return);
  arg1 = (struct PcmsFieldAdapterHandle*)farg1->cptr;
  arg2 = (void*)(*farg2);
  if (arg1)
      (arg1)->pointer = arg2;
}

SWIGEXPORT void* _wrap_PcmsFieldAdapterHandle_pointer_get(
  SwigClassWrapper* farg1)
{
  void* fresult;
  struct PcmsFieldAdapterHandle* arg1 = (struct PcmsFieldAdapterHandle*)0;
  void* result = 0;

  SWIG_check_nonnull(farg1->cptr, "struct PcmsFieldAdapterHandle *",
                     "PcmsFieldAdapterHandle",
                     "PcmsFieldAdapterHandle::pointer", return 0);
  arg1 = (struct PcmsFieldAdapterHandle*)farg1->cptr;
  result = (void*)((arg1)->pointer);
  fresult = (void*)(result);
  return fresult;
}

SWIGEXPORT SwigClassWrapper _wrap_new_PcmsFieldAdapterHandle()
{
  SwigClassWrapper fresult;
  struct PcmsFieldAdapterHandle* result = 0;

  result = (struct PcmsFieldAdapterHandle*)calloc(
    1, sizeof(struct PcmsFieldAdapterHandle));
  fresult.cptr = (void*)result;
  fresult.cmemflags = SWIG_MEM_RVALUE | (1 ? SWIG_MEM_OWN : 0);
  return fresult;
}

SWIGEXPORT void _wrap_delete_PcmsFieldAdapterHandle(SwigClassWrapper* farg1)
{
  struct PcmsFieldAdapterHandle* arg1 = (struct PcmsFieldAdapterHandle*)0;

  arg1 = (struct PcmsFieldAdapterHandle*)farg1->cptr;
  free((char*)arg1);
}

SWIGEXPORT void _wrap_PcmsFieldAdapterHandle_op_assign__(
  SwigClassWrapper* farg1, SwigClassWrapper* farg2)
{
  struct PcmsFieldAdapterHandle* arg1 = (struct PcmsFieldAdapterHandle*)0;
  struct PcmsFieldAdapterHandle* arg2 = 0;

  (void)sizeof(arg1);
  (void)sizeof(arg2);
  SWIG_assign(farg1, *farg2);
}

SWIGEXPORT void _wrap_PcmsFieldHandle_pointer_set(SwigClassWrapper* farg1,
                                                  void const** farg2)
{
  struct PcmsFieldHandle* arg1 = (struct PcmsFieldHandle*)0;
  void* arg2 = (void*)0;

  SWIG_check_nonnull(farg1->cptr, "struct PcmsFieldHandle *", "PcmsFieldHandle",
                     "PcmsFieldHandle::pointer", return);
  arg1 = (struct PcmsFieldHandle*)farg1->cptr;
  arg2 = (void*)(*farg2);
  if (arg1)
      (arg1)->pointer = arg2;
}

SWIGEXPORT void* _wrap_PcmsFieldHandle_pointer_get(SwigClassWrapper* farg1)
{
  void* fresult;
  struct PcmsFieldHandle* arg1 = (struct PcmsFieldHandle*)0;
  void* result = 0;

  SWIG_check_nonnull(farg1->cptr, "struct PcmsFieldHandle *", "PcmsFieldHandle",
                     "PcmsFieldHandle::pointer", return 0);
  arg1 = (struct PcmsFieldHandle*)farg1->cptr;
  result = (void*)((arg1)->pointer);
  fresult = (void*)(result);
  return fresult;
}

SWIGEXPORT SwigClassWrapper _wrap_new_PcmsFieldHandle()
{
  SwigClassWrapper fresult;
  struct PcmsFieldHandle* result = 0;

  result = (struct PcmsFieldHandle*)calloc(1, sizeof(struct PcmsFieldHandle));
  fresult.cptr = (void*)result;
  fresult.cmemflags = SWIG_MEM_RVALUE | (1 ? SWIG_MEM_OWN : 0);
  return fresult;
}

SWIGEXPORT void _wrap_delete_PcmsFieldHandle(SwigClassWrapper* farg1)
{
  struct PcmsFieldHandle* arg1 = (struct PcmsFieldHandle*)0;

  arg1 = (struct PcmsFieldHandle*)farg1->cptr;
  free((char*)arg1);
}

SWIGEXPORT void _wrap_PcmsFieldHandle_op_assign__(SwigClassWrapper* farg1,
                                                  SwigClassWrapper* farg2)
{
  struct PcmsFieldHandle* arg1 = (struct PcmsFieldHandle*)0;
  struct PcmsFieldHandle* arg2 = 0;

  (void)sizeof(arg1);
  (void)sizeof(arg2);
  SWIG_assign(farg1, *farg2);
}

SWIGEXPORT SwigClassWrapper _wrap_pcms_create_client(SwigArrayWrapper *farg1, int const *farg2) {
  SwigClassWrapper fresult ;
  char *arg1 = (char *) 0 ;
  MPI_Comm arg2 ;
  PcmsClientHandle result;

  arg1 = (char *)(farg1->data);
#ifdef HAVE_MPI
  arg2 = MPI_Comm_f2c((MPI_Fint)*farg2);
#else
  arg2 = *farg2;
#endif
  result = pcms_create_client((char const*)arg1, arg2);
  fresult.cptr = (PcmsClientHandle*)memcpy(
    (PcmsClientHandle*)calloc(1, sizeof(PcmsClientHandle)), &result,
    sizeof(PcmsClientHandle));
  fresult.cmemflags = SWIG_MEM_RVALUE | SWIG_MEM_OWN;
  return fresult;
}


SWIGEXPORT void _wrap_pcms_destroy_client(SwigClassWrapper *farg1) {
  PcmsClientHandle arg1;

  SWIG_check_nonnull(farg1->cptr, "PcmsClientHandle", "PcmsClientHandle",
                     "pcms_destroy_client(PcmsClientHandle)", return);
  arg1 = *((PcmsClientHandle*)(farg1->cptr));
  pcms_destroy_client(arg1);
}


SWIGEXPORT SwigClassWrapper _wrap_pcms_load_reverse_classification(SwigArrayWrapper *farg1, int const *farg2) {
  SwigClassWrapper fresult ;
  char *arg1 = (char *) 0 ;
  MPI_Comm arg2 ;
  PcmsReverseClassificationHandle result;

  arg1 = (char *)(farg1->data);
#ifdef HAVE_MPI
  arg2 = MPI_Comm_f2c((MPI_Fint)*farg2);
#else
  arg2 = *farg2;
#endif
  result = pcms_load_reverse_classification((char const*)arg1, arg2);
  fresult.cptr = (PcmsReverseClassificationHandle*)memcpy(
    (PcmsReverseClassificationHandle*)calloc(
      1, sizeof(PcmsReverseClassificationHandle)),
    &result, sizeof(PcmsReverseClassificationHandle));
  fresult.cmemflags = SWIG_MEM_RVALUE | SWIG_MEM_OWN;
  return fresult;
}


SWIGEXPORT void _wrap_pcms_destroy_reverse_classification(SwigClassWrapper *farg1) {
  PcmsReverseClassificationHandle arg1;

  SWIG_check_nonnull(
    farg1->cptr, "PcmsReverseClassificationHandle",
    "PcmsReverseClassificationHandle",
    "pcms_destroy_reverse_classification(PcmsReverseClassificationHandle)",
    return);
  arg1 = *((PcmsReverseClassificationHandle*)(farg1->cptr));
  pcms_destroy_reverse_classification(arg1);
}


SWIGEXPORT int _wrap_pcms_reverse_classification_count_verts(SwigClassWrapper *farg1) {
  int fresult ;
  PcmsReverseClassificationHandle arg1;
  int result;

  SWIG_check_nonnull(
    farg1->cptr, "PcmsReverseClassificationHandle",
    "PcmsReverseClassificationHandle",
    "pcms_reverse_classification_count_verts(PcmsReverseClassificationHandle)",
    return 0);
  arg1 = *((PcmsReverseClassificationHandle*)(farg1->cptr));
  result = (int)pcms_reverse_classification_count_verts(arg1);
  fresult = (int)(result);
  return fresult;
}


SWIGEXPORT SwigClassWrapper _wrap_pcms_create_xgc_field_adapter(SwigArrayWrapper *farg1, int const *farg2, void const **farg3, int const *farg4, int const *farg5, SwigClassWrapper *farg6, in_overlap_function farg7) {
  SwigClassWrapper fresult ;
  char *arg1 = (char *) 0 ;
  MPI_Comm arg2 ;
  void *arg3 = (void *) 0 ;
  int arg4 ;
  PcmsType arg5 ;
  PcmsReverseClassificationHandle arg6;
  in_overlap_function arg7 = (in_overlap_function) 0 ;
  PcmsFieldAdapterHandle result;

  arg1 = (char *)(farg1->data);
#ifdef HAVE_MPI
  arg2 = MPI_Comm_f2c((MPI_Fint)*farg2);
#else
  arg2 = *farg2;
#endif
  arg3 = (void *)(*farg3);
  arg4 = (int)(*farg4);
  arg5 = (PcmsType)(*farg5);
  SWIG_check_nonnull(
    farg6->cptr, "PcmsReverseClassificationHandle",
    "PcmsReverseClassificationHandle",
    "pcms_create_xgc_field_adapter(char const *,MPI_Comm,void "
    "*,int,PcmsType,PcmsReverseClassificationHandle const,in_overlap_function)",
    return SwigClassWrapper_uninitialized());
  arg6 = *((PcmsReverseClassificationHandle*)(farg6->cptr));
  arg7 = (in_overlap_function)(*farg7);
  result = pcms_create_xgc_field_adapter((char const*)arg1, arg2, arg3, arg4,
                                         arg5, arg6, arg7);
  fresult.cptr = (PcmsFieldAdapterHandle*)memcpy(
    (PcmsFieldAdapterHandle*)calloc(1, sizeof(PcmsFieldAdapterHandle)), &result,
    sizeof(PcmsFieldAdapterHandle));
  fresult.cmemflags = SWIG_MEM_RVALUE | SWIG_MEM_OWN;
  return fresult;
}


SWIGEXPORT SwigClassWrapper _wrap_pcms_create_dummy_field_adapter() {
  SwigClassWrapper fresult ;
  PcmsFieldAdapterHandle result;

  result = pcms_create_dummy_field_adapter();
  fresult.cptr = (PcmsFieldAdapterHandle*)memcpy(
    (PcmsFieldAdapterHandle*)calloc(1, sizeof(PcmsFieldAdapterHandle)), &result,
    sizeof(PcmsFieldAdapterHandle));
  fresult.cmemflags = SWIG_MEM_RVALUE | SWIG_MEM_OWN;
  return fresult;
}


SWIGEXPORT void _wrap_pcms_destroy_field_adapter(SwigClassWrapper *farg1) {
  PcmsFieldAdapterHandle arg1;

  SWIG_check_nonnull(
    farg1->cptr, "PcmsFieldAdapterHandle", "PcmsFieldAdapterHandle",
    "pcms_destroy_field_adapter(PcmsFieldAdapterHandle)", return);
  arg1 = *((PcmsFieldAdapterHandle*)(farg1->cptr));
  pcms_destroy_field_adapter(arg1);
}


SWIGEXPORT SwigClassWrapper _wrap_pcms_add_field(SwigClassWrapper *farg1, SwigArrayWrapper *farg2, SwigClassWrapper *farg3, int const *farg4) {
  SwigClassWrapper fresult ;
  PcmsClientHandle arg1;
  char *arg2 = (char *) 0 ;
  PcmsFieldAdapterHandle arg3;
  int arg4 ;
  PcmsFieldHandle result;

  SWIG_check_nonnull(
    farg1->cptr, "PcmsClientHandle", "PcmsClientHandle",
    "pcms_add_field(PcmsClientHandle,char const *,PcmsFieldAdapterHandle,int)",
    return SwigClassWrapper_uninitialized());
  arg1 = *((PcmsClientHandle*)(farg1->cptr));
  arg2 = (char *)(farg2->data);
  SWIG_check_nonnull(
    farg3->cptr, "PcmsFieldAdapterHandle", "PcmsFieldAdapterHandle",
    "pcms_add_field(PcmsClientHandle,char const *,PcmsFieldAdapterHandle,int)",
    return SwigClassWrapper_uninitialized());
  arg3 = *((PcmsFieldAdapterHandle*)(farg3->cptr));
  arg4 = (int)(*farg4);
  result = pcms_add_field(arg1, (char const*)arg2, arg3, arg4);
  fresult.cptr = (PcmsFieldHandle*)memcpy(
    (PcmsFieldHandle*)calloc(1, sizeof(PcmsFieldHandle)), &result,
    sizeof(PcmsFieldHandle));
  fresult.cmemflags = SWIG_MEM_RVALUE | SWIG_MEM_OWN;
  return fresult;
}


SWIGEXPORT void _wrap_pcms_send_field_name(SwigClassWrapper *farg1, SwigArrayWrapper *farg2) {
  PcmsClientHandle arg1;
  char *arg2 = (char *) 0 ;

  SWIG_check_nonnull(farg1->cptr, "PcmsClientHandle", "PcmsClientHandle",
                     "pcms_send_field_name(PcmsClientHandle,char const *)",
                     return);
  arg1 = *((PcmsClientHandle*)(farg1->cptr));
  arg2 = (char *)(farg2->data);
  pcms_send_field_name(arg1,(char const *)arg2);
}


SWIGEXPORT void _wrap_pcms_receive_field_name(SwigClassWrapper *farg1, SwigArrayWrapper *farg2) {
  PcmsClientHandle arg1;
  char *arg2 = (char *) 0 ;

  SWIG_check_nonnull(farg1->cptr, "PcmsClientHandle", "PcmsClientHandle",
                     "pcms_receive_field_name(PcmsClientHandle,char const *)",
                     return);
  arg1 = *((PcmsClientHandle*)(farg1->cptr));
  arg2 = (char *)(farg2->data);
  pcms_receive_field_name(arg1,(char const *)arg2);
}


SWIGEXPORT void _wrap_pcms_send_field(SwigClassWrapper *farg1) {
  PcmsFieldHandle arg1;

  SWIG_check_nonnull(farg1->cptr, "PcmsFieldHandle", "PcmsFieldHandle",
                     "pcms_send_field(PcmsFieldHandle)", return);
  arg1 = *((PcmsFieldHandle*)(farg1->cptr));
  pcms_send_field(arg1);
}


SWIGEXPORT void _wrap_pcms_receive_field(SwigClassWrapper *farg1) {
  PcmsFieldHandle arg1;

  SWIG_check_nonnull(farg1->cptr, "PcmsFieldHandle", "PcmsFieldHandle",
                     "pcms_receive_field(PcmsFieldHandle)", return);
  arg1 = *((PcmsFieldHandle*)(farg1->cptr));
  pcms_receive_field(arg1);
}


SWIGEXPORT void _wrap_pcms_begin_send_phase(SwigClassWrapper *farg1) {
  PcmsClientHandle arg1;

  SWIG_check_nonnull(farg1->cptr, "PcmsClientHandle", "PcmsClientHandle",
                     "pcms_begin_send_phase(PcmsClientHandle)", return);
  arg1 = *((PcmsClientHandle*)(farg1->cptr));
  pcms_begin_send_phase(arg1);
}


SWIGEXPORT void _wrap_pcms_end_send_phase(SwigClassWrapper *farg1) {
  PcmsClientHandle arg1;

  SWIG_check_nonnull(farg1->cptr, "PcmsClientHandle", "PcmsClientHandle",
                     "pcms_end_send_phase(PcmsClientHandle)", return);
  arg1 = *((PcmsClientHandle*)(farg1->cptr));
  pcms_end_send_phase(arg1);
}


SWIGEXPORT void _wrap_pcms_begin_receive_phase(SwigClassWrapper *farg1) {
  PcmsClientHandle arg1;

  SWIG_check_nonnull(farg1->cptr, "PcmsClientHandle", "PcmsClientHandle",
                     "pcms_begin_receive_phase(PcmsClientHandle)", return);
  arg1 = *((PcmsClientHandle*)(farg1->cptr));
  pcms_begin_receive_phase(arg1);
}


SWIGEXPORT void _wrap_pcms_end_receive_phase(SwigClassWrapper *farg1) {
  PcmsClientHandle arg1;

  SWIG_check_nonnull(farg1->cptr, "PcmsClientHandle", "PcmsClientHandle",
                     "pcms_end_receive_phase(PcmsClientHandle)", return);
  arg1 = *((PcmsClientHandle*)(farg1->cptr));
  pcms_end_receive_phase(arg1);
}


SWIGEXPORT void _wrap_pcms_kokkos_initialize_without_args() {
  pcms_kokkos_initialize_without_args();
}


SWIGEXPORT void _wrap_pcms_kokkos_finalize() {
  pcms_kokkos_finalize();
}



