! This file was automatically generated by SWIG (https://www.swig.org).
! Version 4.1.1+fortran
!
! Do not make changes to this file unless you know what you are doing - modify
! the SWIG interface file instead.
module pcms
 use, intrinsic :: ISO_C_BINDING
 implicit none
 private

 ! DECLARATION CONSTRUCTS
 public :: in_overlap_func
 ! enum PcmsAdapterType
 enum, bind(c)
  enumerator :: PCMS_ADAPTER_XGC
  enumerator :: PCMS_ADAPTER_OMEGAH
  enumerator :: PCMS_ADAPTER_GENE
  enumerator :: PCMS_ADAPTER_GEM
 end enum
 integer, parameter, public :: PcmsAdapterType = kind(PCMS_ADAPTER_XGC)
 public :: PCMS_ADAPTER_XGC, PCMS_ADAPTER_OMEGAH, PCMS_ADAPTER_GENE, PCMS_ADAPTER_GEM
 ! enum PcmsType
 enum, bind(c)
  enumerator :: PCMS_FLOAT
  enumerator :: PCMS_DOUBLE
  enumerator :: PCMS_INT
  enumerator :: PCMS_LONG_INT
 end enum
 integer, parameter, public :: PcmsType = kind(PCMS_FLOAT)
 public :: PCMS_FLOAT, PCMS_DOUBLE, PCMS_INT, PCMS_LONG_INT

 integer, parameter :: swig_cmem_own_bit = 0
 integer, parameter :: swig_cmem_rvalue_bit = 1
 type, bind(C) :: SwigClassWrapper
  type(C_PTR), public :: cptr = C_NULL_PTR
  integer(C_INT), public :: cmemflags = 0
 end type
 ! struct struct PcmsClientHandle
 type, public :: PcmsClientHandle
  type(SwigClassWrapper), public :: swigdata
 contains
  procedure :: set_pointer => swigf_PcmsClientHandle_pointer_set
  procedure :: get_pointer => swigf_PcmsClientHandle_pointer_get
  procedure :: release => swigf_PcmsClientHandle_release
  procedure, private :: swigf_PcmsClientHandle_op_assign__
  generic :: assignment(=) => swigf_PcmsClientHandle_op_assign__
 end type PcmsClientHandle
 ! struct struct PcmsOmegaHMeshHandle
 type, public :: PcmsOmegaHMeshHandle
  type(SwigClassWrapper), public :: swigdata
 contains
  procedure :: set_pointer => swigf_PcmsOmegaHMeshHandle_pointer_set
  procedure :: get_pointer => swigf_PcmsOmegaHMeshHandle_pointer_get
  procedure :: release => swigf_PcmsOmegaHMeshHandle_release
  procedure, private :: swigf_PcmsOmegaHMeshHandle_op_assign__
  generic :: assignment(=) => swigf_PcmsOmegaHMeshHandle_op_assign__
 end type PcmsOmegaHMeshHandle
 ! struct struct PcmsReverseClassificationHandle
 type, public :: PcmsReverseClassificationHandle
  type(SwigClassWrapper), public :: swigdata
 contains
  procedure :: set_pointer => swigf_PcmsReverseClassificationHandle_pointer_set
  procedure :: get_pointer => swigf_PcmsReverseClassificationHandle_pointer_get
  procedure :: release => swigf_PcmsReverseClassificationHandle_release
  procedure, private :: swigf_PcmsReverseClassificationHandle_op_assign__
  generic :: assignment(=) => swigf_PcmsReverseClassificationHandle_op_assign__
 end type PcmsReverseClassificationHandle
 ! struct struct PcmsFieldAdapterHandle
 type, public :: PcmsFieldAdapterHandle
  type(SwigClassWrapper), public :: swigdata
 contains
  procedure :: set_pointer => swigf_PcmsFieldAdapterHandle_pointer_set
  procedure :: get_pointer => swigf_PcmsFieldAdapterHandle_pointer_get
  procedure :: release => swigf_PcmsFieldAdapterHandle_release
  procedure, private :: swigf_PcmsFieldAdapterHandle_op_assign__
  generic :: assignment(=) => swigf_PcmsFieldAdapterHandle_op_assign__
 end type PcmsFieldAdapterHandle
 ! struct struct PcmsFieldHandle
 type, public :: PcmsFieldHandle
  type(SwigClassWrapper), public :: swigdata
 contains
  procedure :: set_pointer => swigf_PcmsFieldHandle_pointer_set
  procedure :: get_pointer => swigf_PcmsFieldHandle_pointer_get
  procedure :: release => swigf_PcmsFieldHandle_release
  procedure, private :: swigf_PcmsFieldHandle_op_assign__
  generic :: assignment(=) => swigf_PcmsFieldHandle_op_assign__
 end type PcmsFieldHandle
 type, bind(C) :: SwigArrayWrapper
  type(C_PTR), public :: data = C_NULL_PTR
  integer(C_SIZE_T), public :: size = 0
 end type
 public :: pcms_create_client
 public :: pcms_destroy_client
 public :: pcms_load_reverse_classification
 public :: pcms_destroy_reverse_classification
 public :: pcms_reverse_classification_count_verts
 public :: pcms_create_xgc_field_adapter
 public :: pcms_create_dummy_field_adapter
 public :: pcms_destroy_field_adapter
 public :: pcms_add_field
 public :: pcms_send_field_name
 public :: pcms_receive_field_name
 public :: pcms_send_field
 public :: pcms_receive_field
 public :: pcms_begin_send_phase
 public :: pcms_end_send_phase
 public :: pcms_begin_receive_phase
 public :: pcms_end_receive_phase
 public :: pcms_kokkos_initialize_without_args
 public :: pcms_kokkos_finalize
 interface PcmsOmegaHMeshHandle
  module procedure swigf_new_PcmsOmegaHMeshHandle
 end interface
 interface PcmsClientHandle
  module procedure swigf_new_PcmsClientHandle
 end interface
 interface PcmsReverseClassificationHandle
  module procedure swigf_new_PcmsReverseClassificationHandle
 end interface
 interface PcmsFieldAdapterHandle
  module procedure swigf_new_PcmsFieldAdapterHandle
 end interface
 interface PcmsFieldHandle
  module procedure swigf_new_PcmsFieldHandle
 end interface

! FUNCTION POINTER DECLARATIONS
abstract interface
function in_overlap_func(dimension, id) &
bind(C) &
result(fresult)
use, intrinsic :: ISO_C_BINDING
integer(C_INT), intent(in), value :: dimension
integer(C_INT), intent(in), value :: id
integer(C_INT8_T) :: fresult
end function

end interface


! WRAPPER DECLARATIONS
interface
 subroutine swigc_PcmsClientHandle_pointer_set(farg1, farg2) &
         bind(C, name = "_wrap_PcmsClientHandle_pointer_set")
  use, intrinsic :: ISO_C_BINDING
  import :: swigclasswrapper
  type(SwigClassWrapper), intent(in) :: farg1
  type(C_PTR), intent(in) :: farg2
 end subroutine

 function swigc_PcmsClientHandle_pointer_get(farg1) &
         bind(C, name = "_wrap_PcmsClientHandle_pointer_get") &
                 result(fresult)
  use, intrinsic :: ISO_C_BINDING
  import :: swigclasswrapper
  type(SwigClassWrapper), intent(in) :: farg1
  type(C_PTR) :: fresult
 end function

 function swigc_new_PcmsClientHandle() &
         bind(C, name = "_wrap_new_PcmsClientHandle") &
                 result(fresult)
  use, intrinsic :: ISO_C_BINDING
  import :: swigclasswrapper
  type(SwigClassWrapper) :: fresult
 end function

 subroutine swigc_delete_PcmsClientHandle(farg1) &
         bind(C, name = "_wrap_delete_PcmsClientHandle")
  use, intrinsic :: ISO_C_BINDING
  import :: swigclasswrapper
  type(SwigClassWrapper), intent(inout) :: farg1
 end subroutine

 subroutine swigc_PcmsClientHandle_op_assign__(farg1, farg2) &
         bind(C, name = "_wrap_PcmsClientHandle_op_assign__")
  use, intrinsic :: ISO_C_BINDING
  import :: swigclasswrapper
  type(SwigClassWrapper), intent(inout) :: farg1
  type(SwigClassWrapper), intent(in) :: farg2
 end subroutine

 subroutine swigc_PcmsOmegaHMeshHandle_pointer_set(farg1, farg2) &
         bind(C, name = "_wrap_PcmsOmegaHMeshHandle_pointer_set")
  use, intrinsic :: ISO_C_BINDING
  import :: swigclasswrapper
  type(SwigClassWrapper), intent(in) :: farg1
  type(C_PTR), intent(in) :: farg2
 end subroutine

 function swigc_PcmsOmegaHMeshHandle_pointer_get(farg1) &
         bind(C, name = "_wrap_PcmsOmegaHMeshHandle_pointer_get") &
                 result(fresult)
  use, intrinsic :: ISO_C_BINDING
  import :: swigclasswrapper
  type(SwigClassWrapper), intent(in) :: farg1
  type(C_PTR) :: fresult
 end function

 function swigc_new_PcmsOmegaHMeshHandle() &
         bind(C, name = "_wrap_new_PcmsOmegaHMeshHandle") &
                 result(fresult)
  use, intrinsic :: ISO_C_BINDING
  import :: swigclasswrapper
  type(SwigClassWrapper) :: fresult
 end function

 subroutine swigc_delete_PcmsOmegaHMeshHandle(farg1) &
         bind(C, name = "_wrap_delete_PcmsOmegaHMeshHandle")
  use, intrinsic :: ISO_C_BINDING
  import :: swigclasswrapper
  type(SwigClassWrapper), intent(inout) :: farg1
 end subroutine

 subroutine swigc_PcmsOmegaHMeshHandle_op_assign__(farg1, farg2) &
         bind(C, name = "_wrap_PcmsOmegaHMeshHandle_op_assign__")
  use, intrinsic :: ISO_C_BINDING
  import :: swigclasswrapper
  type(SwigClassWrapper), intent(inout) :: farg1
  type(SwigClassWrapper), intent(in) :: farg2
 end subroutine

 subroutine swigc_PcmsReverseClassificationHandle_pointer_set(farg1, farg2) &
         bind(C, name = "_wrap_PcmsReverseClassificationHandle_pointer_set")
  use, intrinsic :: ISO_C_BINDING
  import :: swigclasswrapper
  type(SwigClassWrapper), intent(in) :: farg1
  type(C_PTR), intent(in) :: farg2
 end subroutine

 function swigc_PcmsReverseClassificationHandle_pointer_get(farg1) &
         bind(C, name = "_wrap_PcmsReverseClassificationHandle_pointer_get") &
                 result(fresult)
  use, intrinsic :: ISO_C_BINDING
  import :: swigclasswrapper
  type(SwigClassWrapper), intent(in) :: farg1
  type(C_PTR) :: fresult
 end function

 function swigc_new_PcmsReverseClassificationHandle() &
         bind(C, name = "_wrap_new_PcmsReverseClassificationHandle") &
                 result(fresult)
  use, intrinsic :: ISO_C_BINDING
  import :: swigclasswrapper
  type(SwigClassWrapper) :: fresult
 end function

 subroutine swigc_delete_PcmsReverseClassificationHandle(farg1) &
         bind(C, name = "_wrap_delete_PcmsReverseClassificationHandle")
  use, intrinsic :: ISO_C_BINDING
  import :: swigclasswrapper
  type(SwigClassWrapper), intent(inout) :: farg1
 end subroutine

 subroutine swigc_PcmsReverseClassificationHandle_op_assign__(farg1, farg2) &
         bind(C, name = "_wrap_PcmsReverseClassificationHandle_op_assign__")
  use, intrinsic :: ISO_C_BINDING
  import :: swigclasswrapper
  type(SwigClassWrapper), intent(inout) :: farg1
  type(SwigClassWrapper), intent(in) :: farg2
 end subroutine

 subroutine swigc_PcmsFieldAdapterHandle_pointer_set(farg1, farg2) &
         bind(C, name = "_wrap_PcmsFieldAdapterHandle_pointer_set")
  use, intrinsic :: ISO_C_BINDING
  import :: swigclasswrapper
  type(SwigClassWrapper), intent(in) :: farg1
  type(C_PTR), intent(in) :: farg2
 end subroutine

 function swigc_PcmsFieldAdapterHandle_pointer_get(farg1) &
         bind(C, name = "_wrap_PcmsFieldAdapterHandle_pointer_get") &
                 result(fresult)
  use, intrinsic :: ISO_C_BINDING
  import :: swigclasswrapper
  type(SwigClassWrapper), intent(in) :: farg1
  type(C_PTR) :: fresult
 end function

 function swigc_new_PcmsFieldAdapterHandle() &
         bind(C, name = "_wrap_new_PcmsFieldAdapterHandle") &
                 result(fresult)
  use, intrinsic :: ISO_C_BINDING
  import :: swigclasswrapper
  type(SwigClassWrapper) :: fresult
 end function

 subroutine swigc_delete_PcmsFieldAdapterHandle(farg1) &
         bind(C, name = "_wrap_delete_PcmsFieldAdapterHandle")
  use, intrinsic :: ISO_C_BINDING
  import :: swigclasswrapper
  type(SwigClassWrapper), intent(inout) :: farg1
 end subroutine

 subroutine swigc_PcmsFieldAdapterHandle_op_assign__(farg1, farg2) &
         bind(C, name = "_wrap_PcmsFieldAdapterHandle_op_assign__")
  use, intrinsic :: ISO_C_BINDING
  import :: swigclasswrapper
  type(SwigClassWrapper), intent(inout) :: farg1
  type(SwigClassWrapper), intent(in) :: farg2
 end subroutine

 subroutine swigc_PcmsFieldHandle_pointer_set(farg1, farg2) &
         bind(C, name = "_wrap_PcmsFieldHandle_pointer_set")
  use, intrinsic :: ISO_C_BINDING
  import :: swigclasswrapper
  type(SwigClassWrapper), intent(in) :: farg1
  type(C_PTR), intent(in) :: farg2
 end subroutine

 function swigc_PcmsFieldHandle_pointer_get(farg1) &
         bind(C, name = "_wrap_PcmsFieldHandle_pointer_get") &
                 result(fresult)
  use, intrinsic :: ISO_C_BINDING
  import :: swigclasswrapper
  type(SwigClassWrapper), intent(in) :: farg1
  type(C_PTR) :: fresult
 end function

 function swigc_new_PcmsFieldHandle() &
         bind(C, name = "_wrap_new_PcmsFieldHandle") &
                 result(fresult)
  use, intrinsic :: ISO_C_BINDING
  import :: swigclasswrapper
  type(SwigClassWrapper) :: fresult
 end function

 subroutine swigc_delete_PcmsFieldHandle(farg1) &
         bind(C, name = "_wrap_delete_PcmsFieldHandle")
  use, intrinsic :: ISO_C_BINDING
  import :: swigclasswrapper
  type(SwigClassWrapper), intent(inout) :: farg1
 end subroutine

 subroutine swigc_PcmsFieldHandle_op_assign__(farg1, farg2) &
         bind(C, name = "_wrap_PcmsFieldHandle_op_assign__")
  use, intrinsic :: ISO_C_BINDING
  import :: swigclasswrapper
  type(SwigClassWrapper), intent(inout) :: farg1
  type(SwigClassWrapper), intent(in) :: farg2
 end subroutine

function swigc_pcms_create_client(farg1, farg2) &
bind(C, name="_wrap_pcms_create_client") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
import :: swigarraywrapper
import :: swigclasswrapper
type(SwigArrayWrapper) :: farg1
integer(C_INT), intent(in) :: farg2
type(SwigClassWrapper) :: fresult
end function

subroutine swigc_pcms_destroy_client(farg1) &
bind(C, name="_wrap_pcms_destroy_client")
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper), intent(in) :: farg1
end subroutine

function swigc_pcms_load_reverse_classification(farg1, farg2) &
bind(C, name="_wrap_pcms_load_reverse_classification") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
import :: swigarraywrapper
import :: swigclasswrapper
type(SwigArrayWrapper) :: farg1
integer(C_INT), intent(in) :: farg2
type(SwigClassWrapper) :: fresult
end function

subroutine swigc_pcms_destroy_reverse_classification(farg1) &
bind(C, name="_wrap_pcms_destroy_reverse_classification")
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper), intent(in) :: farg1
end subroutine

function swigc_pcms_reverse_classification_count_verts(farg1) &
bind(C, name="_wrap_pcms_reverse_classification_count_verts") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper), intent(in) :: farg1
integer(C_INT) :: fresult
end function

function swigc_pcms_create_xgc_field_adapter(farg1, farg2, farg3, farg4, farg5, farg6, farg7) &
bind(C, name="_wrap_pcms_create_xgc_field_adapter") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
import :: swigarraywrapper
import :: swigclasswrapper
type(SwigArrayWrapper) :: farg1
integer(C_INT), intent(in) :: farg2
type(C_PTR), intent(in) :: farg3
integer(C_INT), intent(in) :: farg4
integer(C_INT), intent(in) :: farg5
type(SwigClassWrapper), intent(in) :: farg6
type(C_FUNPTR), value :: farg7
type(SwigClassWrapper) :: fresult
end function

function swigc_pcms_create_dummy_field_adapter() &
bind(C, name="_wrap_pcms_create_dummy_field_adapter") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper) :: fresult
end function

subroutine swigc_pcms_destroy_field_adapter(farg1) &
bind(C, name="_wrap_pcms_destroy_field_adapter")
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper), intent(in) :: farg1
end subroutine

function swigc_pcms_add_field(farg1, farg2, farg3, farg4) &
bind(C, name="_wrap_pcms_add_field") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
import :: swigarraywrapper
import :: swigclasswrapper
type(SwigClassWrapper), intent(in) :: farg1
type(SwigArrayWrapper) :: farg2
type(SwigClassWrapper), intent(in) :: farg3
integer(C_INT), intent(in) :: farg4
type(SwigClassWrapper) :: fresult
end function

subroutine swigc_pcms_send_field_name(farg1, farg2) &
bind(C, name="_wrap_pcms_send_field_name")
use, intrinsic :: ISO_C_BINDING
import :: swigarraywrapper
import :: swigclasswrapper
type(SwigClassWrapper), intent(in) :: farg1
type(SwigArrayWrapper) :: farg2
end subroutine

subroutine swigc_pcms_receive_field_name(farg1, farg2) &
bind(C, name="_wrap_pcms_receive_field_name")
use, intrinsic :: ISO_C_BINDING
import :: swigarraywrapper
import :: swigclasswrapper
type(SwigClassWrapper), intent(in) :: farg1
type(SwigArrayWrapper) :: farg2
end subroutine

subroutine swigc_pcms_send_field(farg1) &
bind(C, name="_wrap_pcms_send_field")
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper), intent(in) :: farg1
end subroutine

subroutine swigc_pcms_receive_field(farg1) &
bind(C, name="_wrap_pcms_receive_field")
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper), intent(in) :: farg1
end subroutine

subroutine swigc_pcms_begin_send_phase(farg1) &
bind(C, name="_wrap_pcms_begin_send_phase")
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper), intent(in) :: farg1
end subroutine

subroutine swigc_pcms_end_send_phase(farg1) &
bind(C, name="_wrap_pcms_end_send_phase")
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper), intent(in) :: farg1
end subroutine

subroutine swigc_pcms_begin_receive_phase(farg1) &
bind(C, name="_wrap_pcms_begin_receive_phase")
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper), intent(in) :: farg1
end subroutine

subroutine swigc_pcms_end_receive_phase(farg1) &
bind(C, name="_wrap_pcms_end_receive_phase")
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper), intent(in) :: farg1
end subroutine

subroutine swigc_pcms_kokkos_initialize_without_args() &
bind(C, name="_wrap_pcms_kokkos_initialize_without_args")
use, intrinsic :: ISO_C_BINDING
end subroutine

subroutine swigc_pcms_kokkos_finalize() &
bind(C, name="_wrap_pcms_kokkos_finalize")
use, intrinsic :: ISO_C_BINDING
end subroutine

end interface


contains
 ! MODULE SUBPROGRAMS
 subroutine swigf_PcmsClientHandle_pointer_set(self, pointer)
  use, intrinsic :: ISO_C_BINDING
  class(PcmsClientHandle), intent(in) :: self
  type(C_PTR), intent(in) :: pointer
  type(SwigClassWrapper) :: farg1
  type(C_PTR) :: farg2

  farg1 = self%swigdata
  farg2 = pointer
  call swigc_PcmsClientHandle_pointer_set(farg1, farg2)
 end subroutine

 function swigf_PcmsClientHandle_pointer_get(self) &
         result(swig_result)
  use, intrinsic :: ISO_C_BINDING
  type(C_PTR) :: swig_result
  class(PcmsClientHandle), intent(in) :: self
  type(C_PTR) :: fresult
  type(SwigClassWrapper) :: farg1

  farg1 = self%swigdata
  fresult = swigc_PcmsClientHandle_pointer_get(farg1)
  swig_result = fresult
 end function

 function swigf_new_PcmsClientHandle() &
         result(self)
  use, intrinsic :: ISO_C_BINDING
  type(PcmsClientHandle) :: self
  type(SwigClassWrapper) :: fresult

  fresult = swigc_new_PcmsClientHandle()
  self%swigdata = fresult
 end function

 subroutine swigf_PcmsClientHandle_release(self)
  use, intrinsic :: ISO_C_BINDING
  class(PcmsClientHandle), intent(inout) :: self
  type(SwigClassWrapper) :: farg1

  farg1 = self%swigdata
  if (btest(farg1%cmemflags, swig_cmem_own_bit)) then
   call swigc_delete_PcmsClientHandle(farg1)
  endif
  farg1%cptr = C_NULL_PTR
  farg1%cmemflags = 0
  self%swigdata = farg1
 end subroutine

 subroutine swigf_PcmsClientHandle_op_assign__(self, other)
  use, intrinsic :: ISO_C_BINDING
  class(PcmsClientHandle), intent(inout) :: self
  type(PcmsClientHandle), intent(in) :: other
  type(SwigClassWrapper) :: farg1
  type(SwigClassWrapper) :: farg2

  farg1 = self%swigdata
  farg2 = other%swigdata
  call swigc_PcmsClientHandle_op_assign__(farg1, farg2)
  self%swigdata = farg1
 end subroutine

 subroutine swigf_PcmsOmegaHMeshHandle_pointer_set(self, pointer)
  use, intrinsic :: ISO_C_BINDING
  class(PcmsOmegaHMeshHandle), intent(in) :: self
  type(C_PTR), intent(in) :: pointer
  type(SwigClassWrapper) :: farg1
  type(C_PTR) :: farg2

  farg1 = self%swigdata
  farg2 = pointer
  call swigc_PcmsOmegaHMeshHandle_pointer_set(farg1, farg2)
 end subroutine

 function swigf_PcmsOmegaHMeshHandle_pointer_get(self) &
         result(swig_result)
  use, intrinsic :: ISO_C_BINDING
  type(C_PTR) :: swig_result
  class(PcmsOmegaHMeshHandle), intent(in) :: self
  type(C_PTR) :: fresult
  type(SwigClassWrapper) :: farg1

  farg1 = self%swigdata
  fresult = swigc_PcmsOmegaHMeshHandle_pointer_get(farg1)
  swig_result = fresult
 end function

 function swigf_new_PcmsOmegaHMeshHandle() &
         result(self)
  use, intrinsic :: ISO_C_BINDING
  type(PcmsOmegaHMeshHandle) :: self
  type(SwigClassWrapper) :: fresult

  fresult = swigc_new_PcmsOmegaHMeshHandle()
  self%swigdata = fresult
 end function

 subroutine swigf_PcmsOmegaHMeshHandle_release(self)
  use, intrinsic :: ISO_C_BINDING
  class(PcmsOmegaHMeshHandle), intent(inout) :: self
  type(SwigClassWrapper) :: farg1

  farg1 = self%swigdata
  if (btest(farg1%cmemflags, swig_cmem_own_bit)) then
   call swigc_delete_PcmsOmegaHMeshHandle(farg1)
  endif
  farg1%cptr = C_NULL_PTR
  farg1%cmemflags = 0
  self%swigdata = farg1
 end subroutine

 subroutine swigf_PcmsOmegaHMeshHandle_op_assign__(self, other)
  use, intrinsic :: ISO_C_BINDING
  class(PcmsOmegaHMeshHandle), intent(inout) :: self
  type(PcmsOmegaHMeshHandle), intent(in) :: other
  type(SwigClassWrapper) :: farg1
  type(SwigClassWrapper) :: farg2

  farg1 = self%swigdata
  farg2 = other%swigdata
  call swigc_PcmsOmegaHMeshHandle_op_assign__(farg1, farg2)
  self%swigdata = farg1
 end subroutine

 subroutine swigf_PcmsReverseClassificationHandle_pointer_set(self, pointer)
  use, intrinsic :: ISO_C_BINDING
  class(PcmsReverseClassificationHandle), intent(in) :: self
  type(C_PTR), intent(in) :: pointer
  type(SwigClassWrapper) :: farg1
  type(C_PTR) :: farg2

  farg1 = self%swigdata
  farg2 = pointer
  call swigc_PcmsReverseClassificationHandle_pointer_set(farg1, farg2)
 end subroutine

 function swigf_PcmsReverseClassificationHandle_pointer_get(self) &
         result(swig_result)
  use, intrinsic :: ISO_C_BINDING
  type(C_PTR) :: swig_result
  class(PcmsReverseClassificationHandle), intent(in) :: self
  type(C_PTR) :: fresult
  type(SwigClassWrapper) :: farg1

  farg1 = self%swigdata
  fresult = swigc_PcmsReverseClassificationHandle_pointer_get(farg1)
  swig_result = fresult
 end function

 function swigf_new_PcmsReverseClassificationHandle() &
         result(self)
  use, intrinsic :: ISO_C_BINDING
  type(PcmsReverseClassificationHandle) :: self
  type(SwigClassWrapper) :: fresult

  fresult = swigc_new_PcmsReverseClassificationHandle()
  self%swigdata = fresult
 end function

 subroutine swigf_PcmsReverseClassificationHandle_release(self)
  use, intrinsic :: ISO_C_BINDING
  class(PcmsReverseClassificationHandle), intent(inout) :: self
  type(SwigClassWrapper) :: farg1

  farg1 = self%swigdata
  if (btest(farg1%cmemflags, swig_cmem_own_bit)) then
   call swigc_delete_PcmsReverseClassificationHandle(farg1)
  endif
  farg1%cptr = C_NULL_PTR
  farg1%cmemflags = 0
  self%swigdata = farg1
 end subroutine

 subroutine swigf_PcmsReverseClassificationHandle_op_assign__(self, other)
  use, intrinsic :: ISO_C_BINDING
  class(PcmsReverseClassificationHandle), intent(inout) :: self
  type(PcmsReverseClassificationHandle), intent(in) :: other
  type(SwigClassWrapper) :: farg1
  type(SwigClassWrapper) :: farg2

  farg1 = self%swigdata
  farg2 = other%swigdata
  call swigc_PcmsReverseClassificationHandle_op_assign__(farg1, farg2)
  self%swigdata = farg1
 end subroutine

 subroutine swigf_PcmsFieldAdapterHandle_pointer_set(self, pointer)
  use, intrinsic :: ISO_C_BINDING
  class(PcmsFieldAdapterHandle), intent(in) :: self
  type(C_PTR), intent(in) :: pointer
  type(SwigClassWrapper) :: farg1
  type(C_PTR) :: farg2

  farg1 = self%swigdata
  farg2 = pointer
  call swigc_PcmsFieldAdapterHandle_pointer_set(farg1, farg2)
 end subroutine

 function swigf_PcmsFieldAdapterHandle_pointer_get(self) &
         result(swig_result)
  use, intrinsic :: ISO_C_BINDING
  type(C_PTR) :: swig_result
  class(PcmsFieldAdapterHandle), intent(in) :: self
  type(C_PTR) :: fresult
  type(SwigClassWrapper) :: farg1

  farg1 = self%swigdata
  fresult = swigc_PcmsFieldAdapterHandle_pointer_get(farg1)
  swig_result = fresult
 end function

 function swigf_new_PcmsFieldAdapterHandle() &
         result(self)
  use, intrinsic :: ISO_C_BINDING
  type(PcmsFieldAdapterHandle) :: self
  type(SwigClassWrapper) :: fresult

  fresult = swigc_new_PcmsFieldAdapterHandle()
  self%swigdata = fresult
 end function

 subroutine swigf_PcmsFieldAdapterHandle_release(self)
  use, intrinsic :: ISO_C_BINDING
  class(PcmsFieldAdapterHandle), intent(inout) :: self
  type(SwigClassWrapper) :: farg1

  farg1 = self%swigdata
  if (btest(farg1%cmemflags, swig_cmem_own_bit)) then
   call swigc_delete_PcmsFieldAdapterHandle(farg1)
  endif
  farg1%cptr = C_NULL_PTR
  farg1%cmemflags = 0
  self%swigdata = farg1
 end subroutine

 subroutine swigf_PcmsFieldAdapterHandle_op_assign__(self, other)
  use, intrinsic :: ISO_C_BINDING
  class(PcmsFieldAdapterHandle), intent(inout) :: self
  type(PcmsFieldAdapterHandle), intent(in) :: other
  type(SwigClassWrapper) :: farg1
  type(SwigClassWrapper) :: farg2

  farg1 = self%swigdata
  farg2 = other%swigdata
  call swigc_PcmsFieldAdapterHandle_op_assign__(farg1, farg2)
  self%swigdata = farg1
 end subroutine

 subroutine swigf_PcmsFieldHandle_pointer_set(self, pointer)
  use, intrinsic :: ISO_C_BINDING
  class(PcmsFieldHandle), intent(in) :: self
  type(C_PTR), intent(in) :: pointer
  type(SwigClassWrapper) :: farg1
  type(C_PTR) :: farg2

  farg1 = self%swigdata
  farg2 = pointer
  call swigc_PcmsFieldHandle_pointer_set(farg1, farg2)
 end subroutine

 function swigf_PcmsFieldHandle_pointer_get(self) &
         result(swig_result)
  use, intrinsic :: ISO_C_BINDING
  type(C_PTR) :: swig_result
  class(PcmsFieldHandle), intent(in) :: self
  type(C_PTR) :: fresult
  type(SwigClassWrapper) :: farg1

  farg1 = self%swigdata
  fresult = swigc_PcmsFieldHandle_pointer_get(farg1)
  swig_result = fresult
 end function

 function swigf_new_PcmsFieldHandle() &
         result(self)
  use, intrinsic :: ISO_C_BINDING
  type(PcmsFieldHandle) :: self
  type(SwigClassWrapper) :: fresult

  fresult = swigc_new_PcmsFieldHandle()
  self%swigdata = fresult
 end function

 subroutine swigf_PcmsFieldHandle_release(self)
  use, intrinsic :: ISO_C_BINDING
  class(PcmsFieldHandle), intent(inout) :: self
  type(SwigClassWrapper) :: farg1

  farg1 = self%swigdata
  if (btest(farg1%cmemflags, swig_cmem_own_bit)) then
   call swigc_delete_PcmsFieldHandle(farg1)
  endif
  farg1%cptr = C_NULL_PTR
  farg1%cmemflags = 0
  self%swigdata = farg1
 end subroutine

 subroutine swigf_PcmsFieldHandle_op_assign__(self, other)
  use, intrinsic :: ISO_C_BINDING
  class(PcmsFieldHandle), intent(inout) :: self
  type(PcmsFieldHandle), intent(in) :: other
  type(SwigClassWrapper) :: farg1
  type(SwigClassWrapper) :: farg2

  farg1 = self%swigdata
  farg2 = other%swigdata
  call swigc_PcmsFieldHandle_op_assign__(farg1, farg2)
  self%swigdata = farg1
 end subroutine


subroutine SWIGTM_fin_char_Sm_(finp, iminp, temp)
  use, intrinsic :: ISO_C_BINDING
  character(len=*), intent(in) :: finp
  type(SwigArrayWrapper), intent(out) :: iminp
  character(kind=C_CHAR), dimension(:), target, allocatable, intent(out) :: temp
  integer :: i

  allocate(character(kind=C_CHAR) :: temp(len(finp) + 1))
  do i=1,len(finp)
    temp(i) = char(ichar(finp(i:i)), kind=C_CHAR)
  end do
  i = len(finp) + 1
  temp(i) = C_NULL_CHAR ! C finp compatibility
  iminp%data = c_loc(temp)
  iminp%size = len(finp, kind=C_SIZE_T)
end subroutine

function pcms_create_client(name, comm) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
type(PcmsClientHandle) :: swig_result
character(len=*), target :: name
integer :: comm
type(SwigClassWrapper) :: fresult 
character(kind=C_CHAR), dimension(:), allocatable, target :: farg1_temp 
type(SwigArrayWrapper) :: farg1 
integer(C_INT) :: farg2 

call SWIGTM_fin_char_Sm_(name, farg1, farg1_temp)
farg2 = int(comm, C_INT)
fresult = swigc_pcms_create_client(farg1, farg2)
swig_result%swigdata = fresult
end function

subroutine pcms_destroy_client(arg0)
use, intrinsic :: ISO_C_BINDING
type(PcmsClientHandle), intent(in) :: arg0
type(SwigClassWrapper) :: farg1 

farg1 = arg0%swigdata
call swigc_pcms_destroy_client(farg1)
end subroutine

function pcms_load_reverse_classification(file, comm) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
type(PcmsReverseClassificationHandle) :: swig_result
character(len=*), target :: file
integer :: comm
type(SwigClassWrapper) :: fresult 
character(kind=C_CHAR), dimension(:), allocatable, target :: farg1_temp 
type(SwigArrayWrapper) :: farg1 
integer(C_INT) :: farg2 

call SWIGTM_fin_char_Sm_(file, farg1, farg1_temp)
farg2 = int(comm, C_INT)
fresult = swigc_pcms_load_reverse_classification(farg1, farg2)
swig_result%swigdata = fresult
end function

subroutine pcms_destroy_reverse_classification(arg0)
use, intrinsic :: ISO_C_BINDING
type(PcmsReverseClassificationHandle), intent(in) :: arg0
type(SwigClassWrapper) :: farg1 

farg1 = arg0%swigdata
call swigc_pcms_destroy_reverse_classification(farg1)
end subroutine

function pcms_reverse_classification_count_verts(arg0) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
integer(C_INT) :: swig_result
type(PcmsReverseClassificationHandle), intent(in) :: arg0
integer(C_INT) :: fresult 
type(SwigClassWrapper) :: farg1 

farg1 = arg0%swigdata
fresult = swigc_pcms_reverse_classification_count_verts(farg1)
swig_result = fresult
end function

function pcms_create_xgc_field_adapter(name, plane_comm, data, size, data_type, rc, in_overlap) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
type(PcmsFieldAdapterHandle) :: swig_result
character(len=*), target :: name
integer :: plane_comm
type(C_PTR), intent(in) :: data
integer(C_INT), intent(in) :: size
integer(PcmsType), intent(in) :: data_type
type(PcmsReverseClassificationHandle), intent(in) :: rc
procedure(in_overlap_func) :: in_overlap
type(SwigClassWrapper) :: fresult 
character(kind=C_CHAR), dimension(:), allocatable, target :: farg1_temp 
type(SwigArrayWrapper) :: farg1 
integer(C_INT) :: farg2 
type(C_PTR) :: farg3 
integer(C_INT) :: farg4 
integer(C_INT) :: farg5 
type(SwigClassWrapper) :: farg6 
type(C_FUNPTR) :: farg7 

call SWIGTM_fin_char_Sm_(name, farg1, farg1_temp)
farg2 = int(plane_comm, C_INT)
farg3 = data
farg4 = size
farg5 = data_type
farg6 = rc%swigdata
farg7 = c_funloc(in_overlap)
fresult = swigc_pcms_create_xgc_field_adapter(farg1, farg2, farg3, farg4, farg5, farg6, farg7)
swig_result%swigdata = fresult
end function

function pcms_create_dummy_field_adapter() &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
type(PcmsFieldAdapterHandle) :: swig_result
type(SwigClassWrapper) :: fresult 

fresult = swigc_pcms_create_dummy_field_adapter()
swig_result%swigdata = fresult
end function

subroutine pcms_destroy_field_adapter(arg0)
use, intrinsic :: ISO_C_BINDING
type(PcmsFieldAdapterHandle), intent(in) :: arg0
type(SwigClassWrapper) :: farg1 

farg1 = arg0%swigdata
call swigc_pcms_destroy_field_adapter(farg1)
end subroutine

function pcms_add_field(client_handle, name, adapter_handle, participates) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
type(PcmsFieldHandle) :: swig_result
type(PcmsClientHandle), intent(in) :: client_handle
character(len=*), target :: name
type(PcmsFieldAdapterHandle), intent(in) :: adapter_handle
integer(C_INT), intent(in) :: participates
type(SwigClassWrapper) :: fresult 
type(SwigClassWrapper) :: farg1 
character(kind=C_CHAR), dimension(:), allocatable, target :: farg2_temp 
type(SwigArrayWrapper) :: farg2 
type(SwigClassWrapper) :: farg3 
integer(C_INT) :: farg4 

farg1 = client_handle%swigdata
call SWIGTM_fin_char_Sm_(name, farg2, farg2_temp)
farg3 = adapter_handle%swigdata
farg4 = participates
fresult = swigc_pcms_add_field(farg1, farg2, farg3, farg4)
swig_result%swigdata = fresult
end function

subroutine pcms_send_field_name(arg0, name)
use, intrinsic :: ISO_C_BINDING
type(PcmsClientHandle), intent(in) :: arg0
character(len=*), target :: name
type(SwigClassWrapper) :: farg1 
character(kind=C_CHAR), dimension(:), allocatable, target :: farg2_temp 
type(SwigArrayWrapper) :: farg2 

farg1 = arg0%swigdata
call SWIGTM_fin_char_Sm_(name, farg2, farg2_temp)
call swigc_pcms_send_field_name(farg1, farg2)
end subroutine

subroutine pcms_receive_field_name(arg0, name)
use, intrinsic :: ISO_C_BINDING
type(PcmsClientHandle), intent(in) :: arg0
character(len=*), target :: name
type(SwigClassWrapper) :: farg1 
character(kind=C_CHAR), dimension(:), allocatable, target :: farg2_temp 
type(SwigArrayWrapper) :: farg2 

farg1 = arg0%swigdata
call SWIGTM_fin_char_Sm_(name, farg2, farg2_temp)
call swigc_pcms_receive_field_name(farg1, farg2)
end subroutine

subroutine pcms_send_field(arg0)
use, intrinsic :: ISO_C_BINDING
type(PcmsFieldHandle), intent(in) :: arg0
type(SwigClassWrapper) :: farg1 

farg1 = arg0%swigdata
call swigc_pcms_send_field(farg1)
end subroutine

subroutine pcms_receive_field(arg0)
use, intrinsic :: ISO_C_BINDING
type(PcmsFieldHandle), intent(in) :: arg0
type(SwigClassWrapper) :: farg1 

farg1 = arg0%swigdata
call swigc_pcms_receive_field(farg1)
end subroutine

subroutine pcms_begin_send_phase(arg0)
use, intrinsic :: ISO_C_BINDING
type(PcmsClientHandle), intent(in) :: arg0
type(SwigClassWrapper) :: farg1 

farg1 = arg0%swigdata
call swigc_pcms_begin_send_phase(farg1)
end subroutine

subroutine pcms_end_send_phase(arg0)
use, intrinsic :: ISO_C_BINDING
type(PcmsClientHandle), intent(in) :: arg0
type(SwigClassWrapper) :: farg1 

farg1 = arg0%swigdata
call swigc_pcms_end_send_phase(farg1)
end subroutine

subroutine pcms_begin_receive_phase(arg0)
use, intrinsic :: ISO_C_BINDING
type(PcmsClientHandle), intent(in) :: arg0
type(SwigClassWrapper) :: farg1 

farg1 = arg0%swigdata
call swigc_pcms_begin_receive_phase(farg1)
end subroutine

subroutine pcms_end_receive_phase(arg0)
use, intrinsic :: ISO_C_BINDING
type(PcmsClientHandle), intent(in) :: arg0
type(SwigClassWrapper) :: farg1 

farg1 = arg0%swigdata
call swigc_pcms_end_receive_phase(farg1)
end subroutine

subroutine pcms_kokkos_initialize_without_args()
use, intrinsic :: ISO_C_BINDING

call swigc_pcms_kokkos_initialize_without_args()
end subroutine

subroutine pcms_kokkos_finalize()
use, intrinsic :: ISO_C_BINDING

call swigc_pcms_kokkos_finalize()
end subroutine


end module
