! This file was automatically generated by SWIG (https://www.swig.org).
! Version 4.2.0
!
! Do not make changes to this file unless you know what you are doing - modify
! the SWIG interface file instead.
module pcms_interpolator
 use, intrinsic :: ISO_C_BINDING
 implicit none
 private

 ! DECLARATION CONSTRUCTS

 integer, parameter :: swig_cmem_own_bit = 0
 integer, parameter :: swig_cmem_rvalue_bit = 1
 type, bind(C) :: SwigClassWrapper
  type(C_PTR), public :: cptr = C_NULL_PTR
  integer(C_INT), public :: cmemflags = 0
 end type
 ! struct struct PcmsInterpolatorOHMeshHandle
 type, public :: PcmsInterpolatorOHMeshHandle
  type(SwigClassWrapper), public :: swigdata
 contains
  procedure :: set_mesh_handle => swigf_PcmsInterpolatorOHMeshHandle_mesh_handle_set
  procedure :: get_mesh_handle => swigf_PcmsInterpolatorOHMeshHandle_mesh_handle_get
  procedure :: set_lib_handle => swigf_PcmsInterpolatorOHMeshHandle_lib_handle_set
  procedure :: get_lib_handle => swigf_PcmsInterpolatorOHMeshHandle_lib_handle_get
  procedure :: release => swigf_PcmsInterpolatorOHMeshHandle_release
  procedure, private :: swigf_PcmsInterpolatorOHMeshHandle_op_assign__
  generic :: assignment(=) => swigf_PcmsInterpolatorOHMeshHandle_op_assign__
 end type PcmsInterpolatorOHMeshHandle
 ! struct struct PcmsInterpolatorHandle
 type, public :: PcmsInterpolatorHandle
  type(SwigClassWrapper), public :: swigdata
 contains
  procedure :: set_pointer => swigf_PcmsInterpolatorHandle_pointer_set
  procedure :: get_pointer => swigf_PcmsInterpolatorHandle_pointer_get
  procedure :: release => swigf_PcmsInterpolatorHandle_release
  procedure, private :: swigf_PcmsInterpolatorHandle_op_assign__
  generic :: assignment(=) => swigf_PcmsInterpolatorHandle_op_assign__
 end type PcmsInterpolatorHandle
 public :: pcms_create_point_based_interpolator
 type, bind(C) :: SwigArrayWrapper
  type(C_PTR), public :: data = C_NULL_PTR
  integer(C_SIZE_T), public :: size = 0
 end type
 public :: pcms_create_degas2xgc_interpolator
 public :: pcms_create_degas2xgcnode_interpolator
 public :: pcms_create_xgcnodedegas2_interpolator
 public :: pcms_create_interpolator
 public :: pcms_destroy_interpolator
 public :: pcms_kokkos_initialize_without_args
 public :: pcms_kokkos_finalize
 public :: read_oh_mesh
 public :: release_oh_mesh
 public :: pcms_interpolate
 interface PcmsInterpolatorHandle
  module procedure swigf_new_PcmsInterpolatorHandle
 end interface
 interface PcmsInterpolatorOHMeshHandle
  module procedure swigf_new_PcmsInterpolatorOHMeshHandle
 end interface

! WRAPPER DECLARATIONS
interface
subroutine swigc_PcmsInterpolatorOHMeshHandle_mesh_handle_set(farg1, farg2) &
bind(C, name="_wrap_PcmsInterpolatorOHMeshHandle_mesh_handle_set")
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper), intent(in) :: farg1
type(C_PTR), intent(in) :: farg2
end subroutine

function swigc_PcmsInterpolatorOHMeshHandle_mesh_handle_get(farg1) &
bind(C, name="_wrap_PcmsInterpolatorOHMeshHandle_mesh_handle_get") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper), intent(in) :: farg1
type(C_PTR) :: fresult
end function

subroutine swigc_PcmsInterpolatorOHMeshHandle_lib_handle_set(farg1, farg2) &
bind(C, name="_wrap_PcmsInterpolatorOHMeshHandle_lib_handle_set")
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper), intent(in) :: farg1
type(C_PTR), intent(in) :: farg2
end subroutine

function swigc_PcmsInterpolatorOHMeshHandle_lib_handle_get(farg1) &
bind(C, name="_wrap_PcmsInterpolatorOHMeshHandle_lib_handle_get") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper), intent(in) :: farg1
type(C_PTR) :: fresult
end function

function swigc_new_PcmsInterpolatorOHMeshHandle() &
bind(C, name="_wrap_new_PcmsInterpolatorOHMeshHandle") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper) :: fresult
end function

subroutine swigc_delete_PcmsInterpolatorOHMeshHandle(farg1) &
bind(C, name="_wrap_delete_PcmsInterpolatorOHMeshHandle")
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper), intent(inout) :: farg1
end subroutine

subroutine swigc_PcmsInterpolatorOHMeshHandle_op_assign__(farg1, farg2) &
bind(C, name="_wrap_PcmsInterpolatorOHMeshHandle_op_assign__")
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper), intent(inout) :: farg1
type(SwigClassWrapper), intent(in) :: farg2
end subroutine

subroutine swigc_PcmsInterpolatorHandle_pointer_set(farg1, farg2) &
bind(C, name="_wrap_PcmsInterpolatorHandle_pointer_set")
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper), intent(in) :: farg1
type(C_PTR), intent(in) :: farg2
end subroutine

function swigc_PcmsInterpolatorHandle_pointer_get(farg1) &
bind(C, name="_wrap_PcmsInterpolatorHandle_pointer_get") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper), intent(in) :: farg1
type(C_PTR) :: fresult
end function

function swigc_new_PcmsInterpolatorHandle() &
bind(C, name="_wrap_new_PcmsInterpolatorHandle") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper) :: fresult
end function

subroutine swigc_delete_PcmsInterpolatorHandle(farg1) &
bind(C, name="_wrap_delete_PcmsInterpolatorHandle")
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper), intent(inout) :: farg1
end subroutine

subroutine swigc_PcmsInterpolatorHandle_op_assign__(farg1, farg2) &
bind(C, name="_wrap_PcmsInterpolatorHandle_op_assign__")
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper), intent(inout) :: farg1
type(SwigClassWrapper), intent(in) :: farg2
end subroutine

function swigc_pcms_create_point_based_interpolator(farg1, farg2, farg3, farg4, farg5, farg6, farg7, farg8, farg9) &
bind(C, name="_wrap_pcms_create_point_based_interpolator") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(C_PTR), intent(in) :: farg1
integer(C_INT), intent(in) :: farg2
type(C_PTR), intent(in) :: farg3
integer(C_INT), intent(in) :: farg4
real(C_DOUBLE), intent(in) :: farg5
integer(C_INT), intent(in) :: farg6
integer(C_INT), intent(in) :: farg7
real(C_DOUBLE), intent(in) :: farg8
real(C_DOUBLE), intent(in) :: farg9
type(SwigClassWrapper) :: fresult
end function

function swigc_pcms_create_degas2xgc_interpolator(farg1, farg2, farg3, farg4, farg5, farg6, farg7) &
bind(C, name="_wrap_pcms_create_degas2xgc_interpolator") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
import :: swigarraywrapper
import :: swigclasswrapper
type(SwigArrayWrapper) :: farg1
type(SwigArrayWrapper) :: farg2
real(C_DOUBLE), intent(in) :: farg3
integer(C_INT), intent(in) :: farg4
integer(C_INT), intent(in) :: farg5
real(C_DOUBLE), intent(in) :: farg6
real(C_DOUBLE), intent(in) :: farg7
type(SwigClassWrapper) :: fresult
end function

function swigc_pcms_create_degas2xgcnode_interpolator(farg1, farg2, farg3, farg4, farg5, farg6, farg7, farg8, farg9) &
bind(C, name="_wrap_pcms_create_degas2xgcnode_interpolator") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
import :: swigarraywrapper
import :: swigclasswrapper
type(C_PTR), intent(in) :: farg1
integer(C_INT), intent(in) :: farg2
type(SwigArrayWrapper) :: farg3
real(C_DOUBLE), intent(in) :: farg4
type(C_PTR), intent(in) :: farg5
integer(C_INT), intent(in) :: farg6
integer(C_INT), intent(in) :: farg7
real(C_DOUBLE), intent(in) :: farg8
real(C_DOUBLE), intent(in) :: farg9
type(SwigClassWrapper) :: fresult
end function

function swigc_pcms_create_xgcnodedegas2_interpolator(farg1, farg2, farg3, farg4, farg5, farg6, farg7, farg8, farg9) &
bind(C, name="_wrap_pcms_create_xgcnodedegas2_interpolator") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
import :: swigarraywrapper
import :: swigclasswrapper
type(SwigArrayWrapper) :: farg1
type(C_PTR), intent(in) :: farg2
integer(C_INT), intent(in) :: farg3
real(C_DOUBLE), intent(in) :: farg4
type(C_PTR), intent(in) :: farg5
integer(C_INT), intent(in) :: farg6
integer(C_INT), intent(in) :: farg7
real(C_DOUBLE), intent(in) :: farg8
real(C_DOUBLE), intent(in) :: farg9
type(SwigClassWrapper) :: fresult
end function

function swigc_pcms_create_interpolator(farg1, farg2) &
bind(C, name="_wrap_pcms_create_interpolator") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper), intent(in) :: farg1
real(C_DOUBLE), intent(in) :: farg2
type(SwigClassWrapper) :: fresult
end function

subroutine swigc_pcms_destroy_interpolator(farg1) &
bind(C, name="_wrap_pcms_destroy_interpolator")
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper), intent(in) :: farg1
end subroutine

subroutine swigc_pcms_kokkos_initialize_without_args() &
bind(C, name="_wrap_pcms_kokkos_initialize_without_args")
use, intrinsic :: ISO_C_BINDING
end subroutine

subroutine swigc_pcms_kokkos_finalize() &
bind(C, name="_wrap_pcms_kokkos_finalize")
use, intrinsic :: ISO_C_BINDING
end subroutine

function swigc_read_oh_mesh(farg1) &
bind(C, name="_wrap_read_oh_mesh") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
import :: swigarraywrapper
import :: swigclasswrapper
type(SwigArrayWrapper) :: farg1
type(SwigClassWrapper) :: fresult
end function

subroutine swigc_release_oh_mesh(farg1) &
bind(C, name="_wrap_release_oh_mesh")
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper), intent(in) :: farg1
end subroutine

subroutine swigc_pcms_interpolate(farg1, farg2, farg3, farg4, farg5) &
bind(C, name="_wrap_pcms_interpolate")
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper), intent(in) :: farg1
type(C_PTR), intent(in) :: farg2
integer(C_INT), intent(in) :: farg3
type(C_PTR), intent(in) :: farg4
integer(C_INT), intent(in) :: farg5
end subroutine

end interface


contains
 ! MODULE SUBPROGRAMS
subroutine swigf_PcmsInterpolatorOHMeshHandle_mesh_handle_set(self, mesh_handle)
use, intrinsic :: ISO_C_BINDING
class(PcmsInterpolatorOHMeshHandle), intent(in) :: self
type(C_PTR), intent(in) :: mesh_handle
type(SwigClassWrapper) :: farg1 
type(C_PTR) :: farg2 

farg1 = self%swigdata
farg2 = mesh_handle
call swigc_PcmsInterpolatorOHMeshHandle_mesh_handle_set(farg1, farg2)
end subroutine

function swigf_PcmsInterpolatorOHMeshHandle_mesh_handle_get(self) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
type(C_PTR) :: swig_result
class(PcmsInterpolatorOHMeshHandle), intent(in) :: self
type(C_PTR) :: fresult 
type(SwigClassWrapper) :: farg1 

farg1 = self%swigdata
fresult = swigc_PcmsInterpolatorOHMeshHandle_mesh_handle_get(farg1)
swig_result = fresult
end function

subroutine swigf_PcmsInterpolatorOHMeshHandle_lib_handle_set(self, lib_handle)
use, intrinsic :: ISO_C_BINDING
class(PcmsInterpolatorOHMeshHandle), intent(in) :: self
type(C_PTR), intent(in) :: lib_handle
type(SwigClassWrapper) :: farg1 
type(C_PTR) :: farg2 

farg1 = self%swigdata
farg2 = lib_handle
call swigc_PcmsInterpolatorOHMeshHandle_lib_handle_set(farg1, farg2)
end subroutine

function swigf_PcmsInterpolatorOHMeshHandle_lib_handle_get(self) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
type(C_PTR) :: swig_result
class(PcmsInterpolatorOHMeshHandle), intent(in) :: self
type(C_PTR) :: fresult 
type(SwigClassWrapper) :: farg1 

farg1 = self%swigdata
fresult = swigc_PcmsInterpolatorOHMeshHandle_lib_handle_get(farg1)
swig_result = fresult
end function

function swigf_new_PcmsInterpolatorOHMeshHandle() &
result(self)
use, intrinsic :: ISO_C_BINDING
type(PcmsInterpolatorOHMeshHandle) :: self
type(SwigClassWrapper) :: fresult 

fresult = swigc_new_PcmsInterpolatorOHMeshHandle()
self%swigdata = fresult
end function

subroutine swigf_PcmsInterpolatorOHMeshHandle_release(self)
use, intrinsic :: ISO_C_BINDING
class(PcmsInterpolatorOHMeshHandle), intent(inout) :: self
type(SwigClassWrapper) :: farg1 

farg1 = self%swigdata
if (btest(farg1%cmemflags, swig_cmem_own_bit)) then
call swigc_delete_PcmsInterpolatorOHMeshHandle(farg1)
endif
farg1%cptr = C_NULL_PTR
farg1%cmemflags = 0
self%swigdata = farg1
end subroutine

subroutine swigf_PcmsInterpolatorOHMeshHandle_op_assign__(self, other)
use, intrinsic :: ISO_C_BINDING
class(PcmsInterpolatorOHMeshHandle), intent(inout) :: self
type(PcmsInterpolatorOHMeshHandle), intent(in) :: other
type(SwigClassWrapper) :: farg1 
type(SwigClassWrapper) :: farg2 

farg1 = self%swigdata
farg2 = other%swigdata
call swigc_PcmsInterpolatorOHMeshHandle_op_assign__(farg1, farg2)
self%swigdata = farg1
end subroutine

subroutine swigf_PcmsInterpolatorHandle_pointer_set(self, pointer)
use, intrinsic :: ISO_C_BINDING
class(PcmsInterpolatorHandle), intent(in) :: self
type(C_PTR), intent(in) :: pointer
type(SwigClassWrapper) :: farg1 
type(C_PTR) :: farg2 

farg1 = self%swigdata
farg2 = pointer
call swigc_PcmsInterpolatorHandle_pointer_set(farg1, farg2)
end subroutine

function swigf_PcmsInterpolatorHandle_pointer_get(self) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
type(C_PTR) :: swig_result
class(PcmsInterpolatorHandle), intent(in) :: self
type(C_PTR) :: fresult 
type(SwigClassWrapper) :: farg1 

farg1 = self%swigdata
fresult = swigc_PcmsInterpolatorHandle_pointer_get(farg1)
swig_result = fresult
end function

function swigf_new_PcmsInterpolatorHandle() &
result(self)
use, intrinsic :: ISO_C_BINDING
type(PcmsInterpolatorHandle) :: self
type(SwigClassWrapper) :: fresult 

fresult = swigc_new_PcmsInterpolatorHandle()
self%swigdata = fresult
end function

subroutine swigf_PcmsInterpolatorHandle_release(self)
use, intrinsic :: ISO_C_BINDING
class(PcmsInterpolatorHandle), intent(inout) :: self
type(SwigClassWrapper) :: farg1 

farg1 = self%swigdata
if (btest(farg1%cmemflags, swig_cmem_own_bit)) then
call swigc_delete_PcmsInterpolatorHandle(farg1)
endif
farg1%cptr = C_NULL_PTR
farg1%cmemflags = 0
self%swigdata = farg1
end subroutine

subroutine swigf_PcmsInterpolatorHandle_op_assign__(self, other)
use, intrinsic :: ISO_C_BINDING
class(PcmsInterpolatorHandle), intent(inout) :: self
type(PcmsInterpolatorHandle), intent(in) :: other
type(SwigClassWrapper) :: farg1 
type(SwigClassWrapper) :: farg2 

farg1 = self%swigdata
farg2 = other%swigdata
call swigc_PcmsInterpolatorHandle_op_assign__(farg1, farg2)
self%swigdata = farg1
end subroutine

function pcms_create_point_based_interpolator(source_points, source_points_size, target_points, target_points_size, radius, &
  degree, min_req_supports, lambda, decay_factor) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
type(PcmsInterpolatorHandle) :: swig_result
type(C_PTR), intent(in) :: source_points
integer(C_INT), intent(in) :: source_points_size
type(C_PTR), intent(in) :: target_points
integer(C_INT), intent(in) :: target_points_size
real(C_DOUBLE), intent(in) :: radius
integer(C_INT), intent(in) :: degree
integer(C_INT), intent(in) :: min_req_supports
real(C_DOUBLE), intent(in) :: lambda
real(C_DOUBLE), intent(in) :: decay_factor
type(SwigClassWrapper) :: fresult 
type(C_PTR) :: farg1 
integer(C_INT) :: farg2 
type(C_PTR) :: farg3 
integer(C_INT) :: farg4 
real(C_DOUBLE) :: farg5 
integer(C_INT) :: farg6 
integer(C_INT) :: farg7 
real(C_DOUBLE) :: farg8 
real(C_DOUBLE) :: farg9 

farg1 = source_points
farg2 = source_points_size
farg3 = target_points
farg4 = target_points_size
farg5 = radius
farg6 = degree
farg7 = min_req_supports
farg8 = lambda
farg9 = decay_factor
fresult = swigc_pcms_create_point_based_interpolator(farg1, farg2, farg3, farg4, farg5, farg6, farg7, farg8, farg9)
swig_result%swigdata = fresult
end function


subroutine SWIGTM_fin_char_Sm_(finp, iminp, temp)
  use, intrinsic :: ISO_C_BINDING
  character(len=*), intent(in) :: finp
  type(SwigArrayWrapper), intent(out) :: iminp
  character(kind=C_CHAR), dimension(:), target, allocatable, intent(out) :: temp
  integer :: i

  allocate(character(kind=C_CHAR) :: temp(len(finp) + 1))
  do i=1,len(finp)
    temp(i) = char(ichar(finp(i:i)), kind=C_CHAR)
  end do
  i = len(finp) + 1
  temp(i) = C_NULL_CHAR ! C finp compatibility
  iminp%data = c_loc(temp)
  iminp%size = len(finp, kind=C_SIZE_T)
end subroutine

function pcms_create_degas2xgc_interpolator(xgc_mesh_filename, dg2_mesh_filename, radius, degree, min_req_supports, lambda, &
  decay_factor) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
type(PcmsInterpolatorHandle) :: swig_result
character(len=*), intent(in) :: xgc_mesh_filename
character(len=*), intent(in) :: dg2_mesh_filename
real(C_DOUBLE), intent(in) :: radius
integer(C_INT), intent(in) :: degree
integer(C_INT), intent(in) :: min_req_supports
real(C_DOUBLE), intent(in) :: lambda
real(C_DOUBLE), intent(in) :: decay_factor
type(SwigClassWrapper) :: fresult 
character(kind=C_CHAR), dimension(:), allocatable, target :: farg1_temp 
type(SwigArrayWrapper) :: farg1 
character(kind=C_CHAR), dimension(:), allocatable, target :: farg2_temp 
type(SwigArrayWrapper) :: farg2 
real(C_DOUBLE) :: farg3 
integer(C_INT) :: farg4 
integer(C_INT) :: farg5 
real(C_DOUBLE) :: farg6 
real(C_DOUBLE) :: farg7 

call SWIGTM_fin_char_Sm_(xgc_mesh_filename, farg1, farg1_temp)
call SWIGTM_fin_char_Sm_(dg2_mesh_filename, farg2, farg2_temp)
farg3 = radius
farg4 = degree
farg5 = min_req_supports
farg6 = lambda
farg7 = decay_factor
fresult = swigc_pcms_create_degas2xgc_interpolator(farg1, farg2, farg3, farg4, farg5, farg6, farg7)
swig_result%swigdata = fresult
end function

function pcms_create_degas2xgcnode_interpolator(target_points, target_points_size, dg2_mesh_filename, radius, dg2_elem_count, &
  degree, min_req_supports, lambda, decay_factor) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
type(PcmsInterpolatorHandle) :: swig_result
type(C_PTR), intent(in) :: target_points
integer(C_INT), intent(in) :: target_points_size
character(len=*), intent(in) :: dg2_mesh_filename
real(C_DOUBLE), intent(in) :: radius
type(C_PTR), intent(in) :: dg2_elem_count
integer(C_INT), intent(in) :: degree
integer(C_INT), intent(in) :: min_req_supports
real(C_DOUBLE), intent(in) :: lambda
real(C_DOUBLE), intent(in) :: decay_factor
type(SwigClassWrapper) :: fresult 
type(C_PTR) :: farg1 
integer(C_INT) :: farg2 
character(kind=C_CHAR), dimension(:), allocatable, target :: farg3_temp 
type(SwigArrayWrapper) :: farg3 
real(C_DOUBLE) :: farg4 
type(C_PTR) :: farg5 
integer(C_INT) :: farg6 
integer(C_INT) :: farg7 
real(C_DOUBLE) :: farg8 
real(C_DOUBLE) :: farg9 

farg1 = target_points
farg2 = target_points_size
call SWIGTM_fin_char_Sm_(dg2_mesh_filename, farg3, farg3_temp)
farg4 = radius
farg5 = dg2_elem_count
farg6 = degree
farg7 = min_req_supports
farg8 = lambda
farg9 = decay_factor
fresult = swigc_pcms_create_degas2xgcnode_interpolator(farg1, farg2, farg3, farg4, farg5, farg6, farg7, farg8, farg9)
swig_result%swigdata = fresult
end function

function pcms_create_xgcnodedegas2_interpolator(dg2_mesh_filename, source_points, source_points_size, radius, dg2_elem_count, &
  degree, min_req_supports, lambda, decay_factor) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
type(PcmsInterpolatorHandle) :: swig_result
character(len=*), intent(in) :: dg2_mesh_filename
type(C_PTR), intent(in) :: source_points
integer(C_INT), intent(in) :: source_points_size
real(C_DOUBLE), intent(in) :: radius
type(C_PTR), intent(in) :: dg2_elem_count
integer(C_INT), intent(in) :: degree
integer(C_INT), intent(in) :: min_req_supports
real(C_DOUBLE), intent(in) :: lambda
real(C_DOUBLE), intent(in) :: decay_factor
type(SwigClassWrapper) :: fresult 
character(kind=C_CHAR), dimension(:), allocatable, target :: farg1_temp 
type(SwigArrayWrapper) :: farg1 
type(C_PTR) :: farg2 
integer(C_INT) :: farg3 
real(C_DOUBLE) :: farg4 
type(C_PTR) :: farg5 
integer(C_INT) :: farg6 
integer(C_INT) :: farg7 
real(C_DOUBLE) :: farg8 
real(C_DOUBLE) :: farg9 

call SWIGTM_fin_char_Sm_(dg2_mesh_filename, farg1, farg1_temp)
farg2 = source_points
farg3 = source_points_size
farg4 = radius
farg5 = dg2_elem_count
farg6 = degree
farg7 = min_req_supports
farg8 = lambda
farg9 = decay_factor
fresult = swigc_pcms_create_xgcnodedegas2_interpolator(farg1, farg2, farg3, farg4, farg5, farg6, farg7, farg8, farg9)
swig_result%swigdata = fresult
end function

function pcms_create_interpolator(oh_mesh, radius) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
type(PcmsInterpolatorHandle) :: swig_result
type(PcmsInterpolatorOHMeshHandle), intent(in) :: oh_mesh
real(C_DOUBLE), intent(in) :: radius
type(SwigClassWrapper) :: fresult 
type(SwigClassWrapper) :: farg1 
real(C_DOUBLE) :: farg2 

farg1 = oh_mesh%swigdata
farg2 = radius
fresult = swigc_pcms_create_interpolator(farg1, farg2)
swig_result%swigdata = fresult
end function

subroutine pcms_destroy_interpolator(interpolator)
use, intrinsic :: ISO_C_BINDING
type(PcmsInterpolatorHandle), intent(in) :: interpolator
type(SwigClassWrapper) :: farg1 

farg1 = interpolator%swigdata
call swigc_pcms_destroy_interpolator(farg1)
end subroutine

subroutine pcms_kokkos_initialize_without_args()
use, intrinsic :: ISO_C_BINDING

call swigc_pcms_kokkos_initialize_without_args()
end subroutine

subroutine pcms_kokkos_finalize()
use, intrinsic :: ISO_C_BINDING

call swigc_pcms_kokkos_finalize()
end subroutine

function read_oh_mesh(filename) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
type(PcmsInterpolatorOHMeshHandle) :: swig_result
character(len=*), intent(in) :: filename
type(SwigClassWrapper) :: fresult 
character(kind=C_CHAR), dimension(:), allocatable, target :: farg1_temp 
type(SwigArrayWrapper) :: farg1 

call SWIGTM_fin_char_Sm_(filename, farg1, farg1_temp)
fresult = swigc_read_oh_mesh(farg1)
swig_result%swigdata = fresult
end function

subroutine release_oh_mesh(oh_mesh)
use, intrinsic :: ISO_C_BINDING
type(PcmsInterpolatorOHMeshHandle), intent(in) :: oh_mesh
type(SwigClassWrapper) :: farg1 

farg1 = oh_mesh%swigdata
call swigc_release_oh_mesh(farg1)
end subroutine

subroutine pcms_interpolate(interpolator, input, input_size, output, output_size)
use, intrinsic :: ISO_C_BINDING
type(PcmsInterpolatorHandle), intent(in) :: interpolator
type(C_PTR), intent(in) :: input
integer(C_INT), intent(in) :: input_size
type(C_PTR), intent(in) :: output
integer(C_INT), intent(in) :: output_size
type(SwigClassWrapper) :: farg1 
type(C_PTR) :: farg2 
integer(C_INT) :: farg3 
type(C_PTR) :: farg4 
integer(C_INT) :: farg5 

farg1 = interpolator%swigdata
farg2 = input
farg3 = input_size
farg4 = output
farg5 = output_size
call swigc_pcms_interpolate(farg1, farg2, farg3, farg4, farg5)
end subroutine


end module
