! This file was automatically generated by SWIG (https://www.swig.org).
! Version 4.1.1+fortran
!
! Do not make changes to this file unless you know what you are doing - modify
! the SWIG interface file instead.
module pcms
 use, intrinsic :: ISO_C_BINDING
 implicit none
 private

 ! DECLARATION CONSTRUCTS
 public :: in_overlap_func
 ! enum WdmCplAdapterType
 enum, bind(c)
  enumerator :: WDMCPL_ADAPTER_XGC
  enumerator :: WDMCPL_ADAPTER_OMEGAH
  enumerator :: WDMCPL_ADAPTER_GENE
  enumerator :: WDMCPL_ADAPTER_GEM
 end enum
 integer, parameter, public :: WdmCplAdapterType = kind(WDMCPL_ADAPTER_XGC)
 public :: WDMCPL_ADAPTER_XGC, WDMCPL_ADAPTER_OMEGAH, WDMCPL_ADAPTER_GENE, WDMCPL_ADAPTER_GEM
 ! enum WdmCplType
 enum, bind(c)
  enumerator :: WDMCPL_FLOAT
  enumerator :: WDMCPL_DOUBLE
  enumerator :: WDMCPL_INT
  enumerator :: WDMCPL_LONG_INT
 end enum
 integer, parameter, public :: WdmCplType = kind(WDMCPL_FLOAT)
 public :: WDMCPL_FLOAT, WDMCPL_DOUBLE, WDMCPL_INT, WDMCPL_LONG_INT

 integer, parameter :: swig_cmem_own_bit = 0
 integer, parameter :: swig_cmem_rvalue_bit = 1
 type, bind(C) :: SwigClassWrapper
  type(C_PTR), public :: cptr = C_NULL_PTR
  integer(C_INT), public :: cmemflags = 0
 end type
 type, bind(C) :: SwigArrayWrapper
  type(C_PTR), public :: data = C_NULL_PTR
  integer(C_SIZE_T), public :: size = 0
 end type
 type, public :: SWIGTYPE_p_WdmCplClientHandle
  type(SwigClassWrapper), public :: swigdata
 end type
 public :: pcms_create_client
 public :: pcms_destroy_client
 type, public :: SWIGTYPE_p_WdmCplReverseClassificationHandle
  type(SwigClassWrapper), public :: swigdata
 end type
 public :: pcms_load_reverse_classification
 public :: pcms_destroy_reverse_classification
 public :: pcms_reverse_classification_count_verts
 type, public :: SWIGTYPE_p_WdmCplFieldAdapterHandle
  type(SwigClassWrapper), public :: swigdata
 end type
 public :: pcms_create_xgc_field_adapter
 public :: pcms_create_dummy_field_adapter
 public :: pcms_destroy_field_adapter
 type, public :: SWIGTYPE_p_WdmCplFieldHandle
  type(SwigClassWrapper), public :: swigdata
 end type
 public :: pcms_add_field
 public :: pcms_send_field_name
 public :: pcms_receive_field_name
 public :: pcms_send_field
 public :: pcms_receive_field
 public :: pcms_begin_send_phase
 public :: pcms_end_send_phase
 public :: pcms_begin_receive_phase
 public :: pcms_end_receive_phase
 public :: pcms_kokkos_initialize_without_args
 public :: pcms_kokkos_finalize

! FUNCTION POINTER DECLARATIONS
abstract interface
function in_overlap_func(dimension, id) &
bind(C) &
result(fresult)
use, intrinsic :: ISO_C_BINDING
integer(C_INT), intent(in), value :: dimension
integer(C_INT), intent(in), value :: id
integer(C_INT8_T) :: fresult
end function

end interface


! WRAPPER DECLARATIONS
interface
function swigc_pcms_create_client(farg1, farg2) &
bind(C, name="_wrap_pcms_create_client") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
import :: swigarraywrapper
import :: swigclasswrapper
type(SwigArrayWrapper) :: farg1
integer(C_INT), intent(in) :: farg2
type(SwigClassWrapper) :: fresult
end function

subroutine swigc_pcms_destroy_client(farg1) &
bind(C, name="_wrap_pcms_destroy_client")
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper), intent(in) :: farg1
end subroutine

function swigc_pcms_load_reverse_classification(farg1, farg2) &
bind(C, name="_wrap_pcms_load_reverse_classification") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
import :: swigarraywrapper
import :: swigclasswrapper
type(SwigArrayWrapper) :: farg1
integer(C_INT), intent(in) :: farg2
type(SwigClassWrapper) :: fresult
end function

subroutine swigc_pcms_destroy_reverse_classification(farg1) &
bind(C, name="_wrap_pcms_destroy_reverse_classification")
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper), intent(in) :: farg1
end subroutine

function swigc_pcms_reverse_classification_count_verts(farg1) &
bind(C, name="_wrap_pcms_reverse_classification_count_verts") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper), intent(in) :: farg1
integer(C_INT) :: fresult
end function

function swigc_pcms_create_xgc_field_adapter(farg1, farg2, farg3, farg4, farg5, farg6, farg7) &
bind(C, name="_wrap_pcms_create_xgc_field_adapter") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
import :: swigarraywrapper
import :: swigclasswrapper
type(SwigArrayWrapper) :: farg1
integer(C_INT), intent(in) :: farg2
type(C_PTR), intent(in) :: farg3
integer(C_INT), intent(in) :: farg4
integer(C_INT), intent(in) :: farg5
type(SwigClassWrapper), intent(in) :: farg6
type(C_FUNPTR), value :: farg7
type(SwigClassWrapper) :: fresult
end function

function swigc_pcms_create_dummy_field_adapter() &
bind(C, name="_wrap_pcms_create_dummy_field_adapter") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper) :: fresult
end function

subroutine swigc_pcms_destroy_field_adapter(farg1) &
bind(C, name="_wrap_pcms_destroy_field_adapter")
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper), intent(in) :: farg1
end subroutine

function swigc_pcms_add_field(farg1, farg2, farg3, farg4) &
bind(C, name="_wrap_pcms_add_field") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
import :: swigarraywrapper
import :: swigclasswrapper
type(SwigClassWrapper), intent(in) :: farg1
type(SwigArrayWrapper) :: farg2
type(SwigClassWrapper), intent(in) :: farg3
integer(C_INT), intent(in) :: farg4
type(SwigClassWrapper) :: fresult
end function

subroutine swigc_pcms_send_field_name(farg1, farg2) &
bind(C, name="_wrap_pcms_send_field_name")
use, intrinsic :: ISO_C_BINDING
import :: swigarraywrapper
import :: swigclasswrapper
type(SwigClassWrapper), intent(in) :: farg1
type(SwigArrayWrapper) :: farg2
end subroutine

subroutine swigc_pcms_receive_field_name(farg1, farg2) &
bind(C, name="_wrap_pcms_receive_field_name")
use, intrinsic :: ISO_C_BINDING
import :: swigarraywrapper
import :: swigclasswrapper
type(SwigClassWrapper), intent(in) :: farg1
type(SwigArrayWrapper) :: farg2
end subroutine

subroutine swigc_pcms_send_field(farg1) &
bind(C, name="_wrap_pcms_send_field")
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper), intent(in) :: farg1
end subroutine

subroutine swigc_pcms_receive_field(farg1) &
bind(C, name="_wrap_pcms_receive_field")
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper), intent(in) :: farg1
end subroutine

subroutine swigc_pcms_begin_send_phase(farg1) &
bind(C, name="_wrap_pcms_begin_send_phase")
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper), intent(in) :: farg1
end subroutine

subroutine swigc_pcms_end_send_phase(farg1) &
bind(C, name="_wrap_pcms_end_send_phase")
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper), intent(in) :: farg1
end subroutine

subroutine swigc_pcms_begin_receive_phase(farg1) &
bind(C, name="_wrap_pcms_begin_receive_phase")
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper), intent(in) :: farg1
end subroutine

subroutine swigc_pcms_end_receive_phase(farg1) &
bind(C, name="_wrap_pcms_end_receive_phase")
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper), intent(in) :: farg1
end subroutine

subroutine swigc_pcms_kokkos_initialize_without_args() &
bind(C, name="_wrap_pcms_kokkos_initialize_without_args")
use, intrinsic :: ISO_C_BINDING
end subroutine

subroutine swigc_pcms_kokkos_finalize() &
bind(C, name="_wrap_pcms_kokkos_finalize")
use, intrinsic :: ISO_C_BINDING
end subroutine

end interface


contains
 ! MODULE SUBPROGRAMS

subroutine SWIGTM_fin_char_Sm_(finp, iminp, temp)
  use, intrinsic :: ISO_C_BINDING
  character(len=*), intent(in) :: finp
  type(SwigArrayWrapper), intent(out) :: iminp
  character(kind=C_CHAR), dimension(:), target, allocatable, intent(out) :: temp
  integer :: i

  allocate(character(kind=C_CHAR) :: temp(len(finp) + 1))
  do i=1,len(finp)
    temp(i) = char(ichar(finp(i:i)), kind=C_CHAR)
  end do
  i = len(finp) + 1
  temp(i) = C_NULL_CHAR ! C finp compatibility
  iminp%data = c_loc(temp)
  iminp%size = len(finp, kind=C_SIZE_T)
end subroutine

function pcms_create_client(name, comm) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
type(SWIGTYPE_p_WdmCplClientHandle) :: swig_result
character(len=*), target :: name
integer :: comm
type(SwigClassWrapper) :: fresult 
character(kind=C_CHAR), dimension(:), allocatable, target :: farg1_temp 
type(SwigArrayWrapper) :: farg1 
integer(C_INT) :: farg2 

call SWIGTM_fin_char_Sm_(name, farg1, farg1_temp)
farg2 = int(comm, C_INT)
fresult = swigc_pcms_create_client(farg1, farg2)
swig_result%swigdata = fresult
end function

subroutine pcms_destroy_client(arg0)
use, intrinsic :: ISO_C_BINDING
class(SWIGTYPE_p_WdmCplClientHandle), intent(in) :: arg0
type(SwigClassWrapper) :: farg1 

farg1 = arg0%swigdata
call swigc_pcms_destroy_client(farg1)
end subroutine

function pcms_load_reverse_classification(file, comm) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
type(SWIGTYPE_p_WdmCplReverseClassificationHandle) :: swig_result
character(len=*), target :: file
integer :: comm
type(SwigClassWrapper) :: fresult 
character(kind=C_CHAR), dimension(:), allocatable, target :: farg1_temp 
type(SwigArrayWrapper) :: farg1 
integer(C_INT) :: farg2 

call SWIGTM_fin_char_Sm_(file, farg1, farg1_temp)
farg2 = int(comm, C_INT)
fresult = swigc_pcms_load_reverse_classification(farg1, farg2)
swig_result%swigdata = fresult
end function

subroutine pcms_destroy_reverse_classification(arg0)
use, intrinsic :: ISO_C_BINDING
class(SWIGTYPE_p_WdmCplReverseClassificationHandle), intent(in) :: arg0
type(SwigClassWrapper) :: farg1 

farg1 = arg0%swigdata
call swigc_pcms_destroy_reverse_classification(farg1)
end subroutine

function pcms_reverse_classification_count_verts(arg0) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
integer(C_INT) :: swig_result
class(SWIGTYPE_p_WdmCplReverseClassificationHandle), intent(in) :: arg0
integer(C_INT) :: fresult 
type(SwigClassWrapper) :: farg1 

farg1 = arg0%swigdata
fresult = swigc_pcms_reverse_classification_count_verts(farg1)
swig_result = fresult
end function

function pcms_create_xgc_field_adapter(name, plane_comm, data, size, data_type, rc, in_overlap) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
type(SWIGTYPE_p_WdmCplFieldAdapterHandle) :: swig_result
character(len=*), target :: name
integer :: plane_comm
type(C_PTR), intent(in) :: data
integer(C_INT), intent(in) :: size
integer(WdmCplType), intent(in) :: data_type
class(SWIGTYPE_p_WdmCplReverseClassificationHandle), intent(in) :: rc
procedure(in_overlap_func) :: in_overlap
type(SwigClassWrapper) :: fresult 
character(kind=C_CHAR), dimension(:), allocatable, target :: farg1_temp 
type(SwigArrayWrapper) :: farg1 
integer(C_INT) :: farg2 
type(C_PTR) :: farg3 
integer(C_INT) :: farg4 
integer(C_INT) :: farg5 
type(SwigClassWrapper) :: farg6 
type(C_FUNPTR) :: farg7 

call SWIGTM_fin_char_Sm_(name, farg1, farg1_temp)
farg2 = int(plane_comm, C_INT)
farg3 = data
farg4 = size
farg5 = data_type
farg6 = rc%swigdata
farg7 = c_funloc(in_overlap)
fresult = swigc_pcms_create_xgc_field_adapter(farg1, farg2, farg3, farg4, farg5, farg6, farg7)
swig_result%swigdata = fresult
end function

function pcms_create_dummy_field_adapter() &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
type(SWIGTYPE_p_WdmCplFieldAdapterHandle) :: swig_result
type(SwigClassWrapper) :: fresult 

fresult = swigc_pcms_create_dummy_field_adapter()
swig_result%swigdata = fresult
end function

subroutine pcms_destroy_field_adapter(arg0)
use, intrinsic :: ISO_C_BINDING
class(SWIGTYPE_p_WdmCplFieldAdapterHandle), intent(in) :: arg0
type(SwigClassWrapper) :: farg1 

farg1 = arg0%swigdata
call swigc_pcms_destroy_field_adapter(farg1)
end subroutine

function pcms_add_field(client_handle, name, adapter_handle, participates) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
type(SWIGTYPE_p_WdmCplFieldHandle) :: swig_result
class(SWIGTYPE_p_WdmCplClientHandle), intent(in) :: client_handle
character(len=*), target :: name
class(SWIGTYPE_p_WdmCplFieldAdapterHandle), intent(in) :: adapter_handle
integer(C_INT), intent(in) :: participates
type(SwigClassWrapper) :: fresult 
type(SwigClassWrapper) :: farg1 
character(kind=C_CHAR), dimension(:), allocatable, target :: farg2_temp 
type(SwigArrayWrapper) :: farg2 
type(SwigClassWrapper) :: farg3 
integer(C_INT) :: farg4 

farg1 = client_handle%swigdata
call SWIGTM_fin_char_Sm_(name, farg2, farg2_temp)
farg3 = adapter_handle%swigdata
farg4 = participates
fresult = swigc_pcms_add_field(farg1, farg2, farg3, farg4)
swig_result%swigdata = fresult
end function

subroutine pcms_send_field_name(arg0, name)
use, intrinsic :: ISO_C_BINDING
class(SWIGTYPE_p_WdmCplClientHandle), intent(in) :: arg0
character(len=*), target :: name
type(SwigClassWrapper) :: farg1 
character(kind=C_CHAR), dimension(:), allocatable, target :: farg2_temp 
type(SwigArrayWrapper) :: farg2 

farg1 = arg0%swigdata
call SWIGTM_fin_char_Sm_(name, farg2, farg2_temp)
call swigc_pcms_send_field_name(farg1, farg2)
end subroutine

subroutine pcms_receive_field_name(arg0, name)
use, intrinsic :: ISO_C_BINDING
class(SWIGTYPE_p_WdmCplClientHandle), intent(in) :: arg0
character(len=*), target :: name
type(SwigClassWrapper) :: farg1 
character(kind=C_CHAR), dimension(:), allocatable, target :: farg2_temp 
type(SwigArrayWrapper) :: farg2 

farg1 = arg0%swigdata
call SWIGTM_fin_char_Sm_(name, farg2, farg2_temp)
call swigc_pcms_receive_field_name(farg1, farg2)
end subroutine

subroutine pcms_send_field(arg0)
use, intrinsic :: ISO_C_BINDING
class(SWIGTYPE_p_WdmCplFieldHandle), intent(in) :: arg0
type(SwigClassWrapper) :: farg1 

farg1 = arg0%swigdata
call swigc_pcms_send_field(farg1)
end subroutine

subroutine pcms_receive_field(arg0)
use, intrinsic :: ISO_C_BINDING
class(SWIGTYPE_p_WdmCplFieldHandle), intent(in) :: arg0
type(SwigClassWrapper) :: farg1 

farg1 = arg0%swigdata
call swigc_pcms_receive_field(farg1)
end subroutine

subroutine pcms_begin_send_phase(arg0)
use, intrinsic :: ISO_C_BINDING
class(SWIGTYPE_p_WdmCplClientHandle), intent(in) :: arg0
type(SwigClassWrapper) :: farg1 

farg1 = arg0%swigdata
call swigc_pcms_begin_send_phase(farg1)
end subroutine

subroutine pcms_end_send_phase(arg0)
use, intrinsic :: ISO_C_BINDING
class(SWIGTYPE_p_WdmCplClientHandle), intent(in) :: arg0
type(SwigClassWrapper) :: farg1 

farg1 = arg0%swigdata
call swigc_pcms_end_send_phase(farg1)
end subroutine

subroutine pcms_begin_receive_phase(arg0)
use, intrinsic :: ISO_C_BINDING
class(SWIGTYPE_p_WdmCplClientHandle), intent(in) :: arg0
type(SwigClassWrapper) :: farg1 

farg1 = arg0%swigdata
call swigc_pcms_begin_receive_phase(farg1)
end subroutine

subroutine pcms_end_receive_phase(arg0)
use, intrinsic :: ISO_C_BINDING
class(SWIGTYPE_p_WdmCplClientHandle), intent(in) :: arg0
type(SwigClassWrapper) :: farg1 

farg1 = arg0%swigdata
call swigc_pcms_end_receive_phase(farg1)
end subroutine

subroutine pcms_kokkos_initialize_without_args()
use, intrinsic :: ISO_C_BINDING

call swigc_pcms_kokkos_initialize_without_args()
end subroutine

subroutine pcms_kokkos_finalize()
use, intrinsic :: ISO_C_BINDING

call swigc_pcms_kokkos_finalize()
end subroutine


end module
