#include "redef.h"
#include "switches.h"
#include "intrinsic_sizes.h"
!>Routines required by the STELLOPT code
!!see http://vmecwiki.pppl.wikispaces.net/STELLOPT
!!\todo check which 'use' statements are actually needed
!!      adapt files.mk accordingly
module stellopt_interface
use parameters_IO
use communications,only: my_mpi_comm_world, &
     &MPI_INTEGER, MPI_REAL_TYPE, MPI_COMPLEX_TYPE, &
     &MPI_LOGICAL, MPI_CHARACTER

implicit none
public:: bcast_parameters

!private
!!the private declaration is a good idea, however, public access to
!!many parameters is required in interfaces, e.g. ITM

Contains
!> ADDED by SAL to assist STELLOPT with changes to namelist parameters
  subroutine bcast_parameters
     IMPLICIT none
     INTEGER :: ierr,n
     ! parallelization namelist already been read by initialize_comm_sim
     ! BOX Namelist
     CALL MPI_BCAST(nx0,1,MPI_INTEGER,0,my_mpi_comm_world,ierr)
     CALL MPI_BCAST(nky0,1,MPI_INTEGER,0,my_mpi_comm_world,ierr)
     CALL MPI_BCAST(nz0,1,MPI_INTEGER,0,my_mpi_comm_world,ierr)
     CALL MPI_BCAST(nv0,1,MPI_INTEGER,0,my_mpi_comm_world,ierr)
     CALL MPI_BCAST(nw0,1,MPI_INTEGER,0,my_mpi_comm_world,ierr)
     CALL MPI_BCAST(n_spec,1,MPI_INTEGER,0,my_mpi_comm_world,ierr)
     CALL MPI_BCAST(kymin,1,MPI_REAL_TYPE,0,my_mpi_comm_world,ierr)
     CALL MPI_BCAST(lv,1,MPI_REAL_TYPE,0,my_mpi_comm_world,ierr)
     CALL MPI_BCAST(lw,1,MPI_REAL_TYPE,0,my_mpi_comm_world,ierr)
     CALL MPI_BCAST(lx,1,MPI_REAL_TYPE,0,my_mpi_comm_world,ierr)
     CALL MPI_BCAST(n_spec,1,MPI_INTEGER,0,my_mpi_comm_world,ierr)
     CALL MPI_BCAST(adapt_lx,1,MPI_LOGICAL,0,my_mpi_comm_world,ierr)
     CALL MPI_BCAST(lx_a,1,MPI_REAL_TYPE,0,my_mpi_comm_world,ierr)
     CALL MPI_BCAST(x0,1,MPI_REAL_TYPE,0,my_mpi_comm_world,ierr)
     CALL MPI_BCAST(n0_global,1,MPI_INTEGER,0,my_mpi_comm_world,ierr)
     CALL MPI_BCAST(adapt_ly,1,MPI_LOGICAL,0,my_mpi_comm_world,ierr)
     CALL MPI_BCAST(ky0_ind,1,MPI_INTEGER,0,my_mpi_comm_world,ierr)
     CALL MPI_BCAST(kx_center,1,MPI_REAL_TYPE,0,my_mpi_comm_world,ierr)
     CALL MPI_BCAST(mu_grid_type,20,MPI_CHARACTER,0,my_mpi_comm_world,ierr)

     ! IN_OUT Namelist
     CALL MPI_BCAST(diagdir,128,MPI_CHARACTER,0,my_mpi_comm_world,ierr)
     CALL MPI_BCAST(chptdir,128,MPI_CHARACTER,0,my_mpi_comm_world,ierr)
     CALL MPI_BCAST(read_checkpoint,1,MPI_LOGICAL,0,my_mpi_comm_world,ierr)
     CALL MPI_BCAST(write_checkpoint,1,MPI_LOGICAL,0,my_mpi_comm_world,ierr)
     CALL MPI_BCAST(many_chpts,1,MPI_LOGICAL,0,my_mpi_comm_world,ierr)
     CALL MPI_BCAST(istep_field,1,MPI_INTEGER,0,my_mpi_comm_world,ierr)
     CALL MPI_BCAST(istep_mom,1,MPI_INTEGER,0,my_mpi_comm_world,ierr)
     CALL MPI_BCAST(istep_nrg,1,MPI_INTEGER,0,my_mpi_comm_world,ierr)
     CALL MPI_BCAST(istep_omega,1,MPI_INTEGER,0,my_mpi_comm_world,ierr)
     CALL MPI_BCAST(istep_vsp,1,MPI_INTEGER,0,my_mpi_comm_world,ierr)
     CALL MPI_BCAST(istep_schpt,1,MPI_INTEGER,0,my_mpi_comm_world,ierr)
     CALL MPI_BCAST(istep_g1,1,MPI_INTEGER,0,my_mpi_comm_world,ierr)
     CALL MPI_BCAST(istep_gav,1,MPI_INTEGER,0,my_mpi_comm_world,ierr)
     CALL MPI_BCAST(istep_energy,1,MPI_INTEGER,0,my_mpi_comm_world,ierr)
     CALL MPI_BCAST(istep_energy3d,1,MPI_INTEGER,0,my_mpi_comm_world,ierr)
     CALL MPI_BCAST(istep_nlt,1,MPI_INTEGER,0,my_mpi_comm_world,ierr)
     CALL MPI_BCAST(nlt_symmetrize,1,MPI_LOGICAL,0,my_mpi_comm_world,ierr)
     CALL MPI_BCAST(istep_dfout,1,MPI_INTEGER,0,my_mpi_comm_world,ierr)
     CALL MPI_BCAST(istep_prof,1,MPI_INTEGER,0,my_mpi_comm_world,ierr)
     CALL MPI_BCAST(write_fielddiff,1,MPI_LOGICAL,0,my_mpi_comm_world,ierr)
     CALL MPI_BCAST(istep_srcmom,1,MPI_INTEGER,0,my_mpi_comm_world,ierr)
     CALL MPI_BCAST(istep_neoclass,1,MPI_INTEGER,0,my_mpi_comm_world,ierr)
     CALL MPI_BCAST(istep_fsa_moments,1,MPI_INTEGER,0,my_mpi_comm_world,ierr)
     CALL MPI_BCAST(istep_GyroLES,1,MPI_INTEGER,0,my_mpi_comm_world,ierr)
     CALL MPI_BCAST(istep_fe_time,1,MPI_INTEGER,0,my_mpi_comm_world,ierr)
     CALL MPI_BCAST(istep_fe_twoD,1,MPI_INTEGER,0,my_mpi_comm_world,ierr)
     CALL MPI_BCAST(istep_fe_transfer,1,MPI_INTEGER,0,my_mpi_comm_world,ierr)
     CALL MPI_BCAST(write_std,1,MPI_LOGICAL,0,my_mpi_comm_world,ierr)
     CALL MPI_BCAST(write_h5,1,MPI_LOGICAL,0,my_mpi_comm_world,ierr)
     CALL MPI_BCAST(chpt_h5,1,MPI_LOGICAL,0,my_mpi_comm_world,ierr)
     CALL MPI_BCAST(chpt_read_h5,1,MPI_LOGICAL,0,my_mpi_comm_world,ierr)
     CALL MPI_BCAST(chpt_write_h5,1,MPI_LOGICAL,0,my_mpi_comm_world,ierr)
     CALL MPI_BCAST(momentum_flux,1,MPI_LOGICAL,0,my_mpi_comm_world,ierr)
     CALL MPI_BCAST(write_flux_final,1,MPI_INTEGER,0,my_mpi_comm_world,ierr)
     CALL MPI_BCAST(iterdb_file,128,MPI_CHARACTER,0,my_mpi_comm_world,ierr)
     CALL MPI_BCAST(iterdb_time,1,MPI_REAL_TYPE,0,my_mpi_comm_world,ierr)

     ! GENERAL Namelist
     CALL MPI_BCAST(nonlinear,1,MPI_LOGICAL,0,my_mpi_comm_world,ierr)
     CALL MPI_BCAST(parallel_nl,1,MPI_LOGICAL,0,my_mpi_comm_world,ierr)
     CALL MPI_BCAST(x_local,1,MPI_LOGICAL,0,my_mpi_comm_world,ierr)
     CALL MPI_BCAST(y_local,1,MPI_LOGICAL,0,my_mpi_comm_world,ierr)
     CALL MPI_BCAST(yx_order,1,MPI_LOGICAL,0,my_mpi_comm_world,ierr)
     CALL MPI_BCAST(lilo,1,MPI_LOGICAL,0,my_mpi_comm_world,ierr)
     CALL MPI_BCAST(comp_type,2,MPI_CHARACTER,0,my_mpi_comm_world,ierr)
     CALL MPI_BCAST(perf_vec,9,MPI_INTEGER,0,my_mpi_comm_world,ierr)
     CALL MPI_BCAST(nblocks,1,MPI_INTEGER,0,my_mpi_comm_world,ierr)
     CALL MPI_BCAST(parscheme,5,MPI_CHARACTER,0,my_mpi_comm_world,ierr)
     CALL MPI_BCAST(arakawa_zv,1,MPI_LOGICAL,0,my_mpi_comm_world,ierr)
     CALL MPI_BCAST(arakawa_zv_order,1,MPI_INTEGER,0,my_mpi_comm_world,ierr)
     CALL MPI_BCAST(arakawa_cons_bc,1,MPI_LOGICAL,0,my_mpi_comm_world,ierr)
     CALL MPI_BCAST(hyp_on_h,1,MPI_LOGICAL,0,my_mpi_comm_world,ierr)
     CALL MPI_BCAST(hypz_opt,1,MPI_LOGICAL,0,my_mpi_comm_world,ierr)
     CALL MPI_BCAST(which_ev,20,MPI_CHARACTER,0,my_mpi_comm_world,ierr)
     CALL MPI_BCAST(which_func_as,1,MPI_INTEGER,0,my_mpi_comm_world,ierr)
     CALL MPI_BCAST(pc_type,20,MPI_CHARACTER,0,my_mpi_comm_world,ierr)
     CALL MPI_BCAST(vec_out_limit,1,MPI_LOGICAL,0,my_mpi_comm_world,ierr)
     CALL MPI_BCAST(n_ev,1,MPI_INTEGER,0,my_mpi_comm_world,ierr)
     CALL MPI_BCAST(ev_prec,1,MPI_REAL_TYPE,0,my_mpi_comm_world,ierr)
     CALL MPI_BCAST(ev_shift,1,MPI_COMPLEX_TYPE,0,my_mpi_comm_world,ierr)
     CALL MPI_BCAST(ev_max_it,1,MPI_INTEGER,0,my_mpi_comm_world,ierr)
     CALL MPI_BCAST(ev_n_test,1,MPI_INTEGER,0,my_mpi_comm_world,ierr)
     CALL MPI_BCAST(timescheme,6,MPI_CHARACTER,0,my_mpi_comm_world,ierr)
     CALL MPI_BCAST(coll_split,1,MPI_LOGICAL,0,my_mpi_comm_world,ierr)
     CALL MPI_BCAST(coll_split_scheme,6,MPI_CHARACTER,0,my_mpi_comm_world,ierr)
     CALL MPI_BCAST(calc_dt,1,MPI_LOGICAL,0,my_mpi_comm_world,ierr)
     CALL MPI_BCAST(dt_max,1,MPI_REAL_TYPE,0,my_mpi_comm_world,ierr)
     CALL MPI_BCAST(courant,1,MPI_REAL_TYPE,0,my_mpi_comm_world,ierr)
     CALL MPI_BCAST(precomp_nc,1,MPI_LOGICAL,0,my_mpi_comm_world,ierr)
     CALL MPI_BCAST(include_f0_contr,1,MPI_LOGICAL,0,my_mpi_comm_world,ierr)
     CALL MPI_BCAST(nc_prec,1,MPI_REAL_TYPE,0,my_mpi_comm_world,ierr)
     CALL MPI_BCAST(nc_max_it,1,MPI_INTEGER,0,my_mpi_comm_world,ierr)
     CALL MPI_BCAST(timelim,1,MPI_INTEGER,0,my_mpi_comm_world,ierr)
     CALL MPI_BCAST(ntimesteps,1,MPI_INTEGER,0,my_mpi_comm_world,ierr)
     CALL MPI_BCAST(simtimelim,1,MPI_REAL_TYPE,0,my_mpi_comm_world,ierr)
     CALL MPI_BCAST(overflow_limit,1,MPI_REAL_TYPE,0,my_mpi_comm_world,ierr)
     CALL MPI_BCAST(underflow_limit,1,MPI_REAL_TYPE,0,my_mpi_comm_world,ierr)
     CALL MPI_BCAST(omega_prec,1,MPI_REAL_TYPE,0,my_mpi_comm_world,ierr)
     CALL MPI_BCAST(beta,1,MPI_REAL_TYPE,0,my_mpi_comm_world,ierr)
     CALL MPI_BCAST(debye2,1,MPI_REAL_TYPE,0,my_mpi_comm_world,ierr)
     CALL MPI_BCAST(bpar,1,MPI_LOGICAL,0,my_mpi_comm_world,ierr)
     CALL MPI_BCAST(Apar0_antenna,1,MPI_REAL_TYPE,0,my_mpi_comm_world,ierr)
     CALL MPI_BCAST(omega0_antenna,1,MPI_REAL_TYPE,0,my_mpi_comm_world,ierr)
     CALL MPI_BCAST(tau,1,MPI_REAL_TYPE,0,my_mpi_comm_world,ierr)
     CALL MPI_BCAST(delzonal,1,MPI_LOGICAL,0,my_mpi_comm_world,ierr)
     CALL MPI_BCAST(delzonal_fields,1,MPI_LOGICAL,0,my_mpi_comm_world,ierr)
     CALL MPI_BCAST(delzonal_bpar,1,MPI_LOGICAL,0,my_mpi_comm_world,ierr)
     CALL MPI_BCAST(delzonal_factor,1,MPI_REAL_TYPE,0,my_mpi_comm_world,ierr)
     CALL MPI_BCAST(del_phi,1,MPI_LOGICAL,0,my_mpi_comm_world,ierr)
     CALL MPI_BCAST(del_fields,1,MPI_LOGICAL,0,my_mpi_comm_world,ierr)
     CALL MPI_BCAST(only_Er,1,MPI_LOGICAL,0,my_mpi_comm_world,ierr)
     CALL MPI_BCAST(collision_op,12,MPI_CHARACTER,0,my_mpi_comm_world,ierr)
     CALL MPI_BCAST(coll,1,MPI_REAL_TYPE,0,my_mpi_comm_world,ierr)
     CALL MPI_BCAST(coll_cons_model,16,MPI_CHARACTER,0,my_mpi_comm_world,ierr)
     CALL MPI_BCAST(spacediff,1,MPI_LOGICAL,0,my_mpi_comm_world,ierr)
     CALL MPI_BCAST(coll_f_fm_on,1,MPI_LOGICAL,0,my_mpi_comm_world,ierr)
     CALL MPI_BCAST(zeff0,1,MPI_REAL_TYPE,0,my_mpi_comm_world,ierr)
     CALL MPI_BCAST(adiabatic_mass,1,MPI_REAL_TYPE,0,my_mpi_comm_world,ierr)
     CALL MPI_BCAST(init_cond,20,MPI_CHARACTER,0,my_mpi_comm_world,ierr)
     CALL MPI_BCAST(init_aux_x,1,MPI_REAL_TYPE,0,my_mpi_comm_world,ierr)
     CALL MPI_BCAST(init_aux_y,1,MPI_REAL_TYPE,0,my_mpi_comm_world,ierr)
     CALL MPI_BCAST(init_aux_z,1,MPI_REAL_TYPE,0,my_mpi_comm_world,ierr)
     CALL MPI_BCAST(init_aux_amp,1,MPI_REAL_TYPE,0,my_mpi_comm_world,ierr)
     CALL MPI_BCAST(hyp_x,1,MPI_REAL_TYPE,0,my_mpi_comm_world,ierr)
     CALL MPI_BCAST(hyp_x_order,1,MPI_INTEGER,0,my_mpi_comm_world,ierr)
     CALL MPI_BCAST(hyp_y,1,MPI_REAL_TYPE,0,my_mpi_comm_world,ierr)
     CALL MPI_BCAST(hyp_y_order,1,MPI_INTEGER,0,my_mpi_comm_world,ierr)
     CALL MPI_BCAST(hyp_perp,1,MPI_REAL_TYPE,0,my_mpi_comm_world,ierr)
     CALL MPI_BCAST(hyp_perp_order,1,MPI_INTEGER,0,my_mpi_comm_world,ierr)
     CALL MPI_BCAST(hyp_z,1,MPI_REAL_TYPE,0,my_mpi_comm_world,ierr)
     CALL MPI_BCAST(hyp_z_order,1,MPI_INTEGER,0,my_mpi_comm_world,ierr)
     CALL MPI_BCAST(hyp_v,1,MPI_REAL_TYPE,0,my_mpi_comm_world,ierr)
     CALL MPI_BCAST(GyroLES,1,MPI_LOGICAL,0,my_mpi_comm_world,ierr)
     CALL MPI_BCAST(diag_GyroLES,1,MPI_LOGICAL,0,my_mpi_comm_world,ierr)
     CALL MPI_BCAST(fracx,1,MPI_REAL_TYPE,0,my_mpi_comm_world,ierr)
     CALL MPI_BCAST(fracy,1,MPI_REAL_TYPE,0,my_mpi_comm_world,ierr)
     CALL MPI_BCAST(tkx,1,MPI_LOGICAL,0,my_mpi_comm_world,ierr)
     CALL MPI_BCAST(tky,1,MPI_LOGICAL,0,my_mpi_comm_world,ierr)
     CALL MPI_BCAST(tkperp,1,MPI_LOGICAL,0,my_mpi_comm_world,ierr)
     CALL MPI_BCAST(t_log_ky,1,MPI_LOGICAL,0,my_mpi_comm_world,ierr)
     CALL MPI_BCAST(t_log_kperp,1,MPI_LOGICAL,0,my_mpi_comm_world,ierr)
     CALL MPI_BCAST(t_log_kperp_fb,1,MPI_LOGICAL,0,my_mpi_comm_world,ierr)
     CALL MPI_BCAST(t_log_kperp_1,1,MPI_LOGICAL,0,my_mpi_comm_world,ierr)
     CALL MPI_BCAST(tk3_kx,1,MPI_LOGICAL,0,my_mpi_comm_world,ierr)
     CALL MPI_BCAST(tk3_ky,1,MPI_LOGICAL,0,my_mpi_comm_world,ierr)
     CALL MPI_BCAST(tk3_log_kperp,1,MPI_LOGICAL,0,my_mpi_comm_world,ierr)
     CALL MPI_BCAST(tk3_log_kperp_1,1,MPI_LOGICAL,0,my_mpi_comm_world,ierr)
     CALL MPI_BCAST(tk3_log_kperp_h,1,MPI_LOGICAL,0,my_mpi_comm_world,ierr)
     CALL MPI_BCAST(n_shells_kperp,1,MPI_INTEGER,0,my_mpi_comm_world,ierr)
     CALL MPI_BCAST(n_shells_log_ky,1,MPI_INTEGER,0,my_mpi_comm_world,ierr)
     CALL MPI_BCAST(n_shells_log_kperp,1,MPI_INTEGER,0,my_mpi_comm_world,ierr)
     CALL MPI_BCAST(n_shells_log_kperp_1,1,MPI_INTEGER,0,my_mpi_comm_world,ierr)
     CALL MPI_BCAST(lambda1,1,MPI_REAL_TYPE,0,my_mpi_comm_world,ierr)
     CALL MPI_BCAST(lambda2,1,MPI_REAL_TYPE,0,my_mpi_comm_world,ierr)
     CALL MPI_BCAST(coeff_g1_en_source,1,MPI_REAL_TYPE,0,my_mpi_comm_world,ierr)
     CALL MPI_BCAST(perf_tsteps,1,MPI_INTEGER,0,my_mpi_comm_world,ierr)
     CALL MPI_BCAST(diag_trap_levels,1,MPI_INTEGER,0,my_mpi_comm_world,ierr)
     CALL MPI_BCAST(diag_Blev(0:9),10,MPI_REAL_TYPE,0,my_mpi_comm_world,ierr)
     CALL MPI_BCAST(avgflux_stime,1,MPI_REAL_TYPE,0,my_mpi_comm_world,ierr)
     CALL MPI_BCAST(avgflux_type,1,MPI_INTEGER,0,my_mpi_comm_world,ierr)
     CALL MPI_BCAST(avgflux_alpha,1,MPI_REAL_TYPE,0,my_mpi_comm_world,ierr)
     CALL MPI_BCAST(avgprof_stime,1,MPI_REAL_TYPE,0,my_mpi_comm_world,ierr)
     CALL MPI_BCAST(gav_stime,1,MPI_REAL_TYPE,0,my_mpi_comm_world,ierr)
     CALL MPI_BCAST(trap_pass,1,MPI_LOGICAL,0,my_mpi_comm_world,ierr)

     ! GEOMETRY Namelist
     CALL MPI_BCAST(magn_geometry,80,MPI_CHARACTER,0,my_mpi_comm_world,ierr)
     CALL MPI_BCAST(shat,1,MPI_REAL_TYPE,0,my_mpi_comm_world,ierr)
     CALL MPI_BCAST(parscale,1,MPI_REAL_TYPE,0,my_mpi_comm_world,ierr)
     CALL MPI_BCAST(trpeps,1,MPI_REAL_TYPE,0,my_mpi_comm_world,ierr)
     CALL MPI_BCAST(q0,1,MPI_REAL_TYPE,0,my_mpi_comm_world,ierr)
     CALL MPI_BCAST(shat,1,MPI_REAL_TYPE,0,my_mpi_comm_world,ierr)
     CALL MPI_BCAST(Bprof_coeffs(0:8),9,MPI_REAL_TYPE,0,my_mpi_comm_world,ierr)
     CALL MPI_BCAST(major_R,1,MPI_REAL_TYPE,0,my_mpi_comm_world,ierr)
     CALL MPI_BCAST(amhd,1,MPI_REAL_TYPE,0,my_mpi_comm_world,ierr)
     CALL MPI_BCAST(minor_r,1,MPI_REAL_TYPE,0,my_mpi_comm_world,ierr)
     CALL MPI_BCAST(q_coeffs(0:5),6,MPI_REAL_TYPE,0,my_mpi_comm_world,ierr)
     CALL MPI_BCAST(major_Z,1,MPI_REAL_TYPE,0,my_mpi_comm_world,ierr)
     CALL MPI_BCAST(kappa,1,MPI_REAL_TYPE,0,my_mpi_comm_world,ierr)
     CALL MPI_BCAST(delta,1,MPI_REAL_TYPE,0,my_mpi_comm_world,ierr)
     CALL MPI_BCAST(zeta,1,MPI_REAL_TYPE,0,my_mpi_comm_world,ierr)
     CALL MPI_BCAST(s_kappa,1,MPI_REAL_TYPE,0,my_mpi_comm_world,ierr)
     CALL MPI_BCAST(s_delta,1,MPI_REAL_TYPE,0,my_mpi_comm_world,ierr)
     CALL MPI_BCAST(s_zeta,1,MPI_REAL_TYPE,0,my_mpi_comm_world,ierr)
     CALL MPI_BCAST(drR,1,MPI_REAL_TYPE,0,my_mpi_comm_world,ierr)
     CALL MPI_BCAST(drZ,1,MPI_REAL_TYPE,0,my_mpi_comm_world,ierr)
     CALL MPI_BCAST(edge_opt,1,MPI_REAL_TYPE,0,my_mpi_comm_world,ierr)
     CALL MPI_BCAST(geomdir,100,MPI_CHARACTER,0,my_mpi_comm_world,ierr)
     CALL MPI_BCAST(geomfile,80,MPI_CHARACTER,0,my_mpi_comm_world,ierr)
     CALL MPI_BCAST(x_def,80,MPI_CHARACTER,0,my_mpi_comm_world,ierr)
     CALL MPI_BCAST(flux_pos,1,MPI_REAL_TYPE,0,my_mpi_comm_world,ierr)
     CALL MPI_BCAST(force_x,1,MPI_REAL_TYPE,0,my_mpi_comm_world,ierr)
     CALL MPI_BCAST(force_z,1,MPI_REAL_TYPE,0,my_mpi_comm_world,ierr)
     CALL MPI_BCAST(mag_prof,1,MPI_LOGICAL,0,my_mpi_comm_world,ierr)
     CALL MPI_BCAST(limit_shat,1,MPI_LOGICAL,0,my_mpi_comm_world,ierr)
     CALL MPI_BCAST(rhostar,1,MPI_REAL_TYPE,0,my_mpi_comm_world,ierr)
     CALL MPI_BCAST(dpdx_term,13,MPI_CHARACTER,0,my_mpi_comm_world,ierr)
     CALL MPI_BCAST(dpdx_pm,1,MPI_REAL_TYPE,0,my_mpi_comm_world,ierr)
     CALL MPI_BCAST(norm_flux_projection,1,MPI_LOGICAL,0,my_mpi_comm_world,ierr)

     ! SPECIES Namelist (don't worry about allocations because number of species
     !                   does not change from run to run STELLOPT)
     DO n=0,n_spec-1
        CALL MPI_BCAST(spec(n)%name,10,MPI_CHARACTER,0,my_mpi_comm_world,ierr)
        CALL MPI_BCAST(spec(n)%passive,1,MPI_LOGICAL,0,my_mpi_comm_world,ierr)
        CALL MPI_BCAST(spec(n)%omn,1,MPI_REAL_TYPE,0,my_mpi_comm_world,ierr)
        CALL MPI_BCAST(spec(n)%omt,1,MPI_REAL_TYPE,0,my_mpi_comm_world,ierr)
        CALL MPI_BCAST(spec(n)%prof_type,1,MPI_INTEGER,0,my_mpi_comm_world,ierr)
        CALL MPI_BCAST(spec(n)%kappa_T,1,MPI_REAL_TYPE,0,my_mpi_comm_world,ierr)
        CALL MPI_BCAST(spec(n)%LT_center,1,MPI_REAL_TYPE,0,my_mpi_comm_world,ierr)
        CALL MPI_BCAST(spec(n)%LT_width,1,MPI_REAL_TYPE,0,my_mpi_comm_world,ierr)
        CALL MPI_BCAST(spec(n)%kappa_n,1,MPI_REAL_TYPE,0,my_mpi_comm_world,ierr)
        CALL MPI_BCAST(spec(n)%Ln_center,1,MPI_REAL_TYPE,0,my_mpi_comm_world,ierr)
        CALL MPI_BCAST(spec(n)%Ln_width,1,MPI_REAL_TYPE,0,my_mpi_comm_world,ierr)
        CALL MPI_BCAST(spec(n)%delta_x_T,1,MPI_REAL_TYPE,0,my_mpi_comm_world,ierr)
        CALL MPI_BCAST(spec(n)%delta_x_n,1,MPI_REAL_TYPE,0,my_mpi_comm_world,ierr)
        CALL MPI_BCAST(spec(n)%mass,1,MPI_REAL_TYPE,0,my_mpi_comm_world,ierr)
        CALL MPI_BCAST(spec(n)%temp,1,MPI_REAL_TYPE,0,my_mpi_comm_world,ierr)
        CALL MPI_BCAST(spec(n)%dens,1,MPI_REAL_TYPE,0,my_mpi_comm_world,ierr)
        CALL MPI_BCAST(spec(n)%charge,1,MPI_INTEGER,0,my_mpi_comm_world,ierr)
        CALL MPI_BCAST(spec(n)%src_prof_type(0:4),5,MPI_REAL_TYPE,0,my_mpi_comm_world,ierr)
        CALL MPI_BCAST(spec(n)%src_amp(0:4),5,MPI_REAL_TYPE,0,my_mpi_comm_world,ierr)
        CALL MPI_BCAST(spec(n)%src_width(0:4),5,MPI_REAL_TYPE,0,my_mpi_comm_world,ierr)
        CALL MPI_BCAST(spec(n)%src_x0(0:4),5,MPI_REAL_TYPE,0,my_mpi_comm_world,ierr)
     END DO

     ! Do some checks
     CALL set_in_prof_defaults()
     CALL check_extended
     CALL check_params(par_in_dir)

     RETURN

  end subroutine bcast_parameters
end module stellopt_interface
