name: build-test
on: 
  push:
  schedule:
    - cron: '12 14 * * 3'

jobs:
  buildTest:
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    strategy:
      matrix:
        build_type: [Release]
        memory_test: [ON, OFF]
        compiler: [g++]
        language: ['cpp']
        exclude:
          - build_type: Release
            memory_test: ON
          - build_type: RelWithDebInfo
            memory_test: OFF
      
    steps:

    # - name: Update packages
    #   run: sudo apt-get update

    # - name: Install mpi
    #   run: sudo apt-get install -yq mpich libmpich-dev

    # - name: Install Valgrind
    #   run: sudo apt-get install -yq valgrind

    - uses: actions/checkout@v4

    - name: build kokkos
      uses: ./.github/actions/install-repo
      with:
        repo-name: 'kokkos'
        repo-path: 'kokkos/kokkos'
        repo-ref: '4.2.00'
        options: '-DCMAKE_CXX_COMPILER=${{ matrix.compiler }}
                  -DKokkos_ENABLE_SERIAL=ON
                  -DKokkos_ENABLE_OPENMP=off
                  -DKokkos_ENABLE_CUDA=off
                  -DKokkos_ENABLE_CUDA_LAMBDA=off
                  -DKokkos_ENABLE_DEBUG=on'

    # - name: build ADIOS2
    #   uses: ./.github/actions/install-repo
    #   with:
    #     repo-name: 'ADIOS2'
    #     repo-path: 'ornladios/ADIOS2'
    #     repo-ref: 'master'
    #     options: '-DADIOS2_USE_CUDA=off
    #               -DCMAKE_BUILD_TYPE=Release
    #               -DCMAKE_CXX_COMPILER=mpicxx
    #               -DCMAKE_C_COMPILER=mpicc'